//! pi_js::fs parity with node v24.21.0 `node:fs` / `node:fs/promises`.
//!
//! `NODE_FS_ERRORS` (bottom of the file) was generated by running the same scenarios with
//! node on macOS against the layout built by [`layout`]; `$T` stands for the (canonical)
//! temp directory.

use std::path::Path;

use pi_js::env::testing::CwdGuard;
use pi_js::error::Error;
use pi_js::fs::{self, constants, promises};

#[derive(Debug)]
#[allow(dead_code)]
struct E {
    name: &'static str,
    message: &'static str,
    code: Option<&'static str>,
    errno: Option<i32>,
    syscall: Option<&'static str>,
    path: Option<&'static str>,
    dest: Option<&'static str>,
}

/// The layout the node generator used.
fn layout() -> (tempfile::TempDir, String) {
    let dir = tempfile::TempDir::new().unwrap();
    let t = std::fs::canonicalize(dir.path())
        .unwrap()
        .to_string_lossy()
        .into_owned();
    let p = |rel: &str| format!("{t}/{rel}");
    std::fs::write(p("file"), "hello").unwrap();
    std::fs::write(p("file2"), "two").unwrap();
    std::fs::create_dir(p("dir")).unwrap();
    std::fs::write(p("dir/c"), "c").unwrap();
    std::fs::create_dir(p("empty")).unwrap();
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::os::unix::fs::symlink(p("file"), p("link-file")).unwrap();
        std::os::unix::fs::symlink(p("missing"), p("dangling")).unwrap();
        std::os::unix::fs::symlink(p("dir"), p("link-dir")).unwrap();
        std::fs::create_dir(p("locked")).unwrap();
        std::fs::write(p("locked/f"), "f").unwrap();
        std::fs::set_permissions(p("locked"), std::fs::Permissions::from_mode(0o500)).unwrap();
    }
    (dir, t)
}

#[cfg(unix)]
fn unlock(t: &str) {
    use std::os::unix::fs::PermissionsExt;
    let _ = std::fs::set_permissions(format!("{t}/locked"), std::fs::Permissions::from_mode(0o700));
}

#[derive(Debug, PartialEq)]
struct Got {
    name: Option<String>,
    message: String,
    code: Option<String>,
    errno: Option<i32>,
    syscall: Option<String>,
    path: Option<String>,
    dest: Option<String>,
}

fn got(e: &Error) -> Got {
    match e {
        Error::Node(n) => Got {
            name: None,
            message: n.message.clone(),
            code: Some(n.code.clone()),
            errno: Some(n.errno),
            syscall: Some(n.syscall.clone()),
            path: n.path.clone(),
            dest: n.dest.clone(),
        },
        Error::Js(j) => Got {
            name: Some(j.name.clone()),
            message: j.message.clone(),
            code: j.code.clone(),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        },
        other => panic!("unexpected error kind: {other:?}"),
    }
}

fn want(e: &E, t: &str, compare_errno: bool, errno: Option<i32>) -> Got {
    let s = |v: &str| v.replace("$T", t);
    Got {
        // NodeError has no `name` (it is "Error", or "SystemError" for ERR_FS_*).
        name: if e.name == "TypeError" {
            Some("TypeError".into())
        } else {
            None
        },
        message: s(e.message),
        code: e.code.map(s),
        errno: if compare_errno { e.errno } else { errno },
        syscall: e.syscall.map(s),
        path: e.path.map(s),
        dest: e.dest.map(s),
    }
}

fn drop_ok<T>(r: pi_js::error::Result<T>) -> pi_js::error::Result<()> {
    r.map(|_| ())
}

fn sync_scenario(name: &str, t: &str) -> Option<pi_js::error::Result<()>> {
    let j = |rel: &str| format!("{t}/{rel}");
    Some(match name {
        "readFile_missing" => drop_ok(fs::read_file(&j("missing"))),
        "readFile_dir" => drop_ok(fs::read_file(&j("dir"))),
        "readFile_notdir" => drop_ok(fs::read_file(&j("file/x"))),
        "writeFile_dir" => fs::write_file(&j("dir"), "x", None),
        "writeFile_noparent" => fs::write_file(&j("missing/x"), "x", None),
        "writeFile_wx" => fs::write_file_with_flag(&j("file"), "x", "wx", None),
        "writeFile_badflag" => fs::write_file_with_flag(&j("newfile"), "x", "zz", None),
        "appendFile_dir" => fs::append_file(&j("dir"), "x"),
        "mkdir_exists" => fs::mkdir(&j("dir"), false, None),
        "mkdir_noparent" => fs::mkdir(&j("missing/x"), false, None),
        "mkdir_under_file" => fs::mkdir(&j("file/a"), false, None),
        "mkdir_rec_under_file" => fs::mkdir(&j("file/a/b"), true, None),
        "mkdir_rec_on_file" => fs::mkdir(&j("file"), true, None),
        "mkdir_rec_existing" => fs::mkdir(&j("dir"), true, None),
        "readdir_missing" => drop_ok(fs::readdir(&j("missing"))),
        "readdir_file" => drop_ok(fs::readdir(&j("file"))),
        "stat_missing" => drop_ok(fs::stat(&j("missing"))),
        "stat_dangling" => drop_ok(fs::stat(&j("dangling"))),
        "stat_notdir" => drop_ok(fs::stat(&j("file/x"))),
        "lstat_missing" => drop_ok(fs::lstat(&j("missing"))),
        "rm_missing" => fs::rm(&j("missing"), false, false),
        "rm_missing_force" => fs::rm(&j("missing"), false, true),
        "rm_dir" => fs::rm(&j("dir"), false, false),
        "rm_dir_force" => fs::rm(&j("dir"), false, true),
        "rm_notdir" => fs::rm(&j("file/x"), false, false),
        "rm_notdir_force" => fs::rm(&j("file/x"), false, true),
        "rm_notdir_recursive" => fs::rm(&j("file/x"), true, false),
        "rm_notdir_recursive_force" => fs::rm(&j("file/x"), true, true),
        "rm_locked_recursive" => fs::rm(&j("locked"), true, true),
        "unlink_missing" => fs::unlink(&j("missing")),
        "unlink_dir" => fs::unlink(&j("dir")),
        "rmdir_nonempty" => fs::rmdir(&j("dir")),
        "rmdir_missing" => fs::rmdir(&j("missing")),
        "rmdir_file" => fs::rmdir(&j("file")),
        "rename_missing" => fs::rename(&j("missing"), &j("other")),
        "rename_dir_to_file" => fs::rename(&j("dir"), &j("file")),
        "rename_file_to_nonempty_dir" => fs::rename(&j("file"), &j("dir")),
        "copyFile_missing" => fs::copy_file(&j("missing"), &j("other")),
        "copyFile_excl" => fs::copy_file_mode(&j("file"), &j("file2"), constants::COPYFILE_EXCL),
        "copyFile_dir_src" => fs::copy_file(&j("dir"), &j("other")),
        "copyFile_dest_dir" => fs::copy_file(&j("file"), &j("dir")),
        "realpath_missing" => drop_ok(fs::realpath(&j("missing/x"))),
        "realpath_dangling" => drop_ok(fs::realpath(&j("dangling"))),
        "realpath_link_missing" => drop_ok(fs::realpath(&j("link-dir/missing"))),
        "realpath_notdir" => drop_ok(fs::realpath(&j("file/x"))),
        "realpathNative_missing" => drop_ok(fs::realpath_native(&j("missing/x"))),
        "chmod_missing" => fs::chmod(&j("missing"), 0o644),
        "mkdtemp_missing" => drop_ok(fs::mkdtemp(&j("missing/pre-"))),
        "symlink_exists" => fs::symlink("target", &j("file")),
        "readlink_file" => drop_ok(fs::readlink(&j("file"))),
        "readlink_missing" => drop_ok(fs::readlink(&j("missing"))),
        "link_missing" => fs::link(&j("missing"), &j("other")),
        "link_exists" => fs::link(&j("file"), &j("file2")),
        "utimes_missing" => fs::utimes(&j("missing"), 0.0, 0.0),
        "truncate_missing" => fs::truncate(&j("missing"), 0),
        "truncate_dir" => fs::truncate(&j("dir"), 0),
        "access_missing" => fs::access(&j("missing"), constants::F_OK),
        "open_wx" => drop_ok(fs::open(&j("file"), "wx", None)),
        "open_missing" => drop_ok(fs::open(&j("missing"), "r", None)),
        "open_badflag" => drop_ok(fs::open(&j("file"), "rw", None)),
        "nul_readFile" => drop_ok(fs::read_file("/x\0y")),
        "nul_rename_old" => fs::rename("/a\0", "/b"),
        "nul_rename_new" => fs::rename("/a", "/b\0"),
        "nul_mkdtemp" => drop_ok(fs::mkdtemp("p\0")),
        "nul_symlink_target" => fs::symlink("t\0", "/x"),
        "nul_symlink_path" => fs::symlink("t", "/x\0"),
        "nul_copy_src" => fs::copy_file("a\0", "b"),
        "nul_copy_dest" => fs::copy_file("a", "b\0"),
        "nul_link_existing" => fs::link("a\0", "b"),
        "nul_link_new" => fs::link("a", "b\0"),
        "nul_quote_single" => drop_ok(fs::read_file("a'b\0")),
        "nul_quote_double" => drop_ok(fs::read_file("a'b\"c\0")),
        "nul_quote_backtick" => drop_ok(fs::read_file("a'b\"c`\0")),
        "nul_escapes" => drop_ok(fs::read_file("\0\n\t\u{8}\u{c}\r\u{b}\u{1b}\u{7f}\u{9f} é\\😀")),
        "nul_long" => drop_ok(fs::read_file(&format!("{}\0", "x".repeat(200)))),
        "nul_long_lines" => drop_ok(fs::read_file(&format!("{}\0", "line of text\n".repeat(12)))),
        "nul_short_lines" => drop_ok(fs::read_file("a\nb\0")),
        "nul_stat" => drop_ok(fs::stat("a\0")),
        "nul_lstat" => drop_ok(fs::lstat("a\0")),
        "nul_writeFile" => fs::write_file("a\0", "", None),
        "nul_appendFile" => fs::append_file("a\0", ""),
        "nul_mkdir" => fs::mkdir("a\0", false, None),
        "nul_readdir" => drop_ok(fs::readdir("a\0")),
        "nul_rm" => fs::rm("a\0", false, false),
        "nul_unlink" => fs::unlink("a\0"),
        "nul_rmdir" => fs::rmdir("a\0"),
        "nul_chmod" => fs::chmod("a\0", 0o644),
        "nul_utimes" => fs::utimes("a\0", 0.0, 0.0),
        "nul_access" => fs::access("a\0", constants::F_OK),
        "nul_realpath" => drop_ok(fs::realpath("a\0")),
        "nul_open" => drop_ok(fs::open("a\0", "r", None)),
        "nul_truncate" => fs::truncate("a\0", 0),
        "nul_readlink" => drop_ok(fs::readlink("a\0")),
        _ => return None,
    })
}

async fn promise_scenario(name: &str, t: &str) -> Option<pi_js::error::Result<()>> {
    let j = |rel: &str| format!("{t}/{rel}");
    Some(match name {
        "p_readFile_missing" => drop_ok(promises::read_file(&j("missing")).await),
        "p_readFile_dir" => drop_ok(promises::read_file(&j("dir")).await),
        "p_writeFile_dir" => promises::write_file(&j("dir"), "x", None).await,
        "p_mkdir_exists" => promises::mkdir(&j("dir"), false, None).await,
        "p_mkdir_rec_under_file" => promises::mkdir(&j("file/a/b"), true, None).await,
        "p_readdir_file" => drop_ok(promises::readdir(&j("file")).await),
        "p_stat_missing" => drop_ok(promises::stat(&j("missing")).await),
        "p_lstat_missing" => drop_ok(promises::lstat(&j("missing")).await),
        "p_rm_missing" => promises::rm(&j("missing"), false, false).await,
        "p_rm_missing_force" => promises::rm(&j("missing"), false, true).await,
        "p_rm_dir" => promises::rm(&j("dir"), false, false).await,
        "p_rm_notdir" => promises::rm(&j("file/x"), false, false).await,
        "p_rm_notdir_recursive_force" => promises::rm(&j("file/x"), true, true).await,
        "p_rm_locked_recursive" => promises::rm(&j("locked"), true, true).await,
        "p_unlink_dir" => promises::unlink(&j("dir")).await,
        "p_rmdir_nonempty" => promises::rmdir(&j("dir")).await,
        "p_rename_missing" => promises::rename(&j("missing"), &j("other")).await,
        "p_copyFile_missing" => promises::copy_file(&j("missing"), &j("other")).await,
        "p_copyFile_excl" => promises::copy_file_mode(&j("file"), &j("file2"), constants::COPYFILE_EXCL).await,
        "p_realpath_missing" => drop_ok(promises::realpath(&j("missing/x")).await),
        "p_realpath_dangling" => drop_ok(promises::realpath(&j("dangling")).await),
        "p_chmod_missing" => promises::chmod(&j("missing"), 0o644).await,
        "p_symlink_exists" => promises::symlink("target", &j("file")).await,
        "p_readlink_file" => drop_ok(promises::readlink(&j("file")).await),
        "p_link_missing" => promises::link(&j("missing"), &j("other")).await,
        "p_utimes_missing" => promises::utimes(&j("missing"), 0.0, 0.0).await,
        "p_truncate_missing" => promises::truncate(&j("missing"), 0).await,
        "p_access_missing" => promises::access(&j("missing"), constants::F_OK).await,
        "p_open_wx" => drop_ok(promises::open(&j("file"), "wx", None).await),
        "p_open_badflag" => drop_ok(promises::open(&j("file"), "rw", None).await),
        "p_nul_readFile" => drop_ok(promises::read_file("/x\0y").await),
        "p_nul_rename_new" => promises::rename("/a", "/b\0").await,
        "p_nul_mkdtemp" => drop_ok(promises::mkdtemp("p\0").await),
        _ => return None,
    })
}

/// Scenarios whose outcome differs between macOS (where the vectors were generated) and
/// other unix systems, or that need a non-root user.
fn skip(name: &str) -> bool {
    let is_root = nix::unistd::geteuid().is_root();
    let mac_only = ["unlink_dir", "p_unlink_dir", "rm_locked_recursive", "copyFile_dir_src"];
    (name.contains("locked") && is_root) || (!cfg!(target_os = "macos") && mac_only.contains(&name))
}

/// errno values shared by macOS and Linux.
fn portable_errno(code: Option<&str>) -> bool {
    matches!(
        code,
        Some("ENOENT" | "EEXIST" | "ENOTDIR" | "EISDIR" | "EACCES" | "EPERM" | "EINVAL" | "ERR_FS_EISDIR")
    )
}

fn compare(name: &str, t: &str, res: pi_js::error::Result<()>, expected: &Option<E>, failures: &mut Vec<String>) {
    match (res, expected) {
        (Ok(()), None) => {}
        (Ok(()), Some(e)) => failures.push(format!("{name}: succeeded, want error {:?}", e.message)),
        (Err(err), None) => failures.push(format!("{name}: failed with {err}, want success")),
        (Err(err), Some(e)) => {
            let g = got(&err);
            let compare_errno = cfg!(target_os = "macos") || portable_errno(e.code);
            let w = want(e, t, compare_errno, g.errno);
            if g != w {
                failures.push(format!("{name}:\n  got  {g:?}\n  want {w:?}"));
            }
        }
    }
}

#[cfg(unix)]
#[test]
fn sync_errors_match_node() {
    let (_dir, t) = layout();
    let mut failures = Vec::new();
    let mut ran = 0;
    for (name, expected) in NODE_FS_ERRORS {
        if name.starts_with("p_") || skip(name) {
            continue;
        }
        let res = sync_scenario(name, &t).unwrap_or_else(|| panic!("no scenario {name}"));
        compare(name, &t, res, expected, &mut failures);
        ran += 1;
    }
    unlock(&t);
    assert!(ran > 80, "only {ran} scenarios ran");
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[cfg(unix)]
#[tokio::test]
async fn promise_errors_match_node() {
    let (_dir, t) = layout();
    let mut failures = Vec::new();
    for (name, expected) in NODE_FS_ERRORS {
        if !name.starts_with("p_") || skip(name) {
            continue;
        }
        let res = promise_scenario(name, &t)
            .await
            .unwrap_or_else(|| panic!("no scenario {name}"));
        compare(name, &t, res, expected, &mut failures);
    }
    unlock(&t);
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

fn node_err(e: Error) -> pi_js::error::NodeError {
    match e {
        Error::Node(n) => n,
        other => panic!("expected NodeError, got {other:?}"),
    }
}

fn tmp() -> (tempfile::TempDir, String) {
    let dir = tempfile::TempDir::new().unwrap();
    let t = std::fs::canonicalize(dir.path())
        .unwrap()
        .to_string_lossy()
        .into_owned();
    (dir, t)
}

fn join(t: &str, rel: &str) -> String {
    pi_js::path::join(&[t, rel])
}

#[test]
fn read_write_append_round_trip() {
    let (_d, t) = tmp();
    let p = join(&t, "a.txt");
    fs::write_file(&p, "hello", None).unwrap();
    fs::append_file(&p, b" world").unwrap();
    assert_eq!(fs::read_to_string(&p).unwrap(), "hello world");
    assert_eq!(fs::read_file(&p).unwrap(), b"hello world");
    fs::write_file(&p, [0xffu8, b'a', 0xfe], None).unwrap();
    assert_eq!(fs::read_to_string(&p).unwrap(), "\u{fffd}a\u{fffd}");
    fs::write_file_with_flag(&join(&t, "new.txt"), "x", "wx", None).unwrap();
    assert!(fs::exists(&join(&t, "new.txt")));
}

#[cfg(unix)]
#[test]
fn modes_and_stats() {
    let (_d, t) = tmp();
    let p = join(&t, "m.txt");
    fs::write_file(&p, "12345", Some(0o600)).unwrap();
    let st = fs::stat(&p).unwrap();
    assert!(st.is_file() && !st.is_directory() && !st.is_symbolic_link());
    assert_eq!(st.size, 5);
    assert_eq!(st.mode & 0o777, 0o600);
    assert_eq!(st.mode & constants::S_IFMT, constants::S_IFREG);
    fs::chmod(&p, 0o640).unwrap();
    assert_eq!(fs::stat(&p).unwrap().mode & 0o777, 0o640);

    fs::utimes(&p, 1000.5, 2_000_000.25).unwrap();
    let st = fs::stat(&p).unwrap();
    assert_eq!(st.atime_ms, 1_000_500.0);
    assert_eq!(st.mtime_ms, 2_000_000_250.0);
    assert_eq!(st.mtime(), 2_000_000_250);
    assert_eq!(st.mtime_ns, 2_000_000_250_000_000);

    let d = join(&t, "d");
    fs::mkdir(&d, false, Some(0o700)).unwrap();
    let st = fs::stat(&d).unwrap();
    assert!(st.is_directory());
    assert_eq!(st.mode & 0o777, 0o700);
}

#[test]
fn mkdir_recursive_creates_parents() {
    let (_d, t) = tmp();
    let deep = join(&t, "a/b/c");
    fs::mkdir(&deep, true, None).unwrap();
    assert!(fs::stat(&deep).unwrap().is_directory());
    fs::mkdir(&deep, true, None).unwrap();
    fs::mkdir(&format!("{deep}/"), true, None).unwrap();
}

#[test]
fn readdir_sorts_and_reports_types() {
    let (_d, t) = tmp();
    for name in ["b", "a", "Z", "_", "a.txt", "é"] {
        fs::write_file(&join(&t, name), "", None).unwrap();
    }
    fs::mkdir(&join(&t, "sub"), false, None).unwrap();
    let names = fs::readdir(&t).unwrap();
    if cfg!(unix) {
        assert_eq!(names, ["Z", "_", "a", "a.txt", "b", "sub", "é"]);
    } else {
        assert_eq!(names.len(), 7);
    }
    let entries = fs::readdir_with_file_types(&t).unwrap();
    let sub = entries.iter().find(|e| e.name == "sub").unwrap();
    assert!(sub.is_directory() && !sub.is_file());
    assert_eq!(sub.parent_path, t);
    assert!(entries.iter().find(|e| e.name == "a").unwrap().is_file());
}

#[cfg(unix)]
#[test]
fn symlinks_lstat_realpath_and_exists() {
    let (_d, t) = tmp();
    fs::mkdir(&join(&t, "real/inner"), true, None).unwrap();
    fs::write_file(&join(&t, "real/inner/f"), "x", None).unwrap();
    fs::symlink("real", &join(&t, "rel-link")).unwrap();
    fs::symlink("rel-link/inner", &join(&t, "chain")).unwrap();
    fs::symlink("missing", &join(&t, "dangling")).unwrap();

    assert_eq!(fs::readlink(&join(&t, "rel-link")).unwrap(), "real");
    assert!(fs::lstat(&join(&t, "rel-link")).unwrap().is_symbolic_link());
    assert!(fs::stat(&join(&t, "rel-link")).unwrap().is_directory());
    assert_eq!(fs::realpath(&join(&t, "chain/f")).unwrap(), join(&t, "real/inner/f"));
    assert_eq!(
        fs::realpath_native(&join(&t, "chain/f")).unwrap(),
        join(&t, "real/inner/f")
    );
    // `..` is applied lexically (path.resolve) before any link is followed, as in Node.
    let e = node_err(fs::realpath(&join(&t, "chain/../inner")).unwrap_err());
    assert_eq!(
        e.message,
        format!("ENOENT: no such file or directory, lstat '{}'", join(&t, "inner"))
    );

    assert!(fs::exists(&join(&t, "chain/f")));
    assert!(!fs::exists(&join(&t, "dangling")));
    assert!(!fs::exists(""));
    assert!(!fs::exists("a\0b"));
    assert!(fs::stat_opt(&join(&t, "dangling")).unwrap().is_none());
    assert!(fs::stat_opt(&join(&t, "real/inner/f/x")).unwrap().is_none());
    assert!(fs::lstat_opt(&join(&t, "dangling")).unwrap().is_some());
    assert!(fs::lstat_opt(&join(&t, "nope")).unwrap().is_none());
    assert_eq!(
        node_err(fs::lstat_opt(&join(&t, "real/inner/f/x")).unwrap_err()).code,
        "ENOTDIR"
    );

    // realpath resolves non-canonical temp dirs (macOS /var -> /private/var).
    let raw = std::env::temp_dir().to_string_lossy().into_owned();
    let canonical = std::fs::canonicalize(&raw).unwrap().to_string_lossy().into_owned();
    assert_eq!(fs::realpath(&raw).unwrap(), canonical.trim_end_matches('/'));
}

#[cfg(unix)]
#[test]
fn rm_variants() {
    let (_d, t) = tmp();
    fs::mkdir(&join(&t, "tree/a/b"), true, None).unwrap();
    fs::write_file(&join(&t, "tree/a/b/f"), "x", None).unwrap();
    fs::write_file(&join(&t, "tree/g"), "x", None).unwrap();
    fs::mkdir(&join(&t, "target"), false, None).unwrap();
    fs::write_file(&join(&t, "target/keep"), "x", None).unwrap();
    fs::symlink(&join(&t, "target"), &join(&t, "link")).unwrap();

    fs::rm(&join(&t, "link"), true, false).unwrap();
    assert!(fs::exists(&join(&t, "target/keep")), "only the link is removed");
    fs::rm(&join(&t, "tree"), true, false).unwrap();
    assert!(!fs::exists(&join(&t, "tree")));
    fs::rm(&join(&t, "target/keep"), false, false).unwrap();
    fs::rm(&join(&t, "target"), true, true).unwrap();
    assert_eq!(fs::readdir(&t).unwrap(), Vec::<String>::new());
}

#[test]
fn copy_rename_link_truncate() {
    let (_d, t) = tmp();
    let a = join(&t, "a");
    fs::write_file(&a, "content", None).unwrap();
    fs::copy_file(&a, &join(&t, "b")).unwrap();
    fs::copy_file_mode(&a, &join(&t, "c"), constants::COPYFILE_EXCL).unwrap();
    assert_eq!(fs::read_to_string(&join(&t, "c")).unwrap(), "content");
    fs::rename(&join(&t, "b"), &join(&t, "d")).unwrap();
    assert!(!fs::exists(&join(&t, "b")));
    fs::link(&a, &join(&t, "hard")).unwrap();
    #[cfg(unix)]
    assert_eq!(fs::stat(&a).unwrap().nlink, 2);
    fs::truncate(&a, 3).unwrap();
    assert_eq!(fs::read_to_string(&join(&t, "hard")).unwrap(), "con");
    fs::truncate(&a, 5).unwrap();
    assert_eq!(fs::read_file(&a).unwrap(), b"con\0\0");
    fs::unlink(&join(&t, "hard")).unwrap();
}

#[test]
fn mkdtemp_names_and_errors() {
    let (_d, t) = tmp();
    let prefix = join(&t, "pre-");
    let made = fs::mkdtemp(&prefix).unwrap();
    let suffix = made.strip_prefix(&prefix).unwrap();
    assert_eq!(suffix.len(), 6);
    assert!(suffix.chars().all(|c| c.is_ascii_alphanumeric()), "{suffix}");
    assert!(fs::stat(&made).unwrap().is_directory());
    #[cfg(unix)]
    assert_eq!(fs::stat(&made).unwrap().mode & 0o777, 0o700);
    assert_ne!(fs::mkdtemp(&prefix).unwrap(), made);
}

#[cfg(unix)]
#[test]
fn access_checks_permissions() {
    let (_d, t) = tmp();
    let p = join(&t, "ro");
    fs::write_file(&p, "x", Some(0o444)).unwrap();
    fs::access(&p, constants::R_OK).unwrap();
    fs::access(&p, constants::F_OK).unwrap();
    if !nix::unistd::geteuid().is_root() {
        let e = node_err(fs::access(&p, constants::W_OK).unwrap_err());
        assert_eq!(e.message, format!("EACCES: permission denied, access '{p}'"));
        assert_eq!(e.errno, -libc::EACCES);
    }
}

#[test]
fn open_and_file_operations() {
    let (_d, t) = tmp();
    let p = join(&t, "f");
    let mut f = fs::open(&p, "w+", None).unwrap();
    assert_eq!(f.write(b"hello world", None).unwrap(), 11);
    let mut buf = [0u8; 5];
    assert_eq!(f.read(&mut buf, Some(6)).unwrap(), 5);
    assert_eq!(&buf, b"world");
    assert_eq!(f.write(b"J", Some(0)).unwrap(), 1);
    assert_eq!(f.stat().unwrap().size, 11);
    f.truncate(5).unwrap();
    f.sync().unwrap();
    f.close().unwrap();
    assert_eq!(fs::read_to_string(&p).unwrap(), "Jello");

    let mut a = fs::open(&p, "a", None).unwrap();
    a.write_all(b"!").unwrap();
    a.close().unwrap();
    assert_eq!(fs::read_to_string(&p).unwrap(), "Jello!");

    let mut r = fs::open(&p, "r", None).unwrap();
    assert_eq!(r.read_to_end().unwrap(), b"Jello!");
    let mut one = [0u8; 1];
    assert_eq!(r.read(&mut one, None).unwrap(), 0, "EOF");
    assert_eq!(r.path(), p);
}

#[test]
fn relative_paths_follow_the_cwd_guard() {
    let (_d, t) = tmp();
    let _cwd = CwdGuard::set(t.clone());
    fs::mkdir("rel/sub", true, None).unwrap();
    fs::write_file("rel/sub/x.txt", "x", None).unwrap();
    assert!(Path::new(&join(&t, "rel/sub/x.txt")).exists());
    assert_eq!(fs::readdir("rel").unwrap(), ["sub"]);
    assert!(fs::exists("rel/sub/x.txt"));
    assert_eq!(fs::realpath("rel/sub/x.txt").unwrap(), join(&t, "rel/sub/x.txt"));
    let e = node_err(fs::read_file("rel/missing").unwrap_err());
    assert_eq!(e.path.as_deref(), Some("rel/missing"));
    assert!(e.message.ends_with("open 'rel/missing'"), "{}", e.message);
}

#[tokio::test]
async fn promises_mirror_the_sync_api() {
    let (_d, t) = tmp();
    let _cwd = CwdGuard::set(t.clone());
    promises::mkdir("p/q", true, None).await.unwrap();
    promises::write_file("p/q/f.txt", "abc", None).await.unwrap();
    promises::append_file("p/q/f.txt", "def").await.unwrap();
    assert_eq!(
        promises::read_to_string(&join(&t, "p/q/f.txt")).await.unwrap(),
        "abcdef"
    );
    assert_eq!(promises::read_file("p/q/f.txt").await.unwrap(), b"abcdef");
    assert!(promises::exists("p/q/f.txt").await);
    assert!(!promises::exists("p/q/none").await);
    assert_eq!(promises::readdir("p").await.unwrap(), ["q"]);
    let entries = promises::readdir_with_file_types("p/q").await.unwrap();
    assert_eq!(entries.len(), 1);
    assert!(entries[0].is_file());
    assert_eq!(promises::stat("p/q/f.txt").await.unwrap().size, 6);
    promises::copy_file("p/q/f.txt", "p/copy.txt").await.unwrap();
    promises::rename("p/copy.txt", "p/moved.txt").await.unwrap();
    promises::truncate("p/moved.txt", 2).await.unwrap();
    assert_eq!(promises::read_to_string("p/moved.txt").await.unwrap(), "ab");
    promises::unlink("p/moved.txt").await.unwrap();
    assert_eq!(promises::realpath("p/q").await.unwrap(), join(&t, "p/q"));

    let made = promises::mkdtemp(&join(&t, "tmp-")).await.unwrap();
    assert_eq!(made.len(), join(&t, "tmp-").len() + 6);
    let e = node_err(promises::mkdtemp(&join(&t, "missing/pre-")).await.unwrap_err());
    let attempted = e.path.clone().unwrap();
    assert!(attempted.starts_with(&join(&t, "missing/pre-")) && attempted.len() == join(&t, "missing/pre-").len() + 6);
    assert_eq!(
        e.message,
        format!("ENOENT: no such file or directory, mkdtemp '{attempted}'")
    );

    promises::rm("p", true, false).await.unwrap();
    assert!(!fs::exists("p"));
    promises::rmdir(&made).await.unwrap();
}

#[tokio::test]
async fn file_handle_operations() {
    let (_d, t) = tmp();
    let p = join(&t, "h");
    let fh = promises::open(&p, "w+", None).await.unwrap();
    assert_eq!(fh.write("hello", None).await.unwrap(), 5);
    let mut buf = [0u8; 3];
    assert_eq!(fh.read(&mut buf, Some(1)).await.unwrap(), 3);
    assert_eq!(&buf, b"ell");
    assert_eq!(fh.stat().await.unwrap().size, 5);
    fh.truncate(4).await.unwrap();
    fh.sync().await.unwrap();
    fh.close().await.unwrap();
    // node: `await fh.stat()` after close rejects with `Error: file closed` (EBADF, fstat).
    for (err, syscall) in [
        (fh.stat().await.unwrap_err(), "fstat"),
        (fh.read(&mut buf, None).await.unwrap_err(), "read"),
        (fh.write("x", None).await.unwrap_err(), "write"),
        (fh.truncate(1).await.unwrap_err(), "ftruncate"),
        (fh.sync().await.unwrap_err(), "fsync"),
        (fh.read_file().await.unwrap_err(), "readFile"),
    ] {
        let e = node_err(err);
        assert_eq!(
            (e.code.as_str(), e.message.as_str(), e.syscall.as_str()),
            ("EBADF", "file closed", syscall)
        );
    }
    fh.close().await.unwrap();
    let fh = promises::open(&p, "r", None).await.unwrap();
    assert_eq!(fh.read_file().await.unwrap(), b"hell");
    fh.close().await.unwrap();
}

async fn advance(ms: u64) {
    tokio::time::advance(std::time::Duration::from_millis(ms)).await;
    for _ in 0..4 {
        tokio::task::yield_now().await;
    }
}

type WatchLog = std::sync::Arc<std::sync::Mutex<Vec<(u64, u64, bool, bool)>>>;

fn watch_logger(log: &WatchLog) -> impl FnMut(&fs::Stats, &fs::Stats) + Send + 'static {
    let log = log.clone();
    move |current, previous| {
        log.lock()
            .unwrap()
            .push((current.size, previous.size, current.is_file(), previous.is_file()))
    }
}

#[tokio::test(start_paused = true)]
async fn watch_file_reports_changes_like_node() {
    let (_d, t) = tmp();
    let p = join(&t, "w.txt");
    let log: WatchLog = Default::default();
    let w = fs::watch_file(&p, 100, watch_logger(&log)).unwrap();
    assert!(w.is_active());

    // A missing file is reported once, with zeroed stats.
    advance(0).await;
    assert_eq!(*log.lock().unwrap(), [(0, 0, false, false)]);
    advance(100).await;
    assert_eq!(log.lock().unwrap().len(), 1);

    std::fs::write(&p, "abc").unwrap();
    advance(100).await;
    assert_eq!(log.lock().unwrap()[1], (3, 0, true, false));
    advance(100).await;
    assert_eq!(log.lock().unwrap().len(), 2, "unchanged stats are not reported");

    std::fs::write(&p, "abcdef").unwrap();
    advance(100).await;
    assert_eq!(log.lock().unwrap()[2], (6, 3, true, true));

    std::fs::remove_file(&p).unwrap();
    advance(100).await;
    assert_eq!(log.lock().unwrap()[3], (0, 6, false, true));

    w.stop();
    assert!(!w.is_active());
    std::fs::write(&p, "again").unwrap();
    advance(500).await;
    assert_eq!(log.lock().unwrap().len(), 4);
}

#[tokio::test(start_paused = true)]
async fn watch_file_on_an_existing_file_waits_for_a_change() {
    let (_d, t) = tmp();
    let p = join(&t, "e.txt");
    std::fs::write(&p, "1").unwrap();
    let log: WatchLog = Default::default();
    let _cwd = CwdGuard::set(t.clone());
    let w = fs::watch_file("e.txt", 50, watch_logger(&log)).unwrap();
    advance(200).await;
    assert!(log.lock().unwrap().is_empty());
    std::fs::write(&p, "22").unwrap();
    advance(50).await;
    assert_eq!(*log.lock().unwrap(), [(2, 1, true, true)]);
    w.stop();
}

// ---------------------------------------------------------------------------------------
// Generated by node v24.21.0 on macOS (see the module comment).

const NODE_FS_ERRORS: &[(&str, Option<E>)] = &[
    (
        "readFile_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, open '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("open"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "readFile_dir",
        Some(E {
            name: "Error",
            message: "EISDIR: illegal operation on a directory, read",
            code: Some("EISDIR"),
            errno: Some(-21),
            syscall: Some("read"),
            path: None,
            dest: None,
        }),
    ),
    (
        "readFile_notdir",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, open '$T/file/x'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("open"),
            path: Some("$T/file/x"),
            dest: None,
        }),
    ),
    (
        "writeFile_dir",
        Some(E {
            name: "Error",
            message: "EISDIR: illegal operation on a directory, open '$T/dir'",
            code: Some("EISDIR"),
            errno: Some(-21),
            syscall: Some("open"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "writeFile_noparent",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, open '$T/missing/x'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("open"),
            path: Some("$T/missing/x"),
            dest: None,
        }),
    ),
    (
        "writeFile_wx",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, open '$T/file'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("open"),
            path: Some("$T/file"),
            dest: None,
        }),
    ),
    (
        "writeFile_badflag",
        Some(E {
            name: "TypeError",
            message: "The argument 'flags' is invalid. Received 'zz'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "appendFile_dir",
        Some(E {
            name: "Error",
            message: "EISDIR: illegal operation on a directory, open '$T/dir'",
            code: Some("EISDIR"),
            errno: Some(-21),
            syscall: Some("open"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "mkdir_exists",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, mkdir '$T/dir'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("mkdir"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "mkdir_noparent",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, mkdir '$T/missing/x'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("mkdir"),
            path: Some("$T/missing/x"),
            dest: None,
        }),
    ),
    (
        "mkdir_under_file",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, mkdir '$T/file/a'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("mkdir"),
            path: Some("$T/file/a"),
            dest: None,
        }),
    ),
    (
        "mkdir_rec_under_file",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, mkdir '$T/file/a/b'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("mkdir"),
            path: Some("$T/file/a/b"),
            dest: None,
        }),
    ),
    (
        "mkdir_rec_on_file",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, mkdir '$T/file'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("mkdir"),
            path: Some("$T/file"),
            dest: None,
        }),
    ),
    ("mkdir_rec_existing", None),
    (
        "readdir_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, scandir '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("scandir"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "readdir_file",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, scandir '$T/file'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("scandir"),
            path: Some("$T/file"),
            dest: None,
        }),
    ),
    (
        "stat_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, stat '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("stat"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "stat_dangling",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, stat '$T/dangling'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("stat"),
            path: Some("$T/dangling"),
            dest: None,
        }),
    ),
    (
        "stat_notdir",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, stat '$T/file/x'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("stat"),
            path: Some("$T/file/x"),
            dest: None,
        }),
    ),
    (
        "lstat_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, lstat '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("lstat"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "rm_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, lstat '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("lstat"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    ("rm_missing_force", None),
    (
        "rm_dir",
        Some(E {
            name: "SystemError",
            message: "Path is a directory: rm returned EISDIR (is a directory) $T/dir",
            code: Some("ERR_FS_EISDIR"),
            errno: Some(21),
            syscall: Some("rm"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "rm_dir_force",
        Some(E {
            name: "SystemError",
            message: "Path is a directory: rm returned EISDIR (is a directory) $T/dir",
            code: Some("ERR_FS_EISDIR"),
            errno: Some(21),
            syscall: Some("rm"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "rm_notdir",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, lstat '$T/file/x'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("lstat"),
            path: Some("$T/file/x"),
            dest: None,
        }),
    ),
    (
        "rm_notdir_force",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, lstat '$T/file/x'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("lstat"),
            path: Some("$T/file/x"),
            dest: None,
        }),
    ),
    (
        "rm_notdir_recursive",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, lstat '$T/file/x'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("lstat"),
            path: Some("$T/file/x"),
            dest: None,
        }),
    ),
    ("rm_notdir_recursive_force", None),
    (
        "rm_locked_recursive",
        Some(E {
            name: "Error",
            message: "ENOTEMPTY, Directory not empty: $T/locked '$T/locked'",
            code: Some("ENOTEMPTY"),
            errno: Some(66),
            syscall: Some("rm"),
            path: Some("$T/locked"),
            dest: None,
        }),
    ),
    (
        "unlink_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, unlink '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("unlink"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "unlink_dir",
        Some(E {
            name: "Error",
            message: "EPERM: operation not permitted, unlink '$T/dir'",
            code: Some("EPERM"),
            errno: Some(-1),
            syscall: Some("unlink"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "rmdir_nonempty",
        Some(E {
            name: "Error",
            message: "ENOTEMPTY: directory not empty, rmdir '$T/dir'",
            code: Some("ENOTEMPTY"),
            errno: Some(-66),
            syscall: Some("rmdir"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "rmdir_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, rmdir '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("rmdir"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "rmdir_file",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, rmdir '$T/file'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("rmdir"),
            path: Some("$T/file"),
            dest: None,
        }),
    ),
    (
        "rename_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, rename '$T/missing' -> '$T/other'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("rename"),
            path: Some("$T/missing"),
            dest: Some("$T/other"),
        }),
    ),
    (
        "rename_dir_to_file",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, rename '$T/dir' -> '$T/file'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("rename"),
            path: Some("$T/dir"),
            dest: Some("$T/file"),
        }),
    ),
    (
        "rename_file_to_nonempty_dir",
        Some(E {
            name: "Error",
            message: "EISDIR: illegal operation on a directory, rename '$T/file' -> '$T/dir'",
            code: Some("EISDIR"),
            errno: Some(-21),
            syscall: Some("rename"),
            path: Some("$T/file"),
            dest: Some("$T/dir"),
        }),
    ),
    (
        "copyFile_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, copyfile '$T/missing' -> '$T/other'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("copyfile"),
            path: Some("$T/missing"),
            dest: Some("$T/other"),
        }),
    ),
    (
        "copyFile_excl",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, copyfile '$T/file' -> '$T/file2'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("copyfile"),
            path: Some("$T/file"),
            dest: Some("$T/file2"),
        }),
    ),
    (
        "copyFile_dir_src",
        Some(E {
            name: "Error",
            message: "ENOTSUP: operation not supported on socket, copyfile '$T/dir' -> '$T/other'",
            code: Some("ENOTSUP"),
            errno: Some(-45),
            syscall: Some("copyfile"),
            path: Some("$T/dir"),
            dest: Some("$T/other"),
        }),
    ),
    (
        "copyFile_dest_dir",
        Some(E {
            name: "Error",
            message: "EISDIR: illegal operation on a directory, copyfile '$T/file' -> '$T/dir'",
            code: Some("EISDIR"),
            errno: Some(-21),
            syscall: Some("copyfile"),
            path: Some("$T/file"),
            dest: Some("$T/dir"),
        }),
    ),
    (
        "realpath_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, lstat '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("lstat"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "realpath_dangling",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, stat '$T/dangling'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("stat"),
            path: Some("$T/dangling"),
            dest: None,
        }),
    ),
    (
        "realpath_link_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, lstat '$T/dir/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("lstat"),
            path: Some("$T/dir/missing"),
            dest: None,
        }),
    ),
    (
        "realpath_notdir",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, lstat '$T/file/x'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("lstat"),
            path: Some("$T/file/x"),
            dest: None,
        }),
    ),
    (
        "realpathNative_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, realpath '$T/missing/x'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("realpath"),
            path: Some("$T/missing/x"),
            dest: None,
        }),
    ),
    (
        "chmod_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, chmod '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("chmod"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "mkdtemp_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, mkdtemp '$T/missing/pre-XXXXXX'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("mkdtemp"),
            path: Some("$T/missing/pre-XXXXXX"),
            dest: None,
        }),
    ),
    (
        "symlink_exists",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, symlink 'target' -> '$T/file'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("symlink"),
            path: Some("target"),
            dest: Some("$T/file"),
        }),
    ),
    (
        "readlink_file",
        Some(E {
            name: "Error",
            message: "EINVAL: invalid argument, readlink '$T/file'",
            code: Some("EINVAL"),
            errno: Some(-22),
            syscall: Some("readlink"),
            path: Some("$T/file"),
            dest: None,
        }),
    ),
    (
        "readlink_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, readlink '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("readlink"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "link_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, link '$T/missing' -> '$T/other'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("link"),
            path: Some("$T/missing"),
            dest: Some("$T/other"),
        }),
    ),
    (
        "link_exists",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, link '$T/file' -> '$T/file2'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("link"),
            path: Some("$T/file"),
            dest: Some("$T/file2"),
        }),
    ),
    (
        "utimes_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, utime '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("utime"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "truncate_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, open '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("open"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "truncate_dir",
        Some(E {
            name: "Error",
            message: "EISDIR: illegal operation on a directory, open '$T/dir'",
            code: Some("EISDIR"),
            errno: Some(-21),
            syscall: Some("open"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "access_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, access '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("access"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "open_wx",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, open '$T/file'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("open"),
            path: Some("$T/file"),
            dest: None,
        }),
    ),
    (
        "open_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, open '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("open"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "open_badflag",
        Some(E {
            name: "TypeError",
            message: "The argument 'flags' is invalid. Received 'rw'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_readFile",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/x\\x00y'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_rename_old",
        Some(E {
            name: "TypeError",
            message: "The argument 'oldPath' must be a string, Uint8Array, or URL without null bytes. Received '/a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_rename_new",
        Some(E {
            name: "TypeError",
            message: "The argument 'newPath' must be a string, Uint8Array, or URL without null bytes. Received '/b\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_mkdtemp",
        Some(E {
            name: "TypeError",
            message: "The argument 'prefix' must be a string, Uint8Array, or URL without null bytes. Received 'p\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_symlink_target",
        Some(E {
            name: "TypeError",
            message: "The argument 'target' must be a string, Uint8Array, or URL without null bytes. Received 't\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_symlink_path",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/x\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_copy_src",
        Some(E {
            name: "TypeError",
            message: "The argument 'src' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_copy_dest",
        Some(E {
            name: "TypeError",
            message: "The argument 'dest' must be a string, Uint8Array, or URL without null bytes. Received 'b\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_link_existing",
        Some(E {
            name: "TypeError",
            message: "The argument 'existingPath' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_link_new",
        Some(E {
            name: "TypeError",
            message: "The argument 'newPath' must be a string, Uint8Array, or URL without null bytes. Received 'b\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_quote_single",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received \"a'b\\x00\"",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_quote_double",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received `a'b\"c\\x00`",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_quote_backtick",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\'b\"c`\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_escapes",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '\\x00\\n\\t\\b\\f\\r\\x0B\\x1B\\x7F\\x9F é\\\\😀'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_long",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_long_lines",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'line of text\\n' +\u{a}  'line of text\\n' +\u{a}  'line of text\\n' +\u{a}  'line of text\\n' +\u{a}  'line of text\\n' +\u{a}  'line of text\\n' +\u{a}  'l...",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_short_lines",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\nb\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_stat",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_lstat",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_writeFile",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_appendFile",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_mkdir",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_readdir",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_rm",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_unlink",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_rmdir",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_chmod",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_utimes",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_access",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_realpath",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_open",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_truncate",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "nul_readlink",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'a\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "p_readFile_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, open '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("open"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "p_readFile_dir",
        Some(E {
            name: "Error",
            message: "EISDIR: illegal operation on a directory, read",
            code: Some("EISDIR"),
            errno: Some(-21),
            syscall: Some("read"),
            path: None,
            dest: None,
        }),
    ),
    (
        "p_writeFile_dir",
        Some(E {
            name: "Error",
            message: "EISDIR: illegal operation on a directory, open '$T/dir'",
            code: Some("EISDIR"),
            errno: Some(-21),
            syscall: Some("open"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "p_mkdir_exists",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, mkdir '$T/dir'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("mkdir"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "p_mkdir_rec_under_file",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, mkdir '$T/file/a/b'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("mkdir"),
            path: Some("$T/file/a/b"),
            dest: None,
        }),
    ),
    (
        "p_readdir_file",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, scandir '$T/file'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("scandir"),
            path: Some("$T/file"),
            dest: None,
        }),
    ),
    (
        "p_stat_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, stat '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("stat"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "p_lstat_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, lstat '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("lstat"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "p_rm_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, lstat '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("lstat"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    ("p_rm_missing_force", None),
    (
        "p_rm_dir",
        Some(E {
            name: "SystemError",
            message: "Path is a directory: rm returned EISDIR (is a directory) $T/dir",
            code: Some("ERR_FS_EISDIR"),
            errno: Some(21),
            syscall: Some("rm"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "p_rm_notdir",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, lstat '$T/file/x'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("lstat"),
            path: Some("$T/file/x"),
            dest: None,
        }),
    ),
    (
        "p_rm_notdir_recursive_force",
        Some(E {
            name: "Error",
            message: "ENOTDIR: not a directory, lstat '$T/file/x'",
            code: Some("ENOTDIR"),
            errno: Some(-20),
            syscall: Some("lstat"),
            path: Some("$T/file/x"),
            dest: None,
        }),
    ),
    (
        "p_rm_locked_recursive",
        Some(E {
            name: "Error",
            message: "EACCES: permission denied, unlink '$T/locked/f'",
            code: Some("EACCES"),
            errno: Some(-13),
            syscall: Some("unlink"),
            path: Some("$T/locked/f"),
            dest: None,
        }),
    ),
    (
        "p_unlink_dir",
        Some(E {
            name: "Error",
            message: "EPERM: operation not permitted, unlink '$T/dir'",
            code: Some("EPERM"),
            errno: Some(-1),
            syscall: Some("unlink"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "p_rmdir_nonempty",
        Some(E {
            name: "Error",
            message: "ENOTEMPTY: directory not empty, rmdir '$T/dir'",
            code: Some("ENOTEMPTY"),
            errno: Some(-66),
            syscall: Some("rmdir"),
            path: Some("$T/dir"),
            dest: None,
        }),
    ),
    (
        "p_rename_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, rename '$T/missing' -> '$T/other'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("rename"),
            path: Some("$T/missing"),
            dest: Some("$T/other"),
        }),
    ),
    (
        "p_copyFile_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, copyfile '$T/missing' -> '$T/other'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("copyfile"),
            path: Some("$T/missing"),
            dest: Some("$T/other"),
        }),
    ),
    (
        "p_copyFile_excl",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, copyfile '$T/file' -> '$T/file2'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("copyfile"),
            path: Some("$T/file"),
            dest: Some("$T/file2"),
        }),
    ),
    (
        "p_realpath_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, realpath '$T/missing/x'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("realpath"),
            path: Some("$T/missing/x"),
            dest: None,
        }),
    ),
    (
        "p_realpath_dangling",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, realpath '$T/dangling'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("realpath"),
            path: Some("$T/dangling"),
            dest: None,
        }),
    ),
    (
        "p_chmod_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, chmod '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("chmod"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "p_symlink_exists",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, symlink 'target' -> '$T/file'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("symlink"),
            path: Some("target"),
            dest: Some("$T/file"),
        }),
    ),
    (
        "p_readlink_file",
        Some(E {
            name: "Error",
            message: "EINVAL: invalid argument, readlink '$T/file'",
            code: Some("EINVAL"),
            errno: Some(-22),
            syscall: Some("readlink"),
            path: Some("$T/file"),
            dest: None,
        }),
    ),
    (
        "p_link_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, link '$T/missing' -> '$T/other'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("link"),
            path: Some("$T/missing"),
            dest: Some("$T/other"),
        }),
    ),
    (
        "p_utimes_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, utime '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("utime"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "p_truncate_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, open '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("open"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "p_access_missing",
        Some(E {
            name: "Error",
            message: "ENOENT: no such file or directory, access '$T/missing'",
            code: Some("ENOENT"),
            errno: Some(-2),
            syscall: Some("access"),
            path: Some("$T/missing"),
            dest: None,
        }),
    ),
    (
        "p_open_wx",
        Some(E {
            name: "Error",
            message: "EEXIST: file already exists, open '$T/file'",
            code: Some("EEXIST"),
            errno: Some(-17),
            syscall: Some("open"),
            path: Some("$T/file"),
            dest: None,
        }),
    ),
    (
        "p_open_badflag",
        Some(E {
            name: "TypeError",
            message: "The argument 'flags' is invalid. Received 'rw'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "p_nul_readFile",
        Some(E {
            name: "TypeError",
            message: "The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/x\\x00y'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "p_nul_rename_new",
        Some(E {
            name: "TypeError",
            message: "The argument 'newPath' must be a string, Uint8Array, or URL without null bytes. Received '/b\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
    (
        "p_nul_mkdtemp",
        Some(E {
            name: "TypeError",
            message: "The argument 'prefix' must be a string, Uint8Array, or URL without null bytes. Received 'p\\x00'",
            code: Some("ERR_INVALID_ARG_VALUE"),
            errno: None,
            syscall: None,
            path: None,
            dest: None,
        }),
    ),
];
