//! pi_js::path parity with Node 24 `path.posix` / `path.win32`.
//!
//! The vector tables at the bottom were generated with node v24.21.0 (`path.posix.*` and
//! `path.win32.*`), with `process.cwd()` stubbed to `/home/user/proj` (`*_PCWD`) or
//! `C:\Users\me\proj` (`*_WCWD`, plus `process.env["=D:"] = "D:\dcwd"` and
//! `process.env["=E:"] = "C:\notE"`).

use pi_js::env::testing::{CwdGuard, EnvGuard};
use pi_js::path::{self, ParsedPath, posix, win32};

const POSIX_CWD: &str = "/home/user/proj";
const WIN_CWD: &str = "C:\\Users\\me\\proj";

fn check<T: std::fmt::Debug + PartialEq>(
    what: &str,
    failures: &mut Vec<String>,
    input: impl std::fmt::Debug,
    got: T,
    want: T,
) {
    if got != want {
        failures.push(format!("{what}({input:?}): got {got:?}, want {want:?}"));
    }
}

fn finish(failures: Vec<String>) {
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

fn parsed(p: [&str; 5]) -> ParsedPath {
    ParsedPath {
        root: p[0].to_string(),
        dir: p[1].to_string(),
        base: p[2].to_string(),
        ext: p[3].to_string(),
        name: p[4].to_string(),
    }
}

struct Module {
    normalize: fn(&str) -> String,
    is_absolute: fn(&str) -> bool,
    dirname: fn(&str) -> String,
    extname: fn(&str) -> String,
    basename: fn(&str, Option<&str>) -> String,
    parse: fn(&str) -> ParsedPath,
    format: fn(&ParsedPath) -> String,
    join: fn(&[&str]) -> String,
    resolve: fn(&[&str]) -> String,
    relative: fn(&str, &str) -> String,
    to_namespaced_path: fn(&str) -> String,
}

const POSIX: Module = Module {
    normalize: posix::normalize,
    is_absolute: posix::is_absolute,
    dirname: posix::dirname,
    extname: posix::extname,
    basename: posix::basename,
    parse: posix::parse,
    format: posix::format,
    join: posix::join,
    resolve: posix::resolve,
    relative: posix::relative,
    to_namespaced_path: posix::to_namespaced_path,
};

const WIN32: Module = Module {
    normalize: win32::normalize,
    is_absolute: win32::is_absolute,
    dirname: win32::dirname,
    extname: win32::extname,
    basename: win32::basename,
    parse: win32::parse,
    format: win32::format,
    join: win32::join,
    resolve: win32::resolve,
    relative: win32::relative,
    to_namespaced_path: win32::to_namespaced_path,
};

#[allow(clippy::type_complexity)]
struct Tables {
    normalize: &'static [(&'static str, &'static str)],
    is_absolute: &'static [(&'static str, bool)],
    dirname: &'static [(&'static str, &'static str)],
    extname: &'static [(&'static str, &'static str)],
    basename: &'static [(&'static str, Option<&'static str>, &'static str)],
    parse: &'static [(&'static str, [&'static str; 5])],
    format: &'static [([&'static str; 5], &'static str)],
    join: &'static [(&'static [&'static str], &'static str)],
}

fn check_pure(m: &Module, t: &Tables, failures: &mut Vec<String>) {
    for (p, want) in t.normalize {
        check("normalize", failures, p, (m.normalize)(p), want.to_string());
    }
    for (p, want) in t.is_absolute {
        check("isAbsolute", failures, p, (m.is_absolute)(p), *want);
    }
    for (p, want) in t.dirname {
        check("dirname", failures, p, (m.dirname)(p), want.to_string());
    }
    for (p, want) in t.extname {
        check("extname", failures, p, (m.extname)(p), want.to_string());
    }
    for (p, ext, want) in t.basename {
        check("basename", failures, (p, ext), (m.basename)(p, *ext), want.to_string());
    }
    for (p, want) in t.parse {
        check("parse", failures, p, (m.parse)(p), parsed(*want));
    }
    for (obj, want) in t.format {
        check("format", failures, obj, (m.format)(&parsed(*obj)), want.to_string());
    }
    for (args, want) in t.join {
        check("join", failures, args, (m.join)(args), want.to_string());
    }
}

#[allow(clippy::type_complexity)]
fn check_cwd(
    m: &Module,
    resolve: &[(&[&str], &str)],
    relative: &[(&str, &str, &str)],
    namespaced: &[(&str, &str)],
    failures: &mut Vec<String>,
) {
    for (args, want) in resolve {
        check("resolve", failures, args, (m.resolve)(args), want.to_string());
    }
    for (a, b, want) in relative {
        check("relative", failures, (a, b), (m.relative)(a, b), want.to_string());
    }
    for (p, want) in namespaced {
        check(
            "toNamespacedPath",
            failures,
            p,
            (m.to_namespaced_path)(p),
            want.to_string(),
        );
    }
}

#[test]
fn posix_pure_functions_match_node() {
    let mut failures = Vec::new();
    let t = Tables {
        normalize: POSIX_NORMALIZE,
        is_absolute: POSIX_IS_ABSOLUTE,
        dirname: POSIX_DIRNAME,
        extname: POSIX_EXTNAME,
        basename: POSIX_BASENAME,
        parse: POSIX_PARSE,
        format: POSIX_FORMAT,
        join: POSIX_JOIN,
    };
    check_pure(&POSIX, &t, &mut failures);
    finish(failures);
}

#[test]
fn win32_pure_functions_match_node() {
    let mut failures = Vec::new();
    let t = Tables {
        normalize: WIN32_NORMALIZE,
        is_absolute: WIN32_IS_ABSOLUTE,
        dirname: WIN32_DIRNAME,
        extname: WIN32_EXTNAME,
        basename: WIN32_BASENAME,
        parse: WIN32_PARSE,
        format: WIN32_FORMAT,
        join: WIN32_JOIN,
    };
    check_pure(&WIN32, &t, &mut failures);
    finish(failures);
}

#[test]
fn posix_cwd_functions_match_node() {
    let _cwd = CwdGuard::set(POSIX_CWD);
    let mut failures = Vec::new();
    check_cwd(
        &POSIX,
        POSIX_RESOLVE_PCWD,
        POSIX_RELATIVE_PCWD,
        POSIX_NAMESPACED_PCWD,
        &mut failures,
    );
    finish(failures);
}

#[test]
fn win32_cwd_functions_match_node() {
    let _cwd = CwdGuard::set(WIN_CWD);
    let _env = EnvGuard::set_many(&[("=D:", Some("D:\\dcwd")), ("=E:", Some("C:\\notE"))]);
    let mut failures = Vec::new();
    check_cwd(
        &WIN32,
        WIN32_RESOLVE_WCWD,
        WIN32_RELATIVE_WCWD,
        WIN32_NAMESPACED_WCWD,
        &mut failures,
    );
    finish(failures);
}

/// A posix-style cwd seen by `path.win32` and a Windows cwd seen by `path.posix` (what
/// Node does on a non-Windows host).
#[cfg(not(windows))]
#[test]
fn cross_platform_cwd_functions_match_node() {
    let mut failures = Vec::new();
    {
        let _cwd = CwdGuard::set(POSIX_CWD);
        let _env = EnvGuard::set_many(&[("=D:", None), ("=E:", None)]);
        check_cwd(
            &WIN32,
            WIN32_RESOLVE_PCWD,
            WIN32_RELATIVE_PCWD,
            WIN32_NAMESPACED_PCWD,
            &mut failures,
        );
    }
    {
        let _cwd = CwdGuard::set(WIN_CWD);
        check_cwd(
            &POSIX,
            POSIX_RESOLVE_WCWD,
            POSIX_RELATIVE_WCWD,
            POSIX_NAMESPACED_WCWD,
            &mut failures,
        );
    }
    finish(failures);
}

#[test]
fn constants_and_platform_default() {
    assert_eq!(posix::sep(), "/");
    assert_eq!(posix::delimiter(), ":");
    assert_eq!(win32::sep(), "\\");
    assert_eq!(win32::delimiter(), ";");
    if cfg!(windows) {
        assert_eq!(path::sep(), "\\");
        assert_eq!(path::delimiter(), ";");
        assert_eq!(path::join(&["a", "b"]), "a\\b");
    } else {
        assert_eq!(path::sep(), "/");
        assert_eq!(path::delimiter(), ":");
        assert_eq!(path::join(&["a", "b"]), "a/b");
        assert_eq!(path::basename("/x/y.ts", Some(".ts")), "y");
        assert_eq!(path::extname("/x/y.ts"), ".ts");
        assert!(path::is_absolute("/x"));
        assert_eq!(path::dirname("/x/y"), "/x");
        assert_eq!(path::normalize("/x/../y"), "/y");
        assert_eq!(path::relative("/a/b", "/a/c"), "../c");
        let _cwd = CwdGuard::set("/srv/app");
        assert_eq!(path::resolve(&["x"]), "/srv/app/x");
        assert_eq!(path::to_namespaced_path("x"), "x");
        assert_eq!(path::format(&path::parse("/a/b.c")), "/a/b.c");
    }
}

// ---------------------------------------------------------------------------------------
// Generated by node v24.21.0 (see the module comment).

const POSIX_NORMALIZE: &[(&str, &str)] = &[
    ("", "."),
    (".", "."),
    ("..", ".."),
    ("/", "/"),
    ("//", "/"),
    ("///", "/"),
    ("a", "a"),
    ("a/", "a/"),
    ("a//", "a/"),
    ("/a", "/a"),
    ("/a/", "/a/"),
    ("a/b", "a/b"),
    ("/a/b/c", "/a/b/c"),
    ("/a/b/c/", "/a/b/c/"),
    ("a/./b", "a/b"),
    ("a/../b", "b"),
    ("../a", "../a"),
    ("../../a/b", "../../a/b"),
    ("/../a", "/a"),
    ("/a/../../b", "/b"),
    ("./", "./"),
    ("./a", "a"),
    ("a/b/../../..", ".."),
    ("a/b/../../../c", "../c"),
    (".a", ".a"),
    ("a.", "a."),
    (".a.b", ".a.b"),
    ("a..b", "a..b"),
    ("file.txt", "file.txt"),
    ("/dir/file.tar.gz", "/dir/file.tar.gz"),
    ("dir/.hidden", "dir/.hidden"),
    ("/foo/bar/baz/asdf/quux.html", "/foo/bar/baz/asdf/quux.html"),
    ("...", "..."),
    ("..a", "..a"),
    ("a/...", "a/..."),
    ("/a/b/.", "/a/b"),
    ("/a/b/..", "/a"),
    ("a/b/./", "a/b/"),
    (".//a//b//", "a/b/"),
    ("//a", "/a"),
    ("//a/b", "/a/b"),
    ("C:", "C:"),
    ("C:\\", "C:\\"),
    ("C:/", "C:/"),
    ("C:\\a\\b", "C:\\a\\b"),
    ("C:a", "C:a"),
    ("C:a\\b", "C:a\\b"),
    ("c:/a/../b", "c:/b"),
    ("C:\\..\\..", "C:\\..\\.."),
    ("C:..", "C:.."),
    ("\\\\server\\share", "\\\\server\\share"),
    ("\\\\server\\share\\", "\\\\server\\share\\"),
    ("\\\\server\\share\\a\\b", "\\\\server\\share\\a\\b"),
    ("//server/share/a", "/server/share/a"),
    ("\\\\server", "\\\\server"),
    ("\\\\server\\", "\\\\server\\"),
    ("\\\\?\\C:\\a", "\\\\?\\C:\\a"),
    ("\\\\?\\UNC\\srv\\shr\\x", "\\\\?\\UNC\\srv\\shr\\x"),
    ("\\\\.\\pipe\\x", "\\\\.\\pipe\\x"),
    ("\\a\\b", "\\a\\b"),
    ("a\\b", "a\\b"),
    ("a\\b\\..\\c", "a\\b\\..\\c"),
    ("\\", "\\"),
    ("\\\\", "\\\\"),
    ("\\\\\\", "\\\\\\"),
    ("\\\\\\a", "\\\\\\a"),
    ("a/b\\c", "a/b\\c"),
    ("file:stream", "file:stream"),
    ("COM1", "COM1"),
    ("C:\\x\\COM1", "C:\\x\\COM1"),
    ("C:\\x\\CON.txt", "C:\\x\\CON.txt"),
    ("con", "con"),
    ("aux:", "aux:"),
    ("x/nul", "x/nul"),
    ("LPT1:", "LPT1:"),
    ("COM¹", "COM¹"),
    ("unicode/é/日本.txt", "unicode/é/日本.txt"),
    ("😀/x.y", "😀/x.y"),
    ("a b/c d.e f", "a b/c d.e f"),
    ("/a/b.c.d", "/a/b.c.d"),
    ("a.b/", "a.b/"),
    ("a.b//", "a.b/"),
    (".", "."),
    ("/.", "/"),
    ("/..", "/"),
    ("/.a", "/.a"),
    ("/.a/", "/.a/"),
    ("C:\\.a", "C:\\.a"),
    ("C:\\a.", "C:\\a."),
    ("C:\\a.b\\", "C:\\a.b\\"),
    ("a\u{9}b/c\u{a}d", "a\u{9}b/c\u{a}d"),
    ("/home/user/proj/src/index.ts", "/home/user/proj/src/index.ts"),
    (
        "C:\\Users\\me\\proj\\src\\index.ts",
        "C:\\Users\\me\\proj\\src\\index.ts",
    ),
    ("D:", "D:"),
    ("D:x", "D:x"),
    ("d:\\", "d:\\"),
    ("C:\\\\a\\\\\\b", "C:\\\\a\\\\\\b"),
];

const POSIX_IS_ABSOLUTE: &[(&str, bool)] = &[
    ("", false),
    (".", false),
    ("..", false),
    ("/", true),
    ("//", true),
    ("///", true),
    ("a", false),
    ("a/", false),
    ("a//", false),
    ("/a", true),
    ("/a/", true),
    ("a/b", false),
    ("/a/b/c", true),
    ("/a/b/c/", true),
    ("a/./b", false),
    ("a/../b", false),
    ("../a", false),
    ("../../a/b", false),
    ("/../a", true),
    ("/a/../../b", true),
    ("./", false),
    ("./a", false),
    ("a/b/../../..", false),
    ("a/b/../../../c", false),
    (".a", false),
    ("a.", false),
    (".a.b", false),
    ("a..b", false),
    ("file.txt", false),
    ("/dir/file.tar.gz", true),
    ("dir/.hidden", false),
    ("/foo/bar/baz/asdf/quux.html", true),
    ("...", false),
    ("..a", false),
    ("a/...", false),
    ("/a/b/.", true),
    ("/a/b/..", true),
    ("a/b/./", false),
    (".//a//b//", false),
    ("//a", true),
    ("//a/b", true),
    ("C:", false),
    ("C:\\", false),
    ("C:/", false),
    ("C:\\a\\b", false),
    ("C:a", false),
    ("C:a\\b", false),
    ("c:/a/../b", false),
    ("C:\\..\\..", false),
    ("C:..", false),
    ("\\\\server\\share", false),
    ("\\\\server\\share\\", false),
    ("\\\\server\\share\\a\\b", false),
    ("//server/share/a", true),
    ("\\\\server", false),
    ("\\\\server\\", false),
    ("\\\\?\\C:\\a", false),
    ("\\\\?\\UNC\\srv\\shr\\x", false),
    ("\\\\.\\pipe\\x", false),
    ("\\a\\b", false),
    ("a\\b", false),
    ("a\\b\\..\\c", false),
    ("\\", false),
    ("\\\\", false),
    ("\\\\\\", false),
    ("\\\\\\a", false),
    ("a/b\\c", false),
    ("file:stream", false),
    ("COM1", false),
    ("C:\\x\\COM1", false),
    ("C:\\x\\CON.txt", false),
    ("con", false),
    ("aux:", false),
    ("x/nul", false),
    ("LPT1:", false),
    ("COM¹", false),
    ("unicode/é/日本.txt", false),
    ("😀/x.y", false),
    ("a b/c d.e f", false),
    ("/a/b.c.d", true),
    ("a.b/", false),
    ("a.b//", false),
    (".", false),
    ("/.", true),
    ("/..", true),
    ("/.a", true),
    ("/.a/", true),
    ("C:\\.a", false),
    ("C:\\a.", false),
    ("C:\\a.b\\", false),
    ("a\u{9}b/c\u{a}d", false),
    ("/home/user/proj/src/index.ts", true),
    ("C:\\Users\\me\\proj\\src\\index.ts", false),
    ("D:", false),
    ("D:x", false),
    ("d:\\", false),
    ("C:\\\\a\\\\\\b", false),
];

const POSIX_DIRNAME: &[(&str, &str)] = &[
    ("", "."),
    (".", "."),
    ("..", "."),
    ("/", "/"),
    ("//", "/"),
    ("///", "/"),
    ("a", "."),
    ("a/", "."),
    ("a//", "."),
    ("/a", "/"),
    ("/a/", "/"),
    ("a/b", "a"),
    ("/a/b/c", "/a/b"),
    ("/a/b/c/", "/a/b"),
    ("a/./b", "a/."),
    ("a/../b", "a/.."),
    ("../a", ".."),
    ("../../a/b", "../../a"),
    ("/../a", "/.."),
    ("/a/../../b", "/a/../.."),
    ("./", "."),
    ("./a", "."),
    ("a/b/../../..", "a/b/../.."),
    ("a/b/../../../c", "a/b/../../.."),
    (".a", "."),
    ("a.", "."),
    (".a.b", "."),
    ("a..b", "."),
    ("file.txt", "."),
    ("/dir/file.tar.gz", "/dir"),
    ("dir/.hidden", "dir"),
    ("/foo/bar/baz/asdf/quux.html", "/foo/bar/baz/asdf"),
    ("...", "."),
    ("..a", "."),
    ("a/...", "a"),
    ("/a/b/.", "/a/b"),
    ("/a/b/..", "/a/b"),
    ("a/b/./", "a/b"),
    (".//a//b//", ".//a/"),
    ("//a", "//"),
    ("//a/b", "//a"),
    ("C:", "."),
    ("C:\\", "."),
    ("C:/", "."),
    ("C:\\a\\b", "."),
    ("C:a", "."),
    ("C:a\\b", "."),
    ("c:/a/../b", "c:/a/.."),
    ("C:\\..\\..", "."),
    ("C:..", "."),
    ("\\\\server\\share", "."),
    ("\\\\server\\share\\", "."),
    ("\\\\server\\share\\a\\b", "."),
    ("//server/share/a", "//server/share"),
    ("\\\\server", "."),
    ("\\\\server\\", "."),
    ("\\\\?\\C:\\a", "."),
    ("\\\\?\\UNC\\srv\\shr\\x", "."),
    ("\\\\.\\pipe\\x", "."),
    ("\\a\\b", "."),
    ("a\\b", "."),
    ("a\\b\\..\\c", "."),
    ("\\", "."),
    ("\\\\", "."),
    ("\\\\\\", "."),
    ("\\\\\\a", "."),
    ("a/b\\c", "a"),
    ("file:stream", "."),
    ("COM1", "."),
    ("C:\\x\\COM1", "."),
    ("C:\\x\\CON.txt", "."),
    ("con", "."),
    ("aux:", "."),
    ("x/nul", "x"),
    ("LPT1:", "."),
    ("COM¹", "."),
    ("unicode/é/日本.txt", "unicode/é"),
    ("😀/x.y", "😀"),
    ("a b/c d.e f", "a b"),
    ("/a/b.c.d", "/a"),
    ("a.b/", "."),
    ("a.b//", "."),
    (".", "."),
    ("/.", "/"),
    ("/..", "/"),
    ("/.a", "/"),
    ("/.a/", "/"),
    ("C:\\.a", "."),
    ("C:\\a.", "."),
    ("C:\\a.b\\", "."),
    ("a\u{9}b/c\u{a}d", "a\u{9}b"),
    ("/home/user/proj/src/index.ts", "/home/user/proj/src"),
    ("C:\\Users\\me\\proj\\src\\index.ts", "."),
    ("D:", "."),
    ("D:x", "."),
    ("d:\\", "."),
    ("C:\\\\a\\\\\\b", "."),
];

const POSIX_EXTNAME: &[(&str, &str)] = &[
    ("", ""),
    (".", ""),
    ("..", ""),
    ("/", ""),
    ("//", ""),
    ("///", ""),
    ("a", ""),
    ("a/", ""),
    ("a//", ""),
    ("/a", ""),
    ("/a/", ""),
    ("a/b", ""),
    ("/a/b/c", ""),
    ("/a/b/c/", ""),
    ("a/./b", ""),
    ("a/../b", ""),
    ("../a", ""),
    ("../../a/b", ""),
    ("/../a", ""),
    ("/a/../../b", ""),
    ("./", ""),
    ("./a", ""),
    ("a/b/../../..", ""),
    ("a/b/../../../c", ""),
    (".a", ""),
    ("a.", "."),
    (".a.b", ".b"),
    ("a..b", ".b"),
    ("file.txt", ".txt"),
    ("/dir/file.tar.gz", ".gz"),
    ("dir/.hidden", ""),
    ("/foo/bar/baz/asdf/quux.html", ".html"),
    ("...", "."),
    ("..a", ".a"),
    ("a/...", "."),
    ("/a/b/.", ""),
    ("/a/b/..", ""),
    ("a/b/./", ""),
    (".//a//b//", ""),
    ("//a", ""),
    ("//a/b", ""),
    ("C:", ""),
    ("C:\\", ""),
    ("C:/", ""),
    ("C:\\a\\b", ""),
    ("C:a", ""),
    ("C:a\\b", ""),
    ("c:/a/../b", ""),
    ("C:\\..\\..", "."),
    ("C:..", "."),
    ("\\\\server\\share", ""),
    ("\\\\server\\share\\", ""),
    ("\\\\server\\share\\a\\b", ""),
    ("//server/share/a", ""),
    ("\\\\server", ""),
    ("\\\\server\\", ""),
    ("\\\\?\\C:\\a", ""),
    ("\\\\?\\UNC\\srv\\shr\\x", ""),
    ("\\\\.\\pipe\\x", ".\\pipe\\x"),
    ("\\a\\b", ""),
    ("a\\b", ""),
    ("a\\b\\..\\c", ".\\c"),
    ("\\", ""),
    ("\\\\", ""),
    ("\\\\\\", ""),
    ("\\\\\\a", ""),
    ("a/b\\c", ""),
    ("file:stream", ""),
    ("COM1", ""),
    ("C:\\x\\COM1", ""),
    ("C:\\x\\CON.txt", ".txt"),
    ("con", ""),
    ("aux:", ""),
    ("x/nul", ""),
    ("LPT1:", ""),
    ("COM¹", ""),
    ("unicode/é/日本.txt", ".txt"),
    ("😀/x.y", ".y"),
    ("a b/c d.e f", ".e f"),
    ("/a/b.c.d", ".d"),
    ("a.b/", ".b"),
    ("a.b//", ".b"),
    (".", ""),
    ("/.", ""),
    ("/..", ""),
    ("/.a", ""),
    ("/.a/", ""),
    ("C:\\.a", ".a"),
    ("C:\\a.", "."),
    ("C:\\a.b\\", ".b\\"),
    ("a\u{9}b/c\u{a}d", ""),
    ("/home/user/proj/src/index.ts", ".ts"),
    ("C:\\Users\\me\\proj\\src\\index.ts", ".ts"),
    ("D:", ""),
    ("D:x", ""),
    ("d:\\", ""),
    ("C:\\\\a\\\\\\b", ""),
];

const POSIX_BASENAME: &[(&str, Option<&str>, &str)] = &[
    ("", None, ""),
    (".", None, "."),
    ("..", None, ".."),
    ("/", None, ""),
    ("//", None, ""),
    ("///", None, ""),
    ("a", None, "a"),
    ("a/", None, "a"),
    ("a//", None, "a"),
    ("/a", None, "a"),
    ("/a/", None, "a"),
    ("a/b", None, "b"),
    ("/a/b/c", None, "c"),
    ("/a/b/c/", None, "c"),
    ("a/./b", None, "b"),
    ("a/../b", None, "b"),
    ("../a", None, "a"),
    ("../../a/b", None, "b"),
    ("/../a", None, "a"),
    ("/a/../../b", None, "b"),
    ("./", None, "."),
    ("./a", None, "a"),
    ("a/b/../../..", None, ".."),
    ("a/b/../../../c", None, "c"),
    (".a", None, ".a"),
    ("a.", None, "a."),
    (".a.b", None, ".a.b"),
    ("a..b", None, "a..b"),
    ("file.txt", None, "file.txt"),
    ("/dir/file.tar.gz", None, "file.tar.gz"),
    ("dir/.hidden", None, ".hidden"),
    ("/foo/bar/baz/asdf/quux.html", None, "quux.html"),
    ("...", None, "..."),
    ("..a", None, "..a"),
    ("a/...", None, "..."),
    ("/a/b/.", None, "."),
    ("/a/b/..", None, ".."),
    ("a/b/./", None, "."),
    (".//a//b//", None, "b"),
    ("//a", None, "a"),
    ("//a/b", None, "b"),
    ("C:", None, "C:"),
    ("C:\\", None, "C:\\"),
    ("C:/", None, "C:"),
    ("C:\\a\\b", None, "C:\\a\\b"),
    ("C:a", None, "C:a"),
    ("C:a\\b", None, "C:a\\b"),
    ("c:/a/../b", None, "b"),
    ("C:\\..\\..", None, "C:\\..\\.."),
    ("C:..", None, "C:.."),
    ("\\\\server\\share", None, "\\\\server\\share"),
    ("\\\\server\\share\\", None, "\\\\server\\share\\"),
    ("\\\\server\\share\\a\\b", None, "\\\\server\\share\\a\\b"),
    ("//server/share/a", None, "a"),
    ("\\\\server", None, "\\\\server"),
    ("\\\\server\\", None, "\\\\server\\"),
    ("\\\\?\\C:\\a", None, "\\\\?\\C:\\a"),
    ("\\\\?\\UNC\\srv\\shr\\x", None, "\\\\?\\UNC\\srv\\shr\\x"),
    ("\\\\.\\pipe\\x", None, "\\\\.\\pipe\\x"),
    ("\\a\\b", None, "\\a\\b"),
    ("a\\b", None, "a\\b"),
    ("a\\b\\..\\c", None, "a\\b\\..\\c"),
    ("\\", None, "\\"),
    ("\\\\", None, "\\\\"),
    ("\\\\\\", None, "\\\\\\"),
    ("\\\\\\a", None, "\\\\\\a"),
    ("a/b\\c", None, "b\\c"),
    ("file:stream", None, "file:stream"),
    ("COM1", None, "COM1"),
    ("C:\\x\\COM1", None, "C:\\x\\COM1"),
    ("C:\\x\\CON.txt", None, "C:\\x\\CON.txt"),
    ("con", None, "con"),
    ("aux:", None, "aux:"),
    ("x/nul", None, "nul"),
    ("LPT1:", None, "LPT1:"),
    ("COM¹", None, "COM¹"),
    ("unicode/é/日本.txt", None, "日本.txt"),
    ("😀/x.y", None, "x.y"),
    ("a b/c d.e f", None, "c d.e f"),
    ("/a/b.c.d", None, "b.c.d"),
    ("a.b/", None, "a.b"),
    ("a.b//", None, "a.b"),
    (".", None, "."),
    ("/.", None, "."),
    ("/..", None, ".."),
    ("/.a", None, ".a"),
    ("/.a/", None, ".a"),
    ("C:\\.a", None, "C:\\.a"),
    ("C:\\a.", None, "C:\\a."),
    ("C:\\a.b\\", None, "C:\\a.b\\"),
    ("a\u{9}b/c\u{a}d", None, "c\u{a}d"),
    ("/home/user/proj/src/index.ts", None, "index.ts"),
    (
        "C:\\Users\\me\\proj\\src\\index.ts",
        None,
        "C:\\Users\\me\\proj\\src\\index.ts",
    ),
    ("D:", None, "D:"),
    ("D:x", None, "D:x"),
    ("d:\\", None, "d:\\"),
    ("C:\\\\a\\\\\\b", None, "C:\\\\a\\\\\\b"),
    ("/a/b.html", Some(".html"), "b"),
    ("/a/b.html", Some("html"), "b."),
    ("/a/b.html", Some("b.html"), "b.html"),
    ("/a/b.html", Some("b.htmlx"), "b.html"),
    ("aaa/bbb", Some("bbb"), "bbb"),
    ("aaa/bbb", Some("a/bbb"), "bbb"),
    ("aaa/bbb//", Some("bbb"), "bbb"),
    ("aaa/bbb", Some("bb"), "b"),
    ("aaa/bbb", Some("b"), "bb"),
    ("/aaa/bbb", Some("/bbb"), "bbb"),
    ("/aaa/bbb", Some("a/bbb"), "bbb"),
    ("/aaa/bbb", Some("bbb"), "bbb"),
    ("/aaa/bbb//", Some("bbb"), "bbb"),
    ("/aaa/bbb", Some("bb"), "b"),
    ("/aaa/bbb", Some("b"), "bb"),
    ("/aaa/", Some("aaa"), "aaa"),
    ("/aaa/b", Some("b"), "b"),
    ("/a/b", Some("b"), "b"),
    ("//a", Some("a"), "a"),
    ("a", Some("a"), ""),
    ("file", Some(""), "file"),
    (".js", Some(".js"), ""),
    ("js", Some(".js"), "js"),
    ("C:\\a\\b.html", Some(".HTML"), "C:\\a\\b.html"),
    ("C:\\a\\B.html", Some("b.html"), "C:\\a\\B.html"),
    ("\\aaa\\bbb", Some("bbb"), "\\aaa\\"),
    ("C:", Some("C:"), ""),
    ("C:foo.txt", Some(".txt"), "C:foo"),
    ("x.ÉÉ", Some(".éé"), "x.ÉÉ"),
];

const POSIX_PARSE: &[(&str, [&str; 5])] = &[
    ("", ["", "", "", "", ""]),
    (".", ["", "", ".", "", "."]),
    ("..", ["", "", "..", "", ".."]),
    ("/", ["/", "/", "", "", ""]),
    ("//", ["/", "/", "", "", ""]),
    ("///", ["/", "/", "", "", ""]),
    ("a", ["", "", "a", "", "a"]),
    ("a/", ["", "", "a", "", "a"]),
    ("a//", ["", "", "a", "", "a"]),
    ("/a", ["/", "/", "a", "", "a"]),
    ("/a/", ["/", "/", "a", "", "a"]),
    ("a/b", ["", "a", "b", "", "b"]),
    ("/a/b/c", ["/", "/a/b", "c", "", "c"]),
    ("/a/b/c/", ["/", "/a/b", "c", "", "c"]),
    ("a/./b", ["", "a/.", "b", "", "b"]),
    ("a/../b", ["", "a/..", "b", "", "b"]),
    ("../a", ["", "..", "a", "", "a"]),
    ("../../a/b", ["", "../../a", "b", "", "b"]),
    ("/../a", ["/", "/..", "a", "", "a"]),
    ("/a/../../b", ["/", "/a/../..", "b", "", "b"]),
    ("./", ["", "", ".", "", "."]),
    ("./a", ["", ".", "a", "", "a"]),
    ("a/b/../../..", ["", "a/b/../..", "..", "", ".."]),
    ("a/b/../../../c", ["", "a/b/../../..", "c", "", "c"]),
    (".a", ["", "", ".a", "", ".a"]),
    ("a.", ["", "", "a.", ".", "a"]),
    (".a.b", ["", "", ".a.b", ".b", ".a"]),
    ("a..b", ["", "", "a..b", ".b", "a."]),
    ("file.txt", ["", "", "file.txt", ".txt", "file"]),
    ("/dir/file.tar.gz", ["/", "/dir", "file.tar.gz", ".gz", "file.tar"]),
    ("dir/.hidden", ["", "dir", ".hidden", "", ".hidden"]),
    (
        "/foo/bar/baz/asdf/quux.html",
        ["/", "/foo/bar/baz/asdf", "quux.html", ".html", "quux"],
    ),
    ("...", ["", "", "...", ".", ".."]),
    ("..a", ["", "", "..a", ".a", "."]),
    ("a/...", ["", "a", "...", ".", ".."]),
    ("/a/b/.", ["/", "/a/b", ".", "", "."]),
    ("/a/b/..", ["/", "/a/b", "..", "", ".."]),
    ("a/b/./", ["", "a/b", ".", "", "."]),
    (".//a//b//", ["", ".//a/", "b", "", "b"]),
    ("//a", ["/", "/", "a", "", "a"]),
    ("//a/b", ["/", "//a", "b", "", "b"]),
    ("C:", ["", "", "C:", "", "C:"]),
    ("C:\\", ["", "", "C:\\", "", "C:\\"]),
    ("C:/", ["", "", "C:", "", "C:"]),
    ("C:\\a\\b", ["", "", "C:\\a\\b", "", "C:\\a\\b"]),
    ("C:a", ["", "", "C:a", "", "C:a"]),
    ("C:a\\b", ["", "", "C:a\\b", "", "C:a\\b"]),
    ("c:/a/../b", ["", "c:/a/..", "b", "", "b"]),
    ("C:\\..\\..", ["", "", "C:\\..\\..", ".", "C:\\..\\."]),
    ("C:..", ["", "", "C:..", ".", "C:."]),
    (
        "\\\\server\\share",
        ["", "", "\\\\server\\share", "", "\\\\server\\share"],
    ),
    (
        "\\\\server\\share\\",
        ["", "", "\\\\server\\share\\", "", "\\\\server\\share\\"],
    ),
    (
        "\\\\server\\share\\a\\b",
        ["", "", "\\\\server\\share\\a\\b", "", "\\\\server\\share\\a\\b"],
    ),
    ("//server/share/a", ["/", "//server/share", "a", "", "a"]),
    ("\\\\server", ["", "", "\\\\server", "", "\\\\server"]),
    ("\\\\server\\", ["", "", "\\\\server\\", "", "\\\\server\\"]),
    ("\\\\?\\C:\\a", ["", "", "\\\\?\\C:\\a", "", "\\\\?\\C:\\a"]),
    (
        "\\\\?\\UNC\\srv\\shr\\x",
        ["", "", "\\\\?\\UNC\\srv\\shr\\x", "", "\\\\?\\UNC\\srv\\shr\\x"],
    ),
    ("\\\\.\\pipe\\x", ["", "", "\\\\.\\pipe\\x", ".\\pipe\\x", "\\\\"]),
    ("\\a\\b", ["", "", "\\a\\b", "", "\\a\\b"]),
    ("a\\b", ["", "", "a\\b", "", "a\\b"]),
    ("a\\b\\..\\c", ["", "", "a\\b\\..\\c", ".\\c", "a\\b\\."]),
    ("\\", ["", "", "\\", "", "\\"]),
    ("\\\\", ["", "", "\\\\", "", "\\\\"]),
    ("\\\\\\", ["", "", "\\\\\\", "", "\\\\\\"]),
    ("\\\\\\a", ["", "", "\\\\\\a", "", "\\\\\\a"]),
    ("a/b\\c", ["", "a", "b\\c", "", "b\\c"]),
    ("file:stream", ["", "", "file:stream", "", "file:stream"]),
    ("COM1", ["", "", "COM1", "", "COM1"]),
    ("C:\\x\\COM1", ["", "", "C:\\x\\COM1", "", "C:\\x\\COM1"]),
    ("C:\\x\\CON.txt", ["", "", "C:\\x\\CON.txt", ".txt", "C:\\x\\CON"]),
    ("con", ["", "", "con", "", "con"]),
    ("aux:", ["", "", "aux:", "", "aux:"]),
    ("x/nul", ["", "x", "nul", "", "nul"]),
    ("LPT1:", ["", "", "LPT1:", "", "LPT1:"]),
    ("COM¹", ["", "", "COM¹", "", "COM¹"]),
    ("unicode/é/日本.txt", ["", "unicode/é", "日本.txt", ".txt", "日本"]),
    ("😀/x.y", ["", "😀", "x.y", ".y", "x"]),
    ("a b/c d.e f", ["", "a b", "c d.e f", ".e f", "c d"]),
    ("/a/b.c.d", ["/", "/a", "b.c.d", ".d", "b.c"]),
    ("a.b/", ["", "", "a.b", ".b", "a"]),
    ("a.b//", ["", "", "a.b", ".b", "a"]),
    (".", ["", "", ".", "", "."]),
    ("/.", ["/", "/", ".", "", "."]),
    ("/..", ["/", "/", "..", ".", "."]),
    ("/.a", ["/", "/", ".a", "", ".a"]),
    ("/.a/", ["/", "/", ".a", "", ".a"]),
    ("C:\\.a", ["", "", "C:\\.a", ".a", "C:\\"]),
    ("C:\\a.", ["", "", "C:\\a.", ".", "C:\\a"]),
    ("C:\\a.b\\", ["", "", "C:\\a.b\\", ".b\\", "C:\\a"]),
    ("a\u{9}b/c\u{a}d", ["", "a\u{9}b", "c\u{a}d", "", "c\u{a}d"]),
    (
        "/home/user/proj/src/index.ts",
        ["/", "/home/user/proj/src", "index.ts", ".ts", "index"],
    ),
    (
        "C:\\Users\\me\\proj\\src\\index.ts",
        [
            "",
            "",
            "C:\\Users\\me\\proj\\src\\index.ts",
            ".ts",
            "C:\\Users\\me\\proj\\src\\index",
        ],
    ),
    ("D:", ["", "", "D:", "", "D:"]),
    ("D:x", ["", "", "D:x", "", "D:x"]),
    ("d:\\", ["", "", "d:\\", "", "d:\\"]),
    ("C:\\\\a\\\\\\b", ["", "", "C:\\\\a\\\\\\b", "", "C:\\\\a\\\\\\b"]),
];

const POSIX_FORMAT: &[([&str; 5], &str)] = &[
    (["/", "/a", "b.c", "", ""], "/a/b.c"),
    (["/", "", "", ".c", "b"], "/b.c"),
    (["", "", "", "c", "b"], "b.c"),
    (["/", "/", "x", "", ""], "/x"),
    (["", "a", "", "", ""], "a/"),
    (["C:\\", "C:\\a", "b", "", ""], "C:\\a/b"),
    (["C:\\", "", "", ".txt", "f"], "C:\\f.txt"),
    (["", "", "", "", ""], ""),
    (["", "C:\\", "x", "", ""], "C:\\/x"),
    (["/", "", ".", "", ""], "/."),
    (["", "", "", "..", "a"], "a.."),
    (["", "x", "", ".", ""], "x/."),
];

const POSIX_JOIN: &[(&[&str], &str)] = &[
    (&[], "."),
    (&[""], "."),
    (&["", ""], "."),
    (&["a"], "a"),
    (&["a", "b"], "a/b"),
    (&["/a", "b", "c"], "/a/b/c"),
    (&["a", "/b"], "a/b"),
    (&["a/", "/b"], "a/b"),
    (&["a", "", "b"], "a/b"),
    (&["", "a"], "a"),
    (&["", "/a"], "/a"),
    (&["/", "a"], "/a"),
    (&["a", "..", "b"], "b"),
    (&["a", "../..", "b"], "../b"),
    (&[".", "."], "."),
    (&["..", "a"], "../a"),
    (&["/a", "..", ".."], "/"),
    (&["a", "b/"], "a/b/"),
    (&["a\\", "b"], "a\\/b"),
    (&["C:", "a"], "C:/a"),
    (&["C:\\", "a"], "C:\\/a"),
    (&["C:", "\\a"], "C:/\\a"),
    (&["\\\\server", "share"], "\\\\server/share"),
    (&["//server", "share"], "/server/share"),
    (&["\\\\", "server", "share"], "\\\\/server/share"),
    (&["//", "server/share"], "/server/share"),
    (&["\\\\server\\share", "a"], "\\\\server\\share/a"),
    (&["\\", "\\server", "share"], "\\/\\server/share"),
    (&["", "", "/"], "/"),
    (&["", ".", "a"], "a"),
    (&["/a/b", "./c", "../d"], "/a/b/d"),
    (&["é", "日本"], "é/日本"),
    (&["a", "COM1"], "a/COM1"),
    (&["C:", "COM1"], "C:/COM1"),
    (&["x", "C:"], "x/C:"),
    (&["./", "C:a"], "C:a"),
    (&["\\\\?\\C:", "a"], "\\\\?\\C:/a"),
    (&["a/", ""], "a/"),
    (&["/", "/"], "/"),
    (&["//", "/a"], "/a"),
];

const POSIX_RESOLVE_PCWD: &[(&[&str], &str)] = &[
    (&[], "/home/user/proj"),
    (&[""], "/home/user/proj"),
    (&["."], "/home/user/proj"),
    (&["a"], "/home/user/proj/a"),
    (&["/a"], "/a"),
    (&["a", "b"], "/home/user/proj/a/b"),
    (&["/a", "b"], "/a/b"),
    (&["/a", "/b"], "/b"),
    (&["a", "/b", "c"], "/b/c"),
    (&["/a/b", "../c"], "/a/c"),
    (&["/a/b", "../../.."], "/"),
    (&[".."], "/home/user"),
    (&["../..", "x"], "/home/x"),
    (&["", ""], "/home/user/proj"),
    (&["/", ""], "/"),
    (&["a/", "b/"], "/home/user/proj/a/b"),
    (&["/foo/bar", "./baz"], "/foo/bar/baz"),
    (&["/foo/bar", "/tmp/file/"], "/tmp/file"),
    (
        &["wwwroot", "static_files/png/", "../gif/image.gif"],
        "/home/user/proj/wwwroot/static_files/gif/image.gif",
    ),
    (&["C:\\a", "b"], "/home/user/proj/C:\\a/b"),
    (&["C:a", "b"], "/home/user/proj/C:a/b"),
    (&["C:"], "/home/user/proj/C:"),
    (&["D:"], "/home/user/proj/D:"),
    (&["D:x"], "/home/user/proj/D:x"),
    (&["d:x", "..\\y"], "/home/user/proj/d:x/..\\y"),
    (
        &["c:/ignore", "d:\\a/b\\c/d", "\\e.exe"],
        "/home/user/proj/c:/ignore/d:\\a/b\\c/d/\\e.exe",
    ),
    (&["c:/ignore", "c:/some/file"], "/home/user/proj/c:/ignore/c:/some/file"),
    (&["d:/ignore", "d:some/dir//"], "/home/user/proj/d:/ignore/d:some/dir"),
    (&["//server/share", "..", "relative\\"], "/server/relative\\"),
    (&["c:/", "//"], "/"),
    (&["c:/", "//dir"], "/dir"),
    (&["c:/", "//server/share"], "/server/share"),
    (&["c:/", "//server//share"], "/server/share"),
    (&["c:/", "///some//dir"], "/some/dir"),
    (&["\\\\server\\share", "x"], "/home/user/proj/\\\\server\\share/x"),
    (&["\\\\?\\C:\\a", "b"], "/home/user/proj/\\\\?\\C:\\a/b"),
    (
        &["C:\\foo\\tmp.3\\", "..\\tmp.3\\cycles\\root.js"],
        "/home/user/proj/C:\\foo\\tmp.3\\/..\\tmp.3\\cycles\\root.js",
    ),
    (&["\\a", "b"], "/home/user/proj/\\a/b"),
    (&["a\\b", "c"], "/home/user/proj/a\\b/c"),
    (&["C:", "\\x"], "/home/user/proj/C:/\\x"),
    (&["C:\\x", "D:"], "/home/user/proj/C:\\x/D:"),
    (&["/a", "C:"], "/a/C:"),
    (&["COM1"], "/home/user/proj/COM1"),
    (&["x", "COM1"], "/home/user/proj/x/COM1"),
    (&["E:x"], "/home/user/proj/E:x"),
    (&["e:", "y"], "/home/user/proj/e:/y"),
    (&["D:\\a", "D:b"], "/home/user/proj/D:\\a/D:b"),
];

const POSIX_RELATIVE_PCWD: &[(&str, &str, &str)] = &[
    ("", "", ""),
    ("/", "/", ""),
    ("/a", "/a", ""),
    ("/a", "/b", "../b"),
    ("/a/b", "/a", ".."),
    ("/a", "/a/b", "b"),
    ("/a/b/c", "/a/x/y", "../../x/y"),
    ("/var/lib", "/var", ".."),
    ("/var/lib", "/bin", "../../bin"),
    ("/var/lib", "/var/lib", ""),
    ("/var/lib", "/var/apache", "../apache"),
    ("/var/", "/var/lib", "lib"),
    ("/", "/var/lib", "var/lib"),
    ("/foo/test", "/foo/test/bar/package.json", "bar/package.json"),
    ("/Users/a/web/b/test/mails", "/Users/a/web/b", "../.."),
    ("/foo/bar/baz-quux", "/foo/bar/baz", "../baz"),
    ("/foo/bar/baz", "/foo/bar/baz-quux", "../baz-quux"),
    ("/baz-quux", "/baz", "../baz"),
    ("/baz", "/baz-quux", "../baz-quux"),
    ("/page1/page2/foo", "/", "../../.."),
    ("a", "b", "../b"),
    ("a/b", "a", ".."),
    ("", "/x", "../../../x"),
    ("/x", "", "../home/user/proj"),
    ("c:/blah\\blah", "d:/games", "../../d:/games"),
    ("c:/aaaa/bbbb", "c:/aaaa", ".."),
    ("c:/aaaa/bbbb", "c:/cccc", "../../cccc"),
    ("c:/aaaa/bbbb", "c:/aaaa/bbbb", ""),
    ("c:/aaaa/bbbb", "c:/aaaa/cccc", "../cccc"),
    ("c:/aaaa/", "c:/aaaa/cccc", "cccc"),
    ("c:/", "c:\\aaaa\\bbbb", "../c:\\aaaa\\bbbb"),
    ("c:/aaaa/bbbb", "d:\\", "../../../d:\\"),
    ("c:/AaAa/bbbb", "c:/aaaa/bbbb", "../../aaaa/bbbb"),
    ("c:/aaaaa/", "c:/aaaa/cccc", "../aaaa/cccc"),
    ("C:\\foo\\bar\\baz\\quux", "C:\\", "../C:\\"),
    (
        "C:\\foo\\test",
        "C:\\foo\\test\\bar\\package.json",
        "../C:\\foo\\test\\bar\\package.json",
    ),
    ("C:\\foo\\bar\\baz-quux", "C:\\foo\\bar\\baz", "../C:\\foo\\bar\\baz"),
    (
        "C:\\foo\\bar\\baz",
        "C:\\foo\\bar\\baz-quux",
        "../C:\\foo\\bar\\baz-quux",
    ),
    ("\\\\foo\\bar", "\\\\foo\\bar\\baz", "../\\\\foo\\bar\\baz"),
    ("\\\\foo\\bar\\baz", "\\\\foo\\bar", "../\\\\foo\\bar"),
    ("\\\\foo\\bar\\baz-quux", "\\\\foo\\bar\\baz", "../\\\\foo\\bar\\baz"),
    (
        "\\\\foo\\bar\\baz",
        "\\\\foo\\bar\\baz-quux",
        "../\\\\foo\\bar\\baz-quux",
    ),
    ("C:\\baz-quux", "C:\\baz", "../C:\\baz"),
    ("C:\\baz", "C:\\baz-quux", "../C:\\baz-quux"),
    ("\\\\foo\\baz-quux", "\\\\foo\\baz", "../\\\\foo\\baz"),
    ("\\\\foo\\baz", "\\\\foo\\baz-quux", "../\\\\foo\\baz-quux"),
    ("C:\\baz", "\\\\foo\\bar\\baz", "../\\\\foo\\bar\\baz"),
    ("\\\\foo\\bar\\baz", "C:\\baz", "../C:\\baz"),
    ("C:\\Ä", "C:\\ä\\x", "../C:\\ä\\x"),
    ("C:\\ǅ", "C:\\ǆ", "../C:\\ǆ"),
    ("a", "C:\\b", "../C:\\b"),
    ("x\\y", "x\\z", "../x\\z"),
];

const POSIX_NAMESPACED_PCWD: &[(&str, &str)] = &[
    ("", ""),
    (".", "."),
    ("..", ".."),
    ("/", "/"),
    ("//", "//"),
    ("///", "///"),
    ("a", "a"),
    ("a/", "a/"),
    ("a//", "a//"),
    ("/a", "/a"),
    ("/a/", "/a/"),
    ("a/b", "a/b"),
    ("/a/b/c", "/a/b/c"),
    ("/a/b/c/", "/a/b/c/"),
    ("a/./b", "a/./b"),
    ("a/../b", "a/../b"),
    ("../a", "../a"),
    ("../../a/b", "../../a/b"),
    ("/../a", "/../a"),
    ("/a/../../b", "/a/../../b"),
    ("./", "./"),
    ("./a", "./a"),
    ("a/b/../../..", "a/b/../../.."),
    ("a/b/../../../c", "a/b/../../../c"),
    (".a", ".a"),
    ("a.", "a."),
    (".a.b", ".a.b"),
    ("a..b", "a..b"),
    ("file.txt", "file.txt"),
    ("/dir/file.tar.gz", "/dir/file.tar.gz"),
    ("dir/.hidden", "dir/.hidden"),
    ("/foo/bar/baz/asdf/quux.html", "/foo/bar/baz/asdf/quux.html"),
    ("...", "..."),
    ("..a", "..a"),
    ("a/...", "a/..."),
    ("/a/b/.", "/a/b/."),
    ("/a/b/..", "/a/b/.."),
    ("a/b/./", "a/b/./"),
    (".//a//b//", ".//a//b//"),
    ("//a", "//a"),
    ("//a/b", "//a/b"),
    ("C:", "C:"),
    ("C:\\", "C:\\"),
    ("C:/", "C:/"),
    ("C:\\a\\b", "C:\\a\\b"),
    ("C:a", "C:a"),
    ("C:a\\b", "C:a\\b"),
    ("c:/a/../b", "c:/a/../b"),
    ("C:\\..\\..", "C:\\..\\.."),
    ("C:..", "C:.."),
    ("\\\\server\\share", "\\\\server\\share"),
    ("\\\\server\\share\\", "\\\\server\\share\\"),
    ("\\\\server\\share\\a\\b", "\\\\server\\share\\a\\b"),
    ("//server/share/a", "//server/share/a"),
    ("\\\\server", "\\\\server"),
    ("\\\\server\\", "\\\\server\\"),
    ("\\\\?\\C:\\a", "\\\\?\\C:\\a"),
    ("\\\\?\\UNC\\srv\\shr\\x", "\\\\?\\UNC\\srv\\shr\\x"),
    ("\\\\.\\pipe\\x", "\\\\.\\pipe\\x"),
    ("\\a\\b", "\\a\\b"),
    ("a\\b", "a\\b"),
    ("a\\b\\..\\c", "a\\b\\..\\c"),
    ("\\", "\\"),
    ("\\\\", "\\\\"),
    ("\\\\\\", "\\\\\\"),
    ("\\\\\\a", "\\\\\\a"),
    ("a/b\\c", "a/b\\c"),
    ("file:stream", "file:stream"),
    ("COM1", "COM1"),
    ("C:\\x\\COM1", "C:\\x\\COM1"),
    ("C:\\x\\CON.txt", "C:\\x\\CON.txt"),
    ("con", "con"),
    ("aux:", "aux:"),
    ("x/nul", "x/nul"),
    ("LPT1:", "LPT1:"),
    ("COM¹", "COM¹"),
    ("unicode/é/日本.txt", "unicode/é/日本.txt"),
    ("😀/x.y", "😀/x.y"),
    ("a b/c d.e f", "a b/c d.e f"),
    ("/a/b.c.d", "/a/b.c.d"),
    ("a.b/", "a.b/"),
    ("a.b//", "a.b//"),
    (".", "."),
    ("/.", "/."),
    ("/..", "/.."),
    ("/.a", "/.a"),
    ("/.a/", "/.a/"),
    ("C:\\.a", "C:\\.a"),
    ("C:\\a.", "C:\\a."),
    ("C:\\a.b\\", "C:\\a.b\\"),
    ("a\u{9}b/c\u{a}d", "a\u{9}b/c\u{a}d"),
    ("/home/user/proj/src/index.ts", "/home/user/proj/src/index.ts"),
    (
        "C:\\Users\\me\\proj\\src\\index.ts",
        "C:\\Users\\me\\proj\\src\\index.ts",
    ),
    ("D:", "D:"),
    ("D:x", "D:x"),
    ("d:\\", "d:\\"),
    ("C:\\\\a\\\\\\b", "C:\\\\a\\\\\\b"),
];

const POSIX_RESOLVE_WCWD: &[(&[&str], &str)] = &[
    (&[], "C:\\Users\\me\\proj"),
    (&[""], "C:\\Users\\me\\proj"),
    (&["."], "C:\\Users\\me\\proj"),
    (&["a"], "C:\\Users\\me\\proj/a"),
    (&["/a"], "/a"),
    (&["a", "b"], "C:\\Users\\me\\proj/a/b"),
    (&["/a", "b"], "/a/b"),
    (&["/a", "/b"], "/b"),
    (&["a", "/b", "c"], "/b/c"),
    (&["/a/b", "../c"], "/a/c"),
    (&["/a/b", "../../.."], "/"),
    (&[".."], "."),
    (&["../..", "x"], "../x"),
    (&["", ""], "C:\\Users\\me\\proj"),
    (&["/", ""], "/"),
    (&["a/", "b/"], "C:\\Users\\me\\proj/a/b"),
    (&["/foo/bar", "./baz"], "/foo/bar/baz"),
    (&["/foo/bar", "/tmp/file/"], "/tmp/file"),
    (
        &["wwwroot", "static_files/png/", "../gif/image.gif"],
        "C:\\Users\\me\\proj/wwwroot/static_files/gif/image.gif",
    ),
    (&["C:\\a", "b"], "C:\\Users\\me\\proj/C:\\a/b"),
    (&["C:a", "b"], "C:\\Users\\me\\proj/C:a/b"),
    (&["C:"], "C:\\Users\\me\\proj/C:"),
    (&["D:"], "C:\\Users\\me\\proj/D:"),
    (&["D:x"], "C:\\Users\\me\\proj/D:x"),
    (&["d:x", "..\\y"], "C:\\Users\\me\\proj/d:x/..\\y"),
    (
        &["c:/ignore", "d:\\a/b\\c/d", "\\e.exe"],
        "C:\\Users\\me\\proj/c:/ignore/d:\\a/b\\c/d/\\e.exe",
    ),
    (
        &["c:/ignore", "c:/some/file"],
        "C:\\Users\\me\\proj/c:/ignore/c:/some/file",
    ),
    (
        &["d:/ignore", "d:some/dir//"],
        "C:\\Users\\me\\proj/d:/ignore/d:some/dir",
    ),
    (&["//server/share", "..", "relative\\"], "/server/relative\\"),
    (&["c:/", "//"], "/"),
    (&["c:/", "//dir"], "/dir"),
    (&["c:/", "//server/share"], "/server/share"),
    (&["c:/", "//server//share"], "/server/share"),
    (&["c:/", "///some//dir"], "/some/dir"),
    (&["\\\\server\\share", "x"], "C:\\Users\\me\\proj/\\\\server\\share/x"),
    (&["\\\\?\\C:\\a", "b"], "C:\\Users\\me\\proj/\\\\?\\C:\\a/b"),
    (
        &["C:\\foo\\tmp.3\\", "..\\tmp.3\\cycles\\root.js"],
        "C:\\Users\\me\\proj/C:\\foo\\tmp.3\\/..\\tmp.3\\cycles\\root.js",
    ),
    (&["\\a", "b"], "C:\\Users\\me\\proj/\\a/b"),
    (&["a\\b", "c"], "C:\\Users\\me\\proj/a\\b/c"),
    (&["C:", "\\x"], "C:\\Users\\me\\proj/C:/\\x"),
    (&["C:\\x", "D:"], "C:\\Users\\me\\proj/C:\\x/D:"),
    (&["/a", "C:"], "/a/C:"),
    (&["COM1"], "C:\\Users\\me\\proj/COM1"),
    (&["x", "COM1"], "C:\\Users\\me\\proj/x/COM1"),
    (&["E:x"], "C:\\Users\\me\\proj/E:x"),
    (&["e:", "y"], "C:\\Users\\me\\proj/e:/y"),
    (&["D:\\a", "D:b"], "C:\\Users\\me\\proj/D:\\a/D:b"),
];

const POSIX_RELATIVE_WCWD: &[(&str, &str, &str)] = &[
    ("", "", ""),
    ("/", "/", ""),
    ("/a", "/a", ""),
    ("/a", "/b", "../b"),
    ("/a/b", "/a", ".."),
    ("/a", "/a/b", "b"),
    ("/a/b/c", "/a/x/y", "../../x/y"),
    ("/var/lib", "/var", ".."),
    ("/var/lib", "/bin", "../../bin"),
    ("/var/lib", "/var/lib", ""),
    ("/var/lib", "/var/apache", "../apache"),
    ("/var/", "/var/lib", "lib"),
    ("/", "/var/lib", "var/lib"),
    ("/foo/test", "/foo/test/bar/package.json", "bar/package.json"),
    ("/Users/a/web/b/test/mails", "/Users/a/web/b", "../.."),
    ("/foo/bar/baz-quux", "/foo/bar/baz", "../baz"),
    ("/foo/bar/baz", "/foo/bar/baz-quux", "../baz-quux"),
    ("/baz-quux", "/baz", "../baz"),
    ("/baz", "/baz-quux", "../baz-quux"),
    ("/page1/page2/foo", "/", "../../.."),
    ("a", "b", "../b"),
    ("a/b", "a", ".."),
    ("", "/x", "../x"),
    ("/x", "", "..C:\\Users\\me\\proj"),
    ("c:/blah\\blah", "d:/games", "../../d:/games"),
    ("c:/aaaa/bbbb", "c:/aaaa", ".."),
    ("c:/aaaa/bbbb", "c:/cccc", "../../cccc"),
    ("c:/aaaa/bbbb", "c:/aaaa/bbbb", ""),
    ("c:/aaaa/bbbb", "c:/aaaa/cccc", "../cccc"),
    ("c:/aaaa/", "c:/aaaa/cccc", "cccc"),
    ("c:/", "c:\\aaaa\\bbbb", "../c:\\aaaa\\bbbb"),
    ("c:/aaaa/bbbb", "d:\\", "../../../d:\\"),
    ("c:/AaAa/bbbb", "c:/aaaa/bbbb", "../../aaaa/bbbb"),
    ("c:/aaaaa/", "c:/aaaa/cccc", "../aaaa/cccc"),
    ("C:\\foo\\bar\\baz\\quux", "C:\\", "../C:\\"),
    (
        "C:\\foo\\test",
        "C:\\foo\\test\\bar\\package.json",
        "../C:\\foo\\test\\bar\\package.json",
    ),
    ("C:\\foo\\bar\\baz-quux", "C:\\foo\\bar\\baz", "../C:\\foo\\bar\\baz"),
    (
        "C:\\foo\\bar\\baz",
        "C:\\foo\\bar\\baz-quux",
        "../C:\\foo\\bar\\baz-quux",
    ),
    ("\\\\foo\\bar", "\\\\foo\\bar\\baz", "../\\\\foo\\bar\\baz"),
    ("\\\\foo\\bar\\baz", "\\\\foo\\bar", "../\\\\foo\\bar"),
    ("\\\\foo\\bar\\baz-quux", "\\\\foo\\bar\\baz", "../\\\\foo\\bar\\baz"),
    (
        "\\\\foo\\bar\\baz",
        "\\\\foo\\bar\\baz-quux",
        "../\\\\foo\\bar\\baz-quux",
    ),
    ("C:\\baz-quux", "C:\\baz", "../C:\\baz"),
    ("C:\\baz", "C:\\baz-quux", "../C:\\baz-quux"),
    ("\\\\foo\\baz-quux", "\\\\foo\\baz", "../\\\\foo\\baz"),
    ("\\\\foo\\baz", "\\\\foo\\baz-quux", "../\\\\foo\\baz-quux"),
    ("C:\\baz", "\\\\foo\\bar\\baz", "../\\\\foo\\bar\\baz"),
    ("\\\\foo\\bar\\baz", "C:\\baz", "../C:\\baz"),
    ("C:\\Ä", "C:\\ä\\x", "../C:\\ä\\x"),
    ("C:\\ǅ", "C:\\ǆ", "../C:\\ǆ"),
    ("a", "C:\\b", "../C:\\b"),
    ("x\\y", "x\\z", "../x\\z"),
];

const POSIX_NAMESPACED_WCWD: &[(&str, &str)] = &[
    ("", ""),
    (".", "."),
    ("..", ".."),
    ("/", "/"),
    ("//", "//"),
    ("///", "///"),
    ("a", "a"),
    ("a/", "a/"),
    ("a//", "a//"),
    ("/a", "/a"),
    ("/a/", "/a/"),
    ("a/b", "a/b"),
    ("/a/b/c", "/a/b/c"),
    ("/a/b/c/", "/a/b/c/"),
    ("a/./b", "a/./b"),
    ("a/../b", "a/../b"),
    ("../a", "../a"),
    ("../../a/b", "../../a/b"),
    ("/../a", "/../a"),
    ("/a/../../b", "/a/../../b"),
    ("./", "./"),
    ("./a", "./a"),
    ("a/b/../../..", "a/b/../../.."),
    ("a/b/../../../c", "a/b/../../../c"),
    (".a", ".a"),
    ("a.", "a."),
    (".a.b", ".a.b"),
    ("a..b", "a..b"),
    ("file.txt", "file.txt"),
    ("/dir/file.tar.gz", "/dir/file.tar.gz"),
    ("dir/.hidden", "dir/.hidden"),
    ("/foo/bar/baz/asdf/quux.html", "/foo/bar/baz/asdf/quux.html"),
    ("...", "..."),
    ("..a", "..a"),
    ("a/...", "a/..."),
    ("/a/b/.", "/a/b/."),
    ("/a/b/..", "/a/b/.."),
    ("a/b/./", "a/b/./"),
    (".//a//b//", ".//a//b//"),
    ("//a", "//a"),
    ("//a/b", "//a/b"),
    ("C:", "C:"),
    ("C:\\", "C:\\"),
    ("C:/", "C:/"),
    ("C:\\a\\b", "C:\\a\\b"),
    ("C:a", "C:a"),
    ("C:a\\b", "C:a\\b"),
    ("c:/a/../b", "c:/a/../b"),
    ("C:\\..\\..", "C:\\..\\.."),
    ("C:..", "C:.."),
    ("\\\\server\\share", "\\\\server\\share"),
    ("\\\\server\\share\\", "\\\\server\\share\\"),
    ("\\\\server\\share\\a\\b", "\\\\server\\share\\a\\b"),
    ("//server/share/a", "//server/share/a"),
    ("\\\\server", "\\\\server"),
    ("\\\\server\\", "\\\\server\\"),
    ("\\\\?\\C:\\a", "\\\\?\\C:\\a"),
    ("\\\\?\\UNC\\srv\\shr\\x", "\\\\?\\UNC\\srv\\shr\\x"),
    ("\\\\.\\pipe\\x", "\\\\.\\pipe\\x"),
    ("\\a\\b", "\\a\\b"),
    ("a\\b", "a\\b"),
    ("a\\b\\..\\c", "a\\b\\..\\c"),
    ("\\", "\\"),
    ("\\\\", "\\\\"),
    ("\\\\\\", "\\\\\\"),
    ("\\\\\\a", "\\\\\\a"),
    ("a/b\\c", "a/b\\c"),
    ("file:stream", "file:stream"),
    ("COM1", "COM1"),
    ("C:\\x\\COM1", "C:\\x\\COM1"),
    ("C:\\x\\CON.txt", "C:\\x\\CON.txt"),
    ("con", "con"),
    ("aux:", "aux:"),
    ("x/nul", "x/nul"),
    ("LPT1:", "LPT1:"),
    ("COM¹", "COM¹"),
    ("unicode/é/日本.txt", "unicode/é/日本.txt"),
    ("😀/x.y", "😀/x.y"),
    ("a b/c d.e f", "a b/c d.e f"),
    ("/a/b.c.d", "/a/b.c.d"),
    ("a.b/", "a.b/"),
    ("a.b//", "a.b//"),
    (".", "."),
    ("/.", "/."),
    ("/..", "/.."),
    ("/.a", "/.a"),
    ("/.a/", "/.a/"),
    ("C:\\.a", "C:\\.a"),
    ("C:\\a.", "C:\\a."),
    ("C:\\a.b\\", "C:\\a.b\\"),
    ("a\u{9}b/c\u{a}d", "a\u{9}b/c\u{a}d"),
    ("/home/user/proj/src/index.ts", "/home/user/proj/src/index.ts"),
    (
        "C:\\Users\\me\\proj\\src\\index.ts",
        "C:\\Users\\me\\proj\\src\\index.ts",
    ),
    ("D:", "D:"),
    ("D:x", "D:x"),
    ("d:\\", "d:\\"),
    ("C:\\\\a\\\\\\b", "C:\\\\a\\\\\\b"),
];

const WIN32_NORMALIZE: &[(&str, &str)] = &[
    ("", "."),
    (".", "."),
    ("..", ".."),
    ("/", "\\"),
    ("//", "\\"),
    ("///", "\\"),
    ("a", "a"),
    ("a/", "a\\"),
    ("a//", "a\\"),
    ("/a", "\\a"),
    ("/a/", "\\a\\"),
    ("a/b", "a\\b"),
    ("/a/b/c", "\\a\\b\\c"),
    ("/a/b/c/", "\\a\\b\\c\\"),
    ("a/./b", "a\\b"),
    ("a/../b", "b"),
    ("../a", "..\\a"),
    ("../../a/b", "..\\..\\a\\b"),
    ("/../a", "\\a"),
    ("/a/../../b", "\\b"),
    ("./", ".\\"),
    ("./a", "a"),
    ("a/b/../../..", ".."),
    ("a/b/../../../c", "..\\c"),
    (".a", ".a"),
    ("a.", "a."),
    (".a.b", ".a.b"),
    ("a..b", "a..b"),
    ("file.txt", "file.txt"),
    ("/dir/file.tar.gz", "\\dir\\file.tar.gz"),
    ("dir/.hidden", "dir\\.hidden"),
    ("/foo/bar/baz/asdf/quux.html", "\\foo\\bar\\baz\\asdf\\quux.html"),
    ("...", "..."),
    ("..a", "..a"),
    ("a/...", "a\\..."),
    ("/a/b/.", "\\a\\b"),
    ("/a/b/..", "\\a"),
    ("a/b/./", "a\\b\\"),
    (".//a//b//", "a\\b\\"),
    ("//a", "\\a"),
    ("//a/b", "\\\\a\\b\\"),
    ("C:", "C:."),
    ("C:\\", "C:\\"),
    ("C:/", "C:\\"),
    ("C:\\a\\b", "C:\\a\\b"),
    ("C:a", "C:a"),
    ("C:a\\b", "C:a\\b"),
    ("c:/a/../b", "c:\\b"),
    ("C:\\..\\..", "C:\\"),
    ("C:..", "C:.."),
    ("\\\\server\\share", "\\\\server\\share\\"),
    ("\\\\server\\share\\", "\\\\server\\share\\"),
    ("\\\\server\\share\\a\\b", "\\\\server\\share\\a\\b"),
    ("//server/share/a", "\\\\server\\share\\a"),
    ("\\\\server", "\\server"),
    ("\\\\server\\", "\\server\\"),
    ("\\\\?\\C:\\a", "\\\\?\\C:\\a"),
    ("\\\\?\\UNC\\srv\\shr\\x", "\\\\?\\UNC\\srv\\shr\\x"),
    ("\\\\.\\pipe\\x", "\\\\.\\pipe\\x"),
    ("\\a\\b", "\\a\\b"),
    ("a\\b", "a\\b"),
    ("a\\b\\..\\c", "a\\c"),
    ("\\", "\\"),
    ("\\\\", "\\"),
    ("\\\\\\", "\\"),
    ("\\\\\\a", "\\a"),
    ("a/b\\c", "a\\b\\c"),
    ("file:stream", "file:stream"),
    ("COM1", "COM1"),
    ("C:\\x\\COM1", "C:\\x\\COM1"),
    ("C:\\x\\CON.txt", "C:\\x\\CON.txt"),
    ("con", "con"),
    ("aux:", ".\\aux:."),
    ("x/nul", "x\\nul"),
    ("LPT1:", ".\\LPT1:."),
    ("COM¹", "COM¹"),
    ("unicode/é/日本.txt", "unicode\\é\\日本.txt"),
    ("😀/x.y", "😀\\x.y"),
    ("a b/c d.e f", "a b\\c d.e f"),
    ("/a/b.c.d", "\\a\\b.c.d"),
    ("a.b/", "a.b\\"),
    ("a.b//", "a.b\\"),
    (".", "."),
    ("/.", "\\"),
    ("/..", "\\"),
    ("/.a", "\\.a"),
    ("/.a/", "\\.a\\"),
    ("C:\\.a", "C:\\.a"),
    ("C:\\a.", "C:\\a."),
    ("C:\\a.b\\", "C:\\a.b\\"),
    ("a\u{9}b/c\u{a}d", "a\u{9}b\\c\u{a}d"),
    ("/home/user/proj/src/index.ts", "\\home\\user\\proj\\src\\index.ts"),
    (
        "C:\\Users\\me\\proj\\src\\index.ts",
        "C:\\Users\\me\\proj\\src\\index.ts",
    ),
    ("D:", "D:."),
    ("D:x", "D:x"),
    ("d:\\", "d:\\"),
    ("C:\\\\a\\\\\\b", "C:\\a\\b"),
];

const WIN32_IS_ABSOLUTE: &[(&str, bool)] = &[
    ("", false),
    (".", false),
    ("..", false),
    ("/", true),
    ("//", true),
    ("///", true),
    ("a", false),
    ("a/", false),
    ("a//", false),
    ("/a", true),
    ("/a/", true),
    ("a/b", false),
    ("/a/b/c", true),
    ("/a/b/c/", true),
    ("a/./b", false),
    ("a/../b", false),
    ("../a", false),
    ("../../a/b", false),
    ("/../a", true),
    ("/a/../../b", true),
    ("./", false),
    ("./a", false),
    ("a/b/../../..", false),
    ("a/b/../../../c", false),
    (".a", false),
    ("a.", false),
    (".a.b", false),
    ("a..b", false),
    ("file.txt", false),
    ("/dir/file.tar.gz", true),
    ("dir/.hidden", false),
    ("/foo/bar/baz/asdf/quux.html", true),
    ("...", false),
    ("..a", false),
    ("a/...", false),
    ("/a/b/.", true),
    ("/a/b/..", true),
    ("a/b/./", false),
    (".//a//b//", false),
    ("//a", true),
    ("//a/b", true),
    ("C:", false),
    ("C:\\", true),
    ("C:/", true),
    ("C:\\a\\b", true),
    ("C:a", false),
    ("C:a\\b", false),
    ("c:/a/../b", true),
    ("C:\\..\\..", true),
    ("C:..", false),
    ("\\\\server\\share", true),
    ("\\\\server\\share\\", true),
    ("\\\\server\\share\\a\\b", true),
    ("//server/share/a", true),
    ("\\\\server", true),
    ("\\\\server\\", true),
    ("\\\\?\\C:\\a", true),
    ("\\\\?\\UNC\\srv\\shr\\x", true),
    ("\\\\.\\pipe\\x", true),
    ("\\a\\b", true),
    ("a\\b", false),
    ("a\\b\\..\\c", false),
    ("\\", true),
    ("\\\\", true),
    ("\\\\\\", true),
    ("\\\\\\a", true),
    ("a/b\\c", false),
    ("file:stream", false),
    ("COM1", false),
    ("C:\\x\\COM1", true),
    ("C:\\x\\CON.txt", true),
    ("con", false),
    ("aux:", false),
    ("x/nul", false),
    ("LPT1:", false),
    ("COM¹", false),
    ("unicode/é/日本.txt", false),
    ("😀/x.y", false),
    ("a b/c d.e f", false),
    ("/a/b.c.d", true),
    ("a.b/", false),
    ("a.b//", false),
    (".", false),
    ("/.", true),
    ("/..", true),
    ("/.a", true),
    ("/.a/", true),
    ("C:\\.a", true),
    ("C:\\a.", true),
    ("C:\\a.b\\", true),
    ("a\u{9}b/c\u{a}d", false),
    ("/home/user/proj/src/index.ts", true),
    ("C:\\Users\\me\\proj\\src\\index.ts", true),
    ("D:", false),
    ("D:x", false),
    ("d:\\", true),
    ("C:\\\\a\\\\\\b", true),
];

const WIN32_DIRNAME: &[(&str, &str)] = &[
    ("", "."),
    (".", "."),
    ("..", "."),
    ("/", "/"),
    ("//", "/"),
    ("///", "/"),
    ("a", "."),
    ("a/", "."),
    ("a//", "."),
    ("/a", "/"),
    ("/a/", "/"),
    ("a/b", "a"),
    ("/a/b/c", "/a/b"),
    ("/a/b/c/", "/a/b"),
    ("a/./b", "a/."),
    ("a/../b", "a/.."),
    ("../a", ".."),
    ("../../a/b", "../../a"),
    ("/../a", "/.."),
    ("/a/../../b", "/a/../.."),
    ("./", "."),
    ("./a", "."),
    ("a/b/../../..", "a/b/../.."),
    ("a/b/../../../c", "a/b/../../.."),
    (".a", "."),
    ("a.", "."),
    (".a.b", "."),
    ("a..b", "."),
    ("file.txt", "."),
    ("/dir/file.tar.gz", "/dir"),
    ("dir/.hidden", "dir"),
    ("/foo/bar/baz/asdf/quux.html", "/foo/bar/baz/asdf"),
    ("...", "."),
    ("..a", "."),
    ("a/...", "a"),
    ("/a/b/.", "/a/b"),
    ("/a/b/..", "/a/b"),
    ("a/b/./", "a/b"),
    (".//a//b//", ".//a/"),
    ("//a", "/"),
    ("//a/b", "//a/b"),
    ("C:", "C:"),
    ("C:\\", "C:\\"),
    ("C:/", "C:/"),
    ("C:\\a\\b", "C:\\a"),
    ("C:a", "C:"),
    ("C:a\\b", "C:a"),
    ("c:/a/../b", "c:/a/.."),
    ("C:\\..\\..", "C:\\.."),
    ("C:..", "C:"),
    ("\\\\server\\share", "\\\\server\\share"),
    ("\\\\server\\share\\", "\\\\server\\share\\"),
    ("\\\\server\\share\\a\\b", "\\\\server\\share\\a"),
    ("//server/share/a", "//server/share/"),
    ("\\\\server", "\\"),
    ("\\\\server\\", "\\"),
    ("\\\\?\\C:\\a", "\\\\?\\C:\\"),
    ("\\\\?\\UNC\\srv\\shr\\x", "\\\\?\\UNC\\srv\\shr"),
    ("\\\\.\\pipe\\x", "\\\\.\\pipe\\"),
    ("\\a\\b", "\\a"),
    ("a\\b", "a"),
    ("a\\b\\..\\c", "a\\b\\.."),
    ("\\", "\\"),
    ("\\\\", "\\"),
    ("\\\\\\", "\\"),
    ("\\\\\\a", "\\\\"),
    ("a/b\\c", "a/b"),
    ("file:stream", "."),
    ("COM1", "."),
    ("C:\\x\\COM1", "C:\\x"),
    ("C:\\x\\CON.txt", "C:\\x"),
    ("con", "."),
    ("aux:", "."),
    ("x/nul", "x"),
    ("LPT1:", "."),
    ("COM¹", "."),
    ("unicode/é/日本.txt", "unicode/é"),
    ("😀/x.y", "😀"),
    ("a b/c d.e f", "a b"),
    ("/a/b.c.d", "/a"),
    ("a.b/", "."),
    ("a.b//", "."),
    (".", "."),
    ("/.", "/"),
    ("/..", "/"),
    ("/.a", "/"),
    ("/.a/", "/"),
    ("C:\\.a", "C:\\"),
    ("C:\\a.", "C:\\"),
    ("C:\\a.b\\", "C:\\"),
    ("a\u{9}b/c\u{a}d", "a\u{9}b"),
    ("/home/user/proj/src/index.ts", "/home/user/proj/src"),
    ("C:\\Users\\me\\proj\\src\\index.ts", "C:\\Users\\me\\proj\\src"),
    ("D:", "D:"),
    ("D:x", "D:"),
    ("d:\\", "d:\\"),
    ("C:\\\\a\\\\\\b", "C:\\\\a\\\\"),
];

const WIN32_EXTNAME: &[(&str, &str)] = &[
    ("", ""),
    (".", ""),
    ("..", ""),
    ("/", ""),
    ("//", ""),
    ("///", ""),
    ("a", ""),
    ("a/", ""),
    ("a//", ""),
    ("/a", ""),
    ("/a/", ""),
    ("a/b", ""),
    ("/a/b/c", ""),
    ("/a/b/c/", ""),
    ("a/./b", ""),
    ("a/../b", ""),
    ("../a", ""),
    ("../../a/b", ""),
    ("/../a", ""),
    ("/a/../../b", ""),
    ("./", ""),
    ("./a", ""),
    ("a/b/../../..", ""),
    ("a/b/../../../c", ""),
    (".a", ""),
    ("a.", "."),
    (".a.b", ".b"),
    ("a..b", ".b"),
    ("file.txt", ".txt"),
    ("/dir/file.tar.gz", ".gz"),
    ("dir/.hidden", ""),
    ("/foo/bar/baz/asdf/quux.html", ".html"),
    ("...", "."),
    ("..a", ".a"),
    ("a/...", "."),
    ("/a/b/.", ""),
    ("/a/b/..", ""),
    ("a/b/./", ""),
    (".//a//b//", ""),
    ("//a", ""),
    ("//a/b", ""),
    ("C:", ""),
    ("C:\\", ""),
    ("C:/", ""),
    ("C:\\a\\b", ""),
    ("C:a", ""),
    ("C:a\\b", ""),
    ("c:/a/../b", ""),
    ("C:\\..\\..", ""),
    ("C:..", ""),
    ("\\\\server\\share", ""),
    ("\\\\server\\share\\", ""),
    ("\\\\server\\share\\a\\b", ""),
    ("//server/share/a", ""),
    ("\\\\server", ""),
    ("\\\\server\\", ""),
    ("\\\\?\\C:\\a", ""),
    ("\\\\?\\UNC\\srv\\shr\\x", ""),
    ("\\\\.\\pipe\\x", ""),
    ("\\a\\b", ""),
    ("a\\b", ""),
    ("a\\b\\..\\c", ""),
    ("\\", ""),
    ("\\\\", ""),
    ("\\\\\\", ""),
    ("\\\\\\a", ""),
    ("a/b\\c", ""),
    ("file:stream", ""),
    ("COM1", ""),
    ("C:\\x\\COM1", ""),
    ("C:\\x\\CON.txt", ".txt"),
    ("con", ""),
    ("aux:", ""),
    ("x/nul", ""),
    ("LPT1:", ""),
    ("COM¹", ""),
    ("unicode/é/日本.txt", ".txt"),
    ("😀/x.y", ".y"),
    ("a b/c d.e f", ".e f"),
    ("/a/b.c.d", ".d"),
    ("a.b/", ".b"),
    ("a.b//", ".b"),
    (".", ""),
    ("/.", ""),
    ("/..", ""),
    ("/.a", ""),
    ("/.a/", ""),
    ("C:\\.a", ""),
    ("C:\\a.", "."),
    ("C:\\a.b\\", ".b"),
    ("a\u{9}b/c\u{a}d", ""),
    ("/home/user/proj/src/index.ts", ".ts"),
    ("C:\\Users\\me\\proj\\src\\index.ts", ".ts"),
    ("D:", ""),
    ("D:x", ""),
    ("d:\\", ""),
    ("C:\\\\a\\\\\\b", ""),
];

const WIN32_BASENAME: &[(&str, Option<&str>, &str)] = &[
    ("", None, ""),
    (".", None, "."),
    ("..", None, ".."),
    ("/", None, ""),
    ("//", None, ""),
    ("///", None, ""),
    ("a", None, "a"),
    ("a/", None, "a"),
    ("a//", None, "a"),
    ("/a", None, "a"),
    ("/a/", None, "a"),
    ("a/b", None, "b"),
    ("/a/b/c", None, "c"),
    ("/a/b/c/", None, "c"),
    ("a/./b", None, "b"),
    ("a/../b", None, "b"),
    ("../a", None, "a"),
    ("../../a/b", None, "b"),
    ("/../a", None, "a"),
    ("/a/../../b", None, "b"),
    ("./", None, "."),
    ("./a", None, "a"),
    ("a/b/../../..", None, ".."),
    ("a/b/../../../c", None, "c"),
    (".a", None, ".a"),
    ("a.", None, "a."),
    (".a.b", None, ".a.b"),
    ("a..b", None, "a..b"),
    ("file.txt", None, "file.txt"),
    ("/dir/file.tar.gz", None, "file.tar.gz"),
    ("dir/.hidden", None, ".hidden"),
    ("/foo/bar/baz/asdf/quux.html", None, "quux.html"),
    ("...", None, "..."),
    ("..a", None, "..a"),
    ("a/...", None, "..."),
    ("/a/b/.", None, "."),
    ("/a/b/..", None, ".."),
    ("a/b/./", None, "."),
    (".//a//b//", None, "b"),
    ("//a", None, "a"),
    ("//a/b", None, "b"),
    ("C:", None, ""),
    ("C:\\", None, ""),
    ("C:/", None, ""),
    ("C:\\a\\b", None, "b"),
    ("C:a", None, "a"),
    ("C:a\\b", None, "b"),
    ("c:/a/../b", None, "b"),
    ("C:\\..\\..", None, ".."),
    ("C:..", None, ".."),
    ("\\\\server\\share", None, "share"),
    ("\\\\server\\share\\", None, "share"),
    ("\\\\server\\share\\a\\b", None, "b"),
    ("//server/share/a", None, "a"),
    ("\\\\server", None, "server"),
    ("\\\\server\\", None, "server"),
    ("\\\\?\\C:\\a", None, "a"),
    ("\\\\?\\UNC\\srv\\shr\\x", None, "x"),
    ("\\\\.\\pipe\\x", None, "x"),
    ("\\a\\b", None, "b"),
    ("a\\b", None, "b"),
    ("a\\b\\..\\c", None, "c"),
    ("\\", None, ""),
    ("\\\\", None, ""),
    ("\\\\\\", None, ""),
    ("\\\\\\a", None, "a"),
    ("a/b\\c", None, "c"),
    ("file:stream", None, "file:stream"),
    ("COM1", None, "COM1"),
    ("C:\\x\\COM1", None, "COM1"),
    ("C:\\x\\CON.txt", None, "CON.txt"),
    ("con", None, "con"),
    ("aux:", None, "aux:"),
    ("x/nul", None, "nul"),
    ("LPT1:", None, "LPT1:"),
    ("COM¹", None, "COM¹"),
    ("unicode/é/日本.txt", None, "日本.txt"),
    ("😀/x.y", None, "x.y"),
    ("a b/c d.e f", None, "c d.e f"),
    ("/a/b.c.d", None, "b.c.d"),
    ("a.b/", None, "a.b"),
    ("a.b//", None, "a.b"),
    (".", None, "."),
    ("/.", None, "."),
    ("/..", None, ".."),
    ("/.a", None, ".a"),
    ("/.a/", None, ".a"),
    ("C:\\.a", None, ".a"),
    ("C:\\a.", None, "a."),
    ("C:\\a.b\\", None, "a.b"),
    ("a\u{9}b/c\u{a}d", None, "c\u{a}d"),
    ("/home/user/proj/src/index.ts", None, "index.ts"),
    ("C:\\Users\\me\\proj\\src\\index.ts", None, "index.ts"),
    ("D:", None, ""),
    ("D:x", None, "x"),
    ("d:\\", None, ""),
    ("C:\\\\a\\\\\\b", None, "b"),
    ("/a/b.html", Some(".html"), "b"),
    ("/a/b.html", Some("html"), "b."),
    ("/a/b.html", Some("b.html"), "b.html"),
    ("/a/b.html", Some("b.htmlx"), "b.html"),
    ("aaa/bbb", Some("bbb"), "bbb"),
    ("aaa/bbb", Some("a/bbb"), "bbb"),
    ("aaa/bbb//", Some("bbb"), "bbb"),
    ("aaa/bbb", Some("bb"), "b"),
    ("aaa/bbb", Some("b"), "bb"),
    ("/aaa/bbb", Some("/bbb"), "bbb"),
    ("/aaa/bbb", Some("a/bbb"), "bbb"),
    ("/aaa/bbb", Some("bbb"), "bbb"),
    ("/aaa/bbb//", Some("bbb"), "bbb"),
    ("/aaa/bbb", Some("bb"), "b"),
    ("/aaa/bbb", Some("b"), "bb"),
    ("/aaa/", Some("aaa"), "aaa"),
    ("/aaa/b", Some("b"), "b"),
    ("/a/b", Some("b"), "b"),
    ("//a", Some("a"), "a"),
    ("a", Some("a"), ""),
    ("file", Some(""), "file"),
    (".js", Some(".js"), ""),
    ("js", Some(".js"), "js"),
    ("C:\\a\\b.html", Some(".HTML"), "b.html"),
    ("C:\\a\\B.html", Some("b.html"), "B.html"),
    ("\\aaa\\bbb", Some("bbb"), "bbb"),
    ("C:", Some("C:"), ""),
    ("C:foo.txt", Some(".txt"), "foo"),
    ("x.ÉÉ", Some(".éé"), "x.ÉÉ"),
];

const WIN32_PARSE: &[(&str, [&str; 5])] = &[
    ("", ["", "", "", "", ""]),
    (".", ["", "", ".", "", "."]),
    ("..", ["", "", "..", "", ".."]),
    ("/", ["/", "/", "", "", ""]),
    ("//", ["/", "/", "", "", ""]),
    ("///", ["/", "/", "", "", ""]),
    ("a", ["", "", "a", "", "a"]),
    ("a/", ["", "", "a", "", "a"]),
    ("a//", ["", "", "a", "", "a"]),
    ("/a", ["/", "/", "a", "", "a"]),
    ("/a/", ["/", "/", "a", "", "a"]),
    ("a/b", ["", "a", "b", "", "b"]),
    ("/a/b/c", ["/", "/a/b", "c", "", "c"]),
    ("/a/b/c/", ["/", "/a/b", "c", "", "c"]),
    ("a/./b", ["", "a/.", "b", "", "b"]),
    ("a/../b", ["", "a/..", "b", "", "b"]),
    ("../a", ["", "..", "a", "", "a"]),
    ("../../a/b", ["", "../../a", "b", "", "b"]),
    ("/../a", ["/", "/..", "a", "", "a"]),
    ("/a/../../b", ["/", "/a/../..", "b", "", "b"]),
    ("./", ["", "", ".", "", "."]),
    ("./a", ["", ".", "a", "", "a"]),
    ("a/b/../../..", ["", "a/b/../..", "..", "", ".."]),
    ("a/b/../../../c", ["", "a/b/../../..", "c", "", "c"]),
    (".a", ["", "", ".a", "", ".a"]),
    ("a.", ["", "", "a.", ".", "a"]),
    (".a.b", ["", "", ".a.b", ".b", ".a"]),
    ("a..b", ["", "", "a..b", ".b", "a."]),
    ("file.txt", ["", "", "file.txt", ".txt", "file"]),
    ("/dir/file.tar.gz", ["/", "/dir", "file.tar.gz", ".gz", "file.tar"]),
    ("dir/.hidden", ["", "dir", ".hidden", "", ".hidden"]),
    (
        "/foo/bar/baz/asdf/quux.html",
        ["/", "/foo/bar/baz/asdf", "quux.html", ".html", "quux"],
    ),
    ("...", ["", "", "...", ".", ".."]),
    ("..a", ["", "", "..a", ".a", "."]),
    ("a/...", ["", "a", "...", ".", ".."]),
    ("/a/b/.", ["/", "/a/b", ".", "", "."]),
    ("/a/b/..", ["/", "/a/b", "..", "", ".."]),
    ("a/b/./", ["", "a/b", ".", "", "."]),
    (".//a//b//", ["", ".//a/", "b", "", "b"]),
    ("//a", ["/", "/", "a", "", "a"]),
    ("//a/b", ["//a/b", "//a/b", "", "", ""]),
    ("C:", ["C:", "C:", "", "", ""]),
    ("C:\\", ["C:\\", "C:\\", "", "", ""]),
    ("C:/", ["C:/", "C:/", "", "", ""]),
    ("C:\\a\\b", ["C:\\", "C:\\a", "b", "", "b"]),
    ("C:a", ["C:", "C:", "a", "", "a"]),
    ("C:a\\b", ["C:", "C:a", "b", "", "b"]),
    ("c:/a/../b", ["c:/", "c:/a/..", "b", "", "b"]),
    ("C:\\..\\..", ["C:\\", "C:\\..", "..", "", ".."]),
    ("C:..", ["C:", "C:", "..", "", ".."]),
    (
        "\\\\server\\share",
        ["\\\\server\\share", "\\\\server\\share", "", "", ""],
    ),
    (
        "\\\\server\\share\\",
        ["\\\\server\\share\\", "\\\\server\\share\\", "", "", ""],
    ),
    (
        "\\\\server\\share\\a\\b",
        ["\\\\server\\share\\", "\\\\server\\share\\a", "b", "", "b"],
    ),
    ("//server/share/a", ["//server/share/", "//server/share/", "a", "", "a"]),
    ("\\\\server", ["\\", "\\", "server", "", "server"]),
    ("\\\\server\\", ["\\", "\\", "server", "", "server"]),
    ("\\\\?\\C:\\a", ["\\\\?\\C:\\", "\\\\?\\C:\\", "a", "", "a"]),
    (
        "\\\\?\\UNC\\srv\\shr\\x",
        ["\\\\?\\UNC\\", "\\\\?\\UNC\\srv\\shr", "x", "", "x"],
    ),
    ("\\\\.\\pipe\\x", ["\\\\.\\pipe\\", "\\\\.\\pipe\\", "x", "", "x"]),
    ("\\a\\b", ["\\", "\\a", "b", "", "b"]),
    ("a\\b", ["", "a", "b", "", "b"]),
    ("a\\b\\..\\c", ["", "a\\b\\..", "c", "", "c"]),
    ("\\", ["\\", "\\", "", "", ""]),
    ("\\\\", ["\\", "\\", "", "", ""]),
    ("\\\\\\", ["\\", "\\", "", "", ""]),
    ("\\\\\\a", ["\\", "\\\\", "a", "", "a"]),
    ("a/b\\c", ["", "a/b", "c", "", "c"]),
    ("file:stream", ["", "", "file:stream", "", "file:stream"]),
    ("COM1", ["", "", "COM1", "", "COM1"]),
    ("C:\\x\\COM1", ["C:\\", "C:\\x", "COM1", "", "COM1"]),
    ("C:\\x\\CON.txt", ["C:\\", "C:\\x", "CON.txt", ".txt", "CON"]),
    ("con", ["", "", "con", "", "con"]),
    ("aux:", ["", "", "aux:", "", "aux:"]),
    ("x/nul", ["", "x", "nul", "", "nul"]),
    ("LPT1:", ["", "", "LPT1:", "", "LPT1:"]),
    ("COM¹", ["", "", "COM¹", "", "COM¹"]),
    ("unicode/é/日本.txt", ["", "unicode/é", "日本.txt", ".txt", "日本"]),
    ("😀/x.y", ["", "😀", "x.y", ".y", "x"]),
    ("a b/c d.e f", ["", "a b", "c d.e f", ".e f", "c d"]),
    ("/a/b.c.d", ["/", "/a", "b.c.d", ".d", "b.c"]),
    ("a.b/", ["", "", "a.b", ".b", "a"]),
    ("a.b//", ["", "", "a.b", ".b", "a"]),
    (".", ["", "", ".", "", "."]),
    ("/.", ["/", "/", ".", "", "."]),
    ("/..", ["/", "/", "..", "", ".."]),
    ("/.a", ["/", "/", ".a", "", ".a"]),
    ("/.a/", ["/", "/", ".a", "", ".a"]),
    ("C:\\.a", ["C:\\", "C:\\", ".a", "", ".a"]),
    ("C:\\a.", ["C:\\", "C:\\", "a.", ".", "a"]),
    ("C:\\a.b\\", ["C:\\", "C:\\", "a.b", ".b", "a"]),
    ("a\u{9}b/c\u{a}d", ["", "a\u{9}b", "c\u{a}d", "", "c\u{a}d"]),
    (
        "/home/user/proj/src/index.ts",
        ["/", "/home/user/proj/src", "index.ts", ".ts", "index"],
    ),
    (
        "C:\\Users\\me\\proj\\src\\index.ts",
        ["C:\\", "C:\\Users\\me\\proj\\src", "index.ts", ".ts", "index"],
    ),
    ("D:", ["D:", "D:", "", "", ""]),
    ("D:x", ["D:", "D:", "x", "", "x"]),
    ("d:\\", ["d:\\", "d:\\", "", "", ""]),
    ("C:\\\\a\\\\\\b", ["C:\\", "C:\\\\a\\\\", "b", "", "b"]),
];

const WIN32_FORMAT: &[([&str; 5], &str)] = &[
    (["/", "/a", "b.c", "", ""], "/a\\b.c"),
    (["/", "", "", ".c", "b"], "/b.c"),
    (["", "", "", "c", "b"], "b.c"),
    (["/", "/", "x", "", ""], "/x"),
    (["", "a", "", "", ""], "a\\"),
    (["C:\\", "C:\\a", "b", "", ""], "C:\\a\\b"),
    (["C:\\", "", "", ".txt", "f"], "C:\\f.txt"),
    (["", "", "", "", ""], ""),
    (["", "C:\\", "x", "", ""], "C:\\\\x"),
    (["/", "", ".", "", ""], "/."),
    (["", "", "", "..", "a"], "a.."),
    (["", "x", "", ".", ""], "x\\."),
];

const WIN32_JOIN: &[(&[&str], &str)] = &[
    (&[], "."),
    (&[""], "."),
    (&["", ""], "."),
    (&["a"], "a"),
    (&["a", "b"], "a\\b"),
    (&["/a", "b", "c"], "\\a\\b\\c"),
    (&["a", "/b"], "a\\b"),
    (&["a/", "/b"], "a\\b"),
    (&["a", "", "b"], "a\\b"),
    (&["", "a"], "a"),
    (&["", "/a"], "\\a"),
    (&["/", "a"], "\\a"),
    (&["a", "..", "b"], "b"),
    (&["a", "../..", "b"], "..\\b"),
    (&[".", "."], "."),
    (&["..", "a"], "..\\a"),
    (&["/a", "..", ".."], "\\"),
    (&["a", "b/"], "a\\b\\"),
    (&["a\\", "b"], "a\\b"),
    (&["C:", "a"], "C:\\a"),
    (&["C:\\", "a"], "C:\\a"),
    (&["C:", "\\a"], "C:\\a"),
    (&["\\\\server", "share"], "\\\\server\\share\\"),
    (&["//server", "share"], "\\\\server\\share\\"),
    (&["\\\\", "server", "share"], "\\server\\share"),
    (&["//", "server/share"], "\\server\\share"),
    (&["\\\\server\\share", "a"], "\\\\server\\share\\a"),
    (&["\\", "\\server", "share"], "\\server\\share"),
    (&["", "", "/"], "\\"),
    (&["", ".", "a"], "a"),
    (&["/a/b", "./c", "../d"], "\\a\\b\\d"),
    (&["é", "日本"], "é\\日本"),
    (&["a", "COM1"], "a\\COM1"),
    (&["C:", "COM1"], "C:\\COM1"),
    (&["x", "C:"], ".\\x\\C:"),
    (&["./", "C:a"], ".\\C:a"),
    (&["\\\\?\\C:", "a"], "\\\\?\\C:\\a"),
    (&["a/", ""], "a\\"),
    (&["/", "/"], "\\"),
    (&["//", "/a"], "\\a"),
];

const WIN32_RESOLVE_PCWD: &[(&[&str], &str)] = &[
    (&[], "\\home\\user\\proj"),
    (&[""], "\\home\\user\\proj"),
    (&["."], "\\home\\user\\proj"),
    (&["a"], "\\home\\user\\proj\\a"),
    (&["/a"], "\\a"),
    (&["a", "b"], "\\home\\user\\proj\\a\\b"),
    (&["/a", "b"], "\\a\\b"),
    (&["/a", "/b"], "\\b"),
    (&["a", "/b", "c"], "\\b\\c"),
    (&["/a/b", "../c"], "\\a\\c"),
    (&["/a/b", "../../.."], "\\"),
    (&[".."], "\\home\\user"),
    (&["../..", "x"], "\\home\\x"),
    (&["", ""], "\\home\\user\\proj"),
    (&["/", ""], "\\"),
    (&["a/", "b/"], "\\home\\user\\proj\\a\\b"),
    (&["/foo/bar", "./baz"], "\\foo\\bar\\baz"),
    (&["/foo/bar", "/tmp/file/"], "\\tmp\\file"),
    (
        &["wwwroot", "static_files/png/", "../gif/image.gif"],
        "\\home\\user\\proj\\wwwroot\\static_files\\gif\\image.gif",
    ),
    (&["C:\\a", "b"], "C:\\a\\b"),
    (&["C:a", "b"], "C:\\home\\user\\proj\\a\\b"),
    (&["C:"], "C:\\home\\user\\proj"),
    (&["D:"], "D:\\home\\user\\proj"),
    (&["D:x"], "D:\\home\\user\\proj\\x"),
    (&["d:x", "..\\y"], "d:\\home\\user\\proj\\y"),
    (&["c:/ignore", "d:\\a/b\\c/d", "\\e.exe"], "d:\\e.exe"),
    (&["c:/ignore", "c:/some/file"], "c:\\some\\file"),
    (&["d:/ignore", "d:some/dir//"], "d:\\ignore\\some\\dir"),
    (&["//server/share", "..", "relative\\"], "\\\\server\\share\\relative"),
    (&["c:/", "//"], "c:\\"),
    (&["c:/", "//dir"], "c:\\dir"),
    (&["c:/", "//server/share"], "\\\\server\\share\\"),
    (&["c:/", "//server//share"], "\\\\server\\share\\"),
    (&["c:/", "///some//dir"], "c:\\some\\dir"),
    (&["\\\\server\\share", "x"], "\\\\server\\share\\x"),
    (&["\\\\?\\C:\\a", "b"], "\\\\?\\C:\\a\\b"),
    (
        &["C:\\foo\\tmp.3\\", "..\\tmp.3\\cycles\\root.js"],
        "C:\\foo\\tmp.3\\cycles\\root.js",
    ),
    (&["\\a", "b"], "\\a\\b"),
    (&["a\\b", "c"], "\\home\\user\\proj\\a\\b\\c"),
    (&["C:", "\\x"], "C:\\x"),
    (&["C:\\x", "D:"], "D:\\home\\user\\proj"),
    (&["/a", "C:"], "C:\\a"),
    (&["COM1"], "\\home\\user\\proj\\COM1"),
    (&["x", "COM1"], "\\home\\user\\proj\\x\\COM1"),
    (&["E:x"], "E:\\home\\user\\proj\\x"),
    (&["e:", "y"], "e:\\home\\user\\proj\\y"),
    (&["D:\\a", "D:b"], "D:\\a\\b"),
];

const WIN32_RELATIVE_PCWD: &[(&str, &str, &str)] = &[
    ("", "", ""),
    ("/", "/", ""),
    ("/a", "/a", ""),
    ("/a", "/b", "\\b"),
    ("/a/b", "/a", ".."),
    ("/a", "/a/b", "b"),
    ("/a/b/c", "/a/x/y", "..\\..\\x\\y"),
    ("/var/lib", "/var", ".."),
    ("/var/lib", "/bin", "\\bin"),
    ("/var/lib", "/var/lib", ""),
    ("/var/lib", "/var/apache", "..\\apache"),
    ("/var/", "/var/lib", "lib"),
    ("/", "/var/lib", "var\\lib"),
    ("/foo/test", "/foo/test/bar/package.json", "bar\\package.json"),
    ("/Users/a/web/b/test/mails", "/Users/a/web/b", "..\\.."),
    ("/foo/bar/baz-quux", "/foo/bar/baz", "..\\baz"),
    ("/foo/bar/baz", "/foo/bar/baz-quux", "..\\baz-quux"),
    ("/baz-quux", "/baz", "..baz"),
    ("/baz", "/baz-quux", "..baz-quux"),
    ("/page1/page2/foo", "/", "..\\..\\.."),
    ("a", "b", "..\\b"),
    ("a/b", "a", ".."),
    ("", "/x", "\\x"),
    ("/x", "", "\\home\\user\\proj"),
    ("c:/blah\\blah", "d:/games", "d:\\games"),
    ("c:/aaaa/bbbb", "c:/aaaa", ".."),
    ("c:/aaaa/bbbb", "c:/cccc", "..\\..\\cccc"),
    ("c:/aaaa/bbbb", "c:/aaaa/bbbb", ""),
    ("c:/aaaa/bbbb", "c:/aaaa/cccc", "..\\cccc"),
    ("c:/aaaa/", "c:/aaaa/cccc", "cccc"),
    ("c:/", "c:\\aaaa\\bbbb", "aaaa\\bbbb"),
    ("c:/aaaa/bbbb", "d:\\", "d:\\"),
    ("c:/AaAa/bbbb", "c:/aaaa/bbbb", ""),
    ("c:/aaaaa/", "c:/aaaa/cccc", "..\\aaaa\\cccc"),
    ("C:\\foo\\bar\\baz\\quux", "C:\\", "..\\..\\..\\.."),
    ("C:\\foo\\test", "C:\\foo\\test\\bar\\package.json", "bar\\package.json"),
    ("C:\\foo\\bar\\baz-quux", "C:\\foo\\bar\\baz", "..\\baz"),
    ("C:\\foo\\bar\\baz", "C:\\foo\\bar\\baz-quux", "..\\baz-quux"),
    ("\\\\foo\\bar", "\\\\foo\\bar\\baz", "baz"),
    ("\\\\foo\\bar\\baz", "\\\\foo\\bar", ".."),
    ("\\\\foo\\bar\\baz-quux", "\\\\foo\\bar\\baz", "..\\baz"),
    ("\\\\foo\\bar\\baz", "\\\\foo\\bar\\baz-quux", "..\\baz-quux"),
    ("C:\\baz-quux", "C:\\baz", "..\\baz"),
    ("C:\\baz", "C:\\baz-quux", "..\\baz-quux"),
    ("\\\\foo\\baz-quux", "\\\\foo\\baz", "..\\baz"),
    ("\\\\foo\\baz", "\\\\foo\\baz-quux", "..\\baz-quux"),
    ("C:\\baz", "\\\\foo\\bar\\baz", "\\\\foo\\bar\\baz"),
    ("\\\\foo\\bar\\baz", "C:\\baz", "C:\\baz"),
    ("C:\\Ä", "C:\\ä\\x", "x"),
    ("C:\\ǅ", "C:\\ǆ", ""),
    ("a", "C:\\b", "C:\\b"),
    ("x\\y", "x\\z", "..\\z"),
];

const WIN32_NAMESPACED_PCWD: &[(&str, &str)] = &[
    ("", ""),
    (".", "\\home\\user\\proj"),
    ("..", "\\home\\user"),
    ("/", "/"),
    ("//", "//"),
    ("///", "///"),
    ("a", "\\home\\user\\proj\\a"),
    ("a/", "\\home\\user\\proj\\a"),
    ("a//", "\\home\\user\\proj\\a"),
    ("/a", "/a"),
    ("/a/", "/a/"),
    ("a/b", "\\home\\user\\proj\\a\\b"),
    ("/a/b/c", "\\a\\b\\c"),
    ("/a/b/c/", "\\a\\b\\c"),
    ("a/./b", "\\home\\user\\proj\\a\\b"),
    ("a/../b", "\\home\\user\\proj\\b"),
    ("../a", "\\home\\user\\a"),
    ("../../a/b", "\\home\\a\\b"),
    ("/../a", "/../a"),
    ("/a/../../b", "/a/../../b"),
    ("./", "\\home\\user\\proj"),
    ("./a", "\\home\\user\\proj\\a"),
    ("a/b/../../..", "\\home\\user"),
    ("a/b/../../../c", "\\home\\user\\c"),
    (".a", "\\home\\user\\proj\\.a"),
    ("a.", "\\home\\user\\proj\\a."),
    (".a.b", "\\home\\user\\proj\\.a.b"),
    ("a..b", "\\home\\user\\proj\\a..b"),
    ("file.txt", "\\home\\user\\proj\\file.txt"),
    ("/dir/file.tar.gz", "\\dir\\file.tar.gz"),
    ("dir/.hidden", "\\home\\user\\proj\\dir\\.hidden"),
    ("/foo/bar/baz/asdf/quux.html", "\\foo\\bar\\baz\\asdf\\quux.html"),
    ("...", "\\home\\user\\proj\\..."),
    ("..a", "\\home\\user\\proj\\..a"),
    ("a/...", "\\home\\user\\proj\\a\\..."),
    ("/a/b/.", "\\a\\b"),
    ("/a/b/..", "/a/b/.."),
    ("a/b/./", "\\home\\user\\proj\\a\\b"),
    (".//a//b//", "\\home\\user\\proj\\a\\b"),
    ("//a", "//a"),
    ("//a/b", "\\\\?\\UNC\\a\\b\\"),
    ("C:", "\\\\?\\C:\\home\\user\\proj"),
    ("C:\\", "\\\\?\\C:\\"),
    ("C:/", "\\\\?\\C:\\"),
    ("C:\\a\\b", "\\\\?\\C:\\a\\b"),
    ("C:a", "\\\\?\\C:\\home\\user\\proj\\a"),
    ("C:a\\b", "\\\\?\\C:\\home\\user\\proj\\a\\b"),
    ("c:/a/../b", "\\\\?\\c:\\b"),
    ("C:\\..\\..", "\\\\?\\C:\\"),
    ("C:..", "\\\\?\\C:\\home\\user"),
    ("\\\\server\\share", "\\\\?\\UNC\\server\\share\\"),
    ("\\\\server\\share\\", "\\\\?\\UNC\\server\\share\\"),
    ("\\\\server\\share\\a\\b", "\\\\?\\UNC\\server\\share\\a\\b"),
    ("//server/share/a", "\\\\?\\UNC\\server\\share\\a"),
    ("\\\\server", "\\server"),
    ("\\\\server\\", "\\server"),
    ("\\\\?\\C:\\a", "\\\\?\\C:\\a"),
    ("\\\\?\\UNC\\srv\\shr\\x", "\\\\?\\UNC\\srv\\shr\\x"),
    ("\\\\.\\pipe\\x", "\\\\.\\pipe\\x"),
    ("\\a\\b", "\\a\\b"),
    ("a\\b", "\\home\\user\\proj\\a\\b"),
    ("a\\b\\..\\c", "\\home\\user\\proj\\a\\c"),
    ("\\", "\\"),
    ("\\\\", "\\\\"),
    ("\\\\\\", "\\\\\\"),
    ("\\\\\\a", "\\\\\\a"),
    ("a/b\\c", "\\home\\user\\proj\\a\\b\\c"),
    ("file:stream", "\\home\\user\\proj\\file:stream"),
    ("COM1", "\\home\\user\\proj\\COM1"),
    ("C:\\x\\COM1", "\\\\?\\C:\\x\\COM1"),
    ("C:\\x\\CON.txt", "\\\\?\\C:\\x\\CON.txt"),
    ("con", "\\home\\user\\proj\\con"),
    ("aux:", "\\home\\user\\proj\\aux:"),
    ("x/nul", "\\home\\user\\proj\\x\\nul"),
    ("LPT1:", "\\home\\user\\proj\\LPT1:"),
    ("COM¹", "\\home\\user\\proj\\COM¹"),
    ("unicode/é/日本.txt", "\\home\\user\\proj\\unicode\\é\\日本.txt"),
    ("😀/x.y", "\\home\\user\\proj\\😀\\x.y"),
    ("a b/c d.e f", "\\home\\user\\proj\\a b\\c d.e f"),
    ("/a/b.c.d", "\\a\\b.c.d"),
    ("a.b/", "\\home\\user\\proj\\a.b"),
    ("a.b//", "\\home\\user\\proj\\a.b"),
    (".", "\\home\\user\\proj"),
    ("/.", "/."),
    ("/..", "/.."),
    ("/.a", "\\.a"),
    ("/.a/", "\\.a"),
    ("C:\\.a", "\\\\?\\C:\\.a"),
    ("C:\\a.", "\\\\?\\C:\\a."),
    ("C:\\a.b\\", "\\\\?\\C:\\a.b"),
    ("a\u{9}b/c\u{a}d", "\\home\\user\\proj\\a\u{9}b\\c\u{a}d"),
    ("/home/user/proj/src/index.ts", "\\home\\user\\proj\\src\\index.ts"),
    (
        "C:\\Users\\me\\proj\\src\\index.ts",
        "\\\\?\\C:\\Users\\me\\proj\\src\\index.ts",
    ),
    ("D:", "\\\\?\\D:\\home\\user\\proj"),
    ("D:x", "\\\\?\\D:\\home\\user\\proj\\x"),
    ("d:\\", "\\\\?\\d:\\"),
    ("C:\\\\a\\\\\\b", "\\\\?\\C:\\a\\b"),
];

const WIN32_RESOLVE_WCWD: &[(&[&str], &str)] = &[
    (&[], "C:\\Users\\me\\proj"),
    (&[""], "C:\\Users\\me\\proj"),
    (&["."], "C:\\Users\\me\\proj"),
    (&["a"], "C:\\Users\\me\\proj\\a"),
    (&["/a"], "C:\\a"),
    (&["a", "b"], "C:\\Users\\me\\proj\\a\\b"),
    (&["/a", "b"], "C:\\a\\b"),
    (&["/a", "/b"], "C:\\b"),
    (&["a", "/b", "c"], "C:\\b\\c"),
    (&["/a/b", "../c"], "C:\\a\\c"),
    (&["/a/b", "../../.."], "C:\\"),
    (&[".."], "C:\\Users\\me"),
    (&["../..", "x"], "C:\\Users\\x"),
    (&["", ""], "C:\\Users\\me\\proj"),
    (&["/", ""], "C:\\"),
    (&["a/", "b/"], "C:\\Users\\me\\proj\\a\\b"),
    (&["/foo/bar", "./baz"], "C:\\foo\\bar\\baz"),
    (&["/foo/bar", "/tmp/file/"], "C:\\tmp\\file"),
    (
        &["wwwroot", "static_files/png/", "../gif/image.gif"],
        "C:\\Users\\me\\proj\\wwwroot\\static_files\\gif\\image.gif",
    ),
    (&["C:\\a", "b"], "C:\\a\\b"),
    (&["C:a", "b"], "C:\\Users\\me\\proj\\a\\b"),
    (&["C:"], "C:\\Users\\me\\proj"),
    (&["D:"], "D:\\dcwd"),
    (&["D:x"], "D:\\dcwd\\x"),
    (&["d:x", "..\\y"], "d:\\y"),
    (&["c:/ignore", "d:\\a/b\\c/d", "\\e.exe"], "d:\\e.exe"),
    (&["c:/ignore", "c:/some/file"], "c:\\some\\file"),
    (&["d:/ignore", "d:some/dir//"], "d:\\ignore\\some\\dir"),
    (&["//server/share", "..", "relative\\"], "\\\\server\\share\\relative"),
    (&["c:/", "//"], "c:\\"),
    (&["c:/", "//dir"], "c:\\dir"),
    (&["c:/", "//server/share"], "\\\\server\\share\\"),
    (&["c:/", "//server//share"], "\\\\server\\share\\"),
    (&["c:/", "///some//dir"], "c:\\some\\dir"),
    (&["\\\\server\\share", "x"], "\\\\server\\share\\x"),
    (&["\\\\?\\C:\\a", "b"], "\\\\?\\C:\\a\\b"),
    (
        &["C:\\foo\\tmp.3\\", "..\\tmp.3\\cycles\\root.js"],
        "C:\\foo\\tmp.3\\cycles\\root.js",
    ),
    (&["\\a", "b"], "C:\\a\\b"),
    (&["a\\b", "c"], "C:\\Users\\me\\proj\\a\\b\\c"),
    (&["C:", "\\x"], "C:\\x"),
    (&["C:\\x", "D:"], "D:\\dcwd"),
    (&["/a", "C:"], "C:\\a"),
    (&["COM1"], "C:\\Users\\me\\proj\\COM1"),
    (&["x", "COM1"], "C:\\Users\\me\\proj\\x\\COM1"),
    (&["E:x"], "E:\\x"),
    (&["e:", "y"], "e:\\y"),
    (&["D:\\a", "D:b"], "D:\\a\\b"),
];

const WIN32_RELATIVE_WCWD: &[(&str, &str, &str)] = &[
    ("", "", ""),
    ("/", "/", ""),
    ("/a", "/a", ""),
    ("/a", "/b", "..\\b"),
    ("/a/b", "/a", ".."),
    ("/a", "/a/b", "b"),
    ("/a/b/c", "/a/x/y", "..\\..\\x\\y"),
    ("/var/lib", "/var", ".."),
    ("/var/lib", "/bin", "..\\..\\bin"),
    ("/var/lib", "/var/lib", ""),
    ("/var/lib", "/var/apache", "..\\apache"),
    ("/var/", "/var/lib", "lib"),
    ("/", "/var/lib", "var\\lib"),
    ("/foo/test", "/foo/test/bar/package.json", "bar\\package.json"),
    ("/Users/a/web/b/test/mails", "/Users/a/web/b", "..\\.."),
    ("/foo/bar/baz-quux", "/foo/bar/baz", "..\\baz"),
    ("/foo/bar/baz", "/foo/bar/baz-quux", "..\\baz-quux"),
    ("/baz-quux", "/baz", "..\\baz"),
    ("/baz", "/baz-quux", "..\\baz-quux"),
    ("/page1/page2/foo", "/", "..\\..\\.."),
    ("a", "b", "..\\b"),
    ("a/b", "a", ".."),
    ("", "/x", "..\\..\\..\\x"),
    ("/x", "", "..\\Users\\me\\proj"),
    ("c:/blah\\blah", "d:/games", "d:\\games"),
    ("c:/aaaa/bbbb", "c:/aaaa", ".."),
    ("c:/aaaa/bbbb", "c:/cccc", "..\\..\\cccc"),
    ("c:/aaaa/bbbb", "c:/aaaa/bbbb", ""),
    ("c:/aaaa/bbbb", "c:/aaaa/cccc", "..\\cccc"),
    ("c:/aaaa/", "c:/aaaa/cccc", "cccc"),
    ("c:/", "c:\\aaaa\\bbbb", "aaaa\\bbbb"),
    ("c:/aaaa/bbbb", "d:\\", "d:\\"),
    ("c:/AaAa/bbbb", "c:/aaaa/bbbb", ""),
    ("c:/aaaaa/", "c:/aaaa/cccc", "..\\aaaa\\cccc"),
    ("C:\\foo\\bar\\baz\\quux", "C:\\", "..\\..\\..\\.."),
    ("C:\\foo\\test", "C:\\foo\\test\\bar\\package.json", "bar\\package.json"),
    ("C:\\foo\\bar\\baz-quux", "C:\\foo\\bar\\baz", "..\\baz"),
    ("C:\\foo\\bar\\baz", "C:\\foo\\bar\\baz-quux", "..\\baz-quux"),
    ("\\\\foo\\bar", "\\\\foo\\bar\\baz", "baz"),
    ("\\\\foo\\bar\\baz", "\\\\foo\\bar", ".."),
    ("\\\\foo\\bar\\baz-quux", "\\\\foo\\bar\\baz", "..\\baz"),
    ("\\\\foo\\bar\\baz", "\\\\foo\\bar\\baz-quux", "..\\baz-quux"),
    ("C:\\baz-quux", "C:\\baz", "..\\baz"),
    ("C:\\baz", "C:\\baz-quux", "..\\baz-quux"),
    ("\\\\foo\\baz-quux", "\\\\foo\\baz", "..\\baz"),
    ("\\\\foo\\baz", "\\\\foo\\baz-quux", "..\\baz-quux"),
    ("C:\\baz", "\\\\foo\\bar\\baz", "\\\\foo\\bar\\baz"),
    ("\\\\foo\\bar\\baz", "C:\\baz", "C:\\baz"),
    ("C:\\Ä", "C:\\ä\\x", "x"),
    ("C:\\ǅ", "C:\\ǆ", ""),
    ("a", "C:\\b", "..\\..\\..\\..\\b"),
    ("x\\y", "x\\z", "..\\z"),
];

const WIN32_NAMESPACED_WCWD: &[(&str, &str)] = &[
    ("", ""),
    (".", "\\\\?\\C:\\Users\\me\\proj"),
    ("..", "\\\\?\\C:\\Users\\me"),
    ("/", "\\\\?\\C:\\"),
    ("//", "\\\\?\\C:\\"),
    ("///", "\\\\?\\C:\\"),
    ("a", "\\\\?\\C:\\Users\\me\\proj\\a"),
    ("a/", "\\\\?\\C:\\Users\\me\\proj\\a"),
    ("a//", "\\\\?\\C:\\Users\\me\\proj\\a"),
    ("/a", "\\\\?\\C:\\a"),
    ("/a/", "\\\\?\\C:\\a"),
    ("a/b", "\\\\?\\C:\\Users\\me\\proj\\a\\b"),
    ("/a/b/c", "\\\\?\\C:\\a\\b\\c"),
    ("/a/b/c/", "\\\\?\\C:\\a\\b\\c"),
    ("a/./b", "\\\\?\\C:\\Users\\me\\proj\\a\\b"),
    ("a/../b", "\\\\?\\C:\\Users\\me\\proj\\b"),
    ("../a", "\\\\?\\C:\\Users\\me\\a"),
    ("../../a/b", "\\\\?\\C:\\Users\\a\\b"),
    ("/../a", "\\\\?\\C:\\a"),
    ("/a/../../b", "\\\\?\\C:\\b"),
    ("./", "\\\\?\\C:\\Users\\me\\proj"),
    ("./a", "\\\\?\\C:\\Users\\me\\proj\\a"),
    ("a/b/../../..", "\\\\?\\C:\\Users\\me"),
    ("a/b/../../../c", "\\\\?\\C:\\Users\\me\\c"),
    (".a", "\\\\?\\C:\\Users\\me\\proj\\.a"),
    ("a.", "\\\\?\\C:\\Users\\me\\proj\\a."),
    (".a.b", "\\\\?\\C:\\Users\\me\\proj\\.a.b"),
    ("a..b", "\\\\?\\C:\\Users\\me\\proj\\a..b"),
    ("file.txt", "\\\\?\\C:\\Users\\me\\proj\\file.txt"),
    ("/dir/file.tar.gz", "\\\\?\\C:\\dir\\file.tar.gz"),
    ("dir/.hidden", "\\\\?\\C:\\Users\\me\\proj\\dir\\.hidden"),
    (
        "/foo/bar/baz/asdf/quux.html",
        "\\\\?\\C:\\foo\\bar\\baz\\asdf\\quux.html",
    ),
    ("...", "\\\\?\\C:\\Users\\me\\proj\\..."),
    ("..a", "\\\\?\\C:\\Users\\me\\proj\\..a"),
    ("a/...", "\\\\?\\C:\\Users\\me\\proj\\a\\..."),
    ("/a/b/.", "\\\\?\\C:\\a\\b"),
    ("/a/b/..", "\\\\?\\C:\\a"),
    ("a/b/./", "\\\\?\\C:\\Users\\me\\proj\\a\\b"),
    (".//a//b//", "\\\\?\\C:\\Users\\me\\proj\\a\\b"),
    ("//a", "\\\\?\\C:\\a"),
    ("//a/b", "\\\\?\\UNC\\a\\b\\"),
    ("C:", "\\\\?\\C:\\Users\\me\\proj"),
    ("C:\\", "\\\\?\\C:\\"),
    ("C:/", "\\\\?\\C:\\"),
    ("C:\\a\\b", "\\\\?\\C:\\a\\b"),
    ("C:a", "\\\\?\\C:\\Users\\me\\proj\\a"),
    ("C:a\\b", "\\\\?\\C:\\Users\\me\\proj\\a\\b"),
    ("c:/a/../b", "\\\\?\\c:\\b"),
    ("C:\\..\\..", "\\\\?\\C:\\"),
    ("C:..", "\\\\?\\C:\\Users\\me"),
    ("\\\\server\\share", "\\\\?\\UNC\\server\\share\\"),
    ("\\\\server\\share\\", "\\\\?\\UNC\\server\\share\\"),
    ("\\\\server\\share\\a\\b", "\\\\?\\UNC\\server\\share\\a\\b"),
    ("//server/share/a", "\\\\?\\UNC\\server\\share\\a"),
    ("\\\\server", "\\\\?\\C:\\server"),
    ("\\\\server\\", "\\\\?\\C:\\server"),
    ("\\\\?\\C:\\a", "\\\\?\\C:\\a"),
    ("\\\\?\\UNC\\srv\\shr\\x", "\\\\?\\UNC\\srv\\shr\\x"),
    ("\\\\.\\pipe\\x", "\\\\.\\pipe\\x"),
    ("\\a\\b", "\\\\?\\C:\\a\\b"),
    ("a\\b", "\\\\?\\C:\\Users\\me\\proj\\a\\b"),
    ("a\\b\\..\\c", "\\\\?\\C:\\Users\\me\\proj\\a\\c"),
    ("\\", "\\\\?\\C:\\"),
    ("\\\\", "\\\\?\\C:\\"),
    ("\\\\\\", "\\\\?\\C:\\"),
    ("\\\\\\a", "\\\\?\\C:\\a"),
    ("a/b\\c", "\\\\?\\C:\\Users\\me\\proj\\a\\b\\c"),
    ("file:stream", "\\\\?\\C:\\Users\\me\\proj\\file:stream"),
    ("COM1", "\\\\?\\C:\\Users\\me\\proj\\COM1"),
    ("C:\\x\\COM1", "\\\\?\\C:\\x\\COM1"),
    ("C:\\x\\CON.txt", "\\\\?\\C:\\x\\CON.txt"),
    ("con", "\\\\?\\C:\\Users\\me\\proj\\con"),
    ("aux:", "\\\\?\\C:\\Users\\me\\proj\\aux:"),
    ("x/nul", "\\\\?\\C:\\Users\\me\\proj\\x\\nul"),
    ("LPT1:", "\\\\?\\C:\\Users\\me\\proj\\LPT1:"),
    ("COM¹", "\\\\?\\C:\\Users\\me\\proj\\COM¹"),
    ("unicode/é/日本.txt", "\\\\?\\C:\\Users\\me\\proj\\unicode\\é\\日本.txt"),
    ("😀/x.y", "\\\\?\\C:\\Users\\me\\proj\\😀\\x.y"),
    ("a b/c d.e f", "\\\\?\\C:\\Users\\me\\proj\\a b\\c d.e f"),
    ("/a/b.c.d", "\\\\?\\C:\\a\\b.c.d"),
    ("a.b/", "\\\\?\\C:\\Users\\me\\proj\\a.b"),
    ("a.b//", "\\\\?\\C:\\Users\\me\\proj\\a.b"),
    (".", "\\\\?\\C:\\Users\\me\\proj"),
    ("/.", "\\\\?\\C:\\"),
    ("/..", "\\\\?\\C:\\"),
    ("/.a", "\\\\?\\C:\\.a"),
    ("/.a/", "\\\\?\\C:\\.a"),
    ("C:\\.a", "\\\\?\\C:\\.a"),
    ("C:\\a.", "\\\\?\\C:\\a."),
    ("C:\\a.b\\", "\\\\?\\C:\\a.b"),
    ("a\u{9}b/c\u{a}d", "\\\\?\\C:\\Users\\me\\proj\\a\u{9}b\\c\u{a}d"),
    (
        "/home/user/proj/src/index.ts",
        "\\\\?\\C:\\home\\user\\proj\\src\\index.ts",
    ),
    (
        "C:\\Users\\me\\proj\\src\\index.ts",
        "\\\\?\\C:\\Users\\me\\proj\\src\\index.ts",
    ),
    ("D:", "\\\\?\\D:\\dcwd"),
    ("D:x", "\\\\?\\D:\\dcwd\\x"),
    ("d:\\", "\\\\?\\d:\\"),
    ("C:\\\\a\\\\\\b", "\\\\?\\C:\\a\\b"),
];
