//! pi_js::regex parity tests. Vectors generated with Node 24 (see the header of `vectors`).

#[allow(clippy::type_complexity)]
mod vectors {
    // Generated by node v24.21.0 (V8 13.6.233.17-node.53) from /tmp/pi-nint/gen-regex.mjs.
    pub const SYNTAX: &[(&str, &str, Option<&str>)] = &[
        ("(", "", Some("Invalid regular expression: /(/: Unterminated group")),
        (")", "", Some("Invalid regular expression: /)/: Unmatched ')'")),
        ("a)", "", Some("Invalid regular expression: /a)/: Unmatched ')'")),
        ("(a", "", Some("Invalid regular expression: /(a/: Unterminated group")),
        (
            "[",
            "",
            Some("Invalid regular expression: /[/: Unterminated character class"),
        ),
        (
            "[a",
            "",
            Some("Invalid regular expression: /[a/: Unterminated character class"),
        ),
        ("\\", "", Some("Invalid regular expression: /\\/: \\ at end of pattern")),
        (
            "a\\",
            "",
            Some("Invalid regular expression: /a\\/: \\ at end of pattern"),
        ),
        ("*", "", Some("Invalid regular expression: /*/: Nothing to repeat")),
        ("+a", "", Some("Invalid regular expression: /+a/: Nothing to repeat")),
        ("?", "", Some("Invalid regular expression: /?/: Nothing to repeat")),
        ("a**", "", Some("Invalid regular expression: /a**/: Nothing to repeat")),
        (
            "a{2,1}",
            "",
            Some("Invalid regular expression: /a{2,1}/: numbers out of order in {} quantifier"),
        ),
        ("{", "", None),
        ("}", "", None),
        ("]", "", None),
        ("a{", "", None),
        ("a{1", "", None),
        ("a{1,", "", None),
        ("{1}", "", Some("Invalid regular expression: /{1}/: Nothing to repeat")),
        (
            "{",
            "u",
            Some("Invalid regular expression: /{/u: Lone quantifier brackets"),
        ),
        (
            "}",
            "u",
            Some("Invalid regular expression: /}/u: Lone quantifier brackets"),
        ),
        (
            "]",
            "u",
            Some("Invalid regular expression: /]/u: Lone quantifier brackets"),
        ),
        (
            "a{1",
            "u",
            Some("Invalid regular expression: /a{1/u: Incomplete quantifier"),
        ),
        (
            "[b-a]",
            "",
            Some("Invalid regular expression: /[b-a]/: Range out of order in character class"),
        ),
        (
            "[z-a]",
            "u",
            Some("Invalid regular expression: /[z-a]/u: Range out of order in character class"),
        ),
        (
            "(?<a>x)(?<a>y)",
            "",
            Some("Invalid regular expression: /(?<a>x)(?<a>y)/: Duplicate capture group name"),
        ),
        (
            "(?<1a>x)",
            "",
            Some("Invalid regular expression: /(?<1a>x)/: Invalid capture group name"),
        ),
        (
            "(?<a",
            "",
            Some("Invalid regular expression: /(?<a/: Invalid capture group name"),
        ),
        (
            "\\k<b>",
            "u",
            Some("Invalid regular expression: /\\k<b>/u: Invalid named capture referenced"),
        ),
        (
            "(?<a>x)\\k<b>",
            "",
            Some("Invalid regular expression: /(?<a>x)\\k<b>/: Invalid named capture referenced"),
        ),
        (
            "\\k<a",
            "u",
            Some("Invalid regular expression: /\\k<a/u: Invalid capture group name"),
        ),
        ("\\k", "", None),
        (
            "\\k",
            "u",
            Some("Invalid regular expression: /\\k/u: Invalid named reference"),
        ),
        (
            "\\p{Foo}",
            "u",
            Some("Invalid regular expression: /\\p{Foo}/u: Invalid property name"),
        ),
        ("\\p{L}", "u", None),
        ("\\p{L}", "", None),
        (
            "\\u{110000}",
            "u",
            Some("Invalid regular expression: /\\u{110000}/u: Invalid Unicode escape"),
        ),
        (
            "\\u{12",
            "u",
            Some("Invalid regular expression: /\\u{12/u: Invalid Unicode escape"),
        ),
        (
            "\\u12",
            "u",
            Some("Invalid regular expression: /\\u12/u: Invalid Unicode escape"),
        ),
        ("\\u12", "", None),
        ("\\x1", "u", Some("Invalid regular expression: /\\x1/u: Invalid escape")),
        ("\\x1", "", None),
        ("\\c", "", None),
        (
            "\\c",
            "u",
            Some("Invalid regular expression: /\\c/u: Invalid Unicode escape"),
        ),
        ("\\q", "u", Some("Invalid regular expression: /\\q/u: Invalid escape")),
        ("\\q", "", None),
        ("\\-", "u", Some("Invalid regular expression: /\\-/u: Invalid escape")),
        ("[\\-]", "u", None),
        ("\\1", "u", Some("Invalid regular expression: /\\1/u: Invalid escape")),
        (
            "(a)\\2",
            "u",
            Some("Invalid regular expression: /(a)\\2/u: Invalid escape"),
        ),
        ("(a)\\2", "", None),
        ("\\8", "", None),
        ("\\8", "u", Some("Invalid regular expression: /\\8/u: Invalid escape")),
        ("\\07", "", None),
        (
            "\\07",
            "u",
            Some("Invalid regular expression: /\\07/u: Invalid decimal escape"),
        ),
        ("[\\d-z]", "", None),
        (
            "[\\d-z]",
            "u",
            Some("Invalid regular expression: /[\\d-z]/u: Invalid character class"),
        ),
        ("(?:", "", Some("Invalid regular expression: /(?:/: Unterminated group")),
        ("(?", "", Some("Invalid regular expression: /(?/: Invalid group")),
        ("(?x)", "", Some("Invalid regular expression: /(?x)/: Invalid group")),
        ("(?i:a)", "", None),
        ("(?-i:a)", "", None),
        (
            "(?ii:a)",
            "",
            Some("Invalid regular expression: /(?ii:a)/: Repeated flag in flag group"),
        ),
        (
            "(?i-i:a)",
            "",
            Some("Invalid regular expression: /(?i-i:a)/: Repeated flag in flag group"),
        ),
        (
            "(?--:a)",
            "",
            Some("Invalid regular expression: /(?--:a)/: Multiple dashes in flag group"),
        ),
        ("(?=a)*", "", None),
        (
            "(?=a)*",
            "u",
            Some("Invalid regular expression: /(?=a)*/u: Invalid quantifier"),
        ),
        (
            "(?<=a)*",
            "",
            Some("Invalid regular expression: /(?<=a)*/: Invalid quantifier"),
        ),
        ("^*", "", Some("Invalid regular expression: /^*/: Nothing to repeat")),
        ("$+", "", Some("Invalid regular expression: /$+/: Nothing to repeat")),
        (
            "\\b*",
            "",
            Some("Invalid regular expression: /\\b*/: Nothing to repeat"),
        ),
        (
            "\\b*",
            "u",
            Some("Invalid regular expression: /\\b*/u: Nothing to repeat"),
        ),
        ("a{99999999999}", "", None),
        (
            "x{1}{2}",
            "",
            Some("Invalid regular expression: /x{1}{2}/: Nothing to repeat"),
        ),
        ("x??", "", None),
        ("x*?", "", None),
        (
            "x+?+",
            "",
            Some("Invalid regular expression: /x+?+/: Nothing to repeat"),
        ),
        (
            "[\\w-a]",
            "u",
            Some("Invalid regular expression: /[\\w-a]/u: Invalid character class"),
        ),
        (
            "[a-\\w]",
            "u",
            Some("Invalid regular expression: /[a-\\w]/u: Invalid character class"),
        ),
        ("[\\p{L}]", "u", None),
        ("[a-\\d]", "", None),
        (
            "\\P",
            "u",
            Some("Invalid regular expression: /\\P/u: Invalid property name"),
        ),
        (
            "\\p",
            "u",
            Some("Invalid regular expression: /\\p/u: Invalid property name"),
        ),
        (
            "\\p{",
            "u",
            Some("Invalid regular expression: /\\p{/u: Invalid property name"),
        ),
        (
            "\\p{L",
            "u",
            Some("Invalid regular expression: /\\p{L/u: Invalid property name"),
        ),
        ("a", "gg", Some("Invalid flags supplied to RegExp constructor 'gg'")),
        ("a", "uv", Some("Invalid flags supplied to RegExp constructor 'uv'")),
        ("a", "x", Some("Invalid flags supplied to RegExp constructor 'x'")),
        ("a", "dgimsuy", None),
        ("a", "dgimsvy", None),
        ("[a&&b]", "v", None),
        ("[a--b]", "v", None),
        (
            "[(]",
            "v",
            Some("Invalid regular expression: /[(]/v: Invalid character in character class"),
        ),
        (
            "[a-z&&b]",
            "v",
            Some("Invalid regular expression: /[a-z&&b]/v: Invalid set operation in character class"),
        ),
        (
            "[^\\q{ab}]",
            "v",
            Some("Invalid regular expression: /[^\\q{ab}]/v: Negated character class may contain strings"),
        ),
        (
            "\\q{a}",
            "v",
            Some("Invalid regular expression: /\\q{a}/v: Invalid escape"),
        ),
        ("(?<𝒜>.)", "u", None),
        ("(?<\\u0061>.)", "", None),
        ("(?<a>.)|(?<a>.)", "", None),
        ("[]", "", None),
        ("[^]", "", None),
        ("a|", "", None),
        ("|", "", None),
        ("()", "", None),
        ("(?<=a)b", "", None),
        ("(?<!a)b", "", None),
        ("(?!a)b", "", None),
        ("\\/", "", None),
        ("/", "", None),
        ("\\u{61}", "", None),
        ("\\u{61}", "u", None),
        ("[\\b]", "", None),
        ("\\B", "", None),
        ("(?<n>a)\\k<n>", "", None),
        ("\\k<n>", "", None),
        ("\\0", "u", None),
        (
            "\\00",
            "u",
            Some("Invalid regular expression: /\\00/u: Invalid decimal escape"),
        ),
        ("[\\0]", "u", None),
        ("\\cA", "u", None),
        ("[\\c]", "", None),
        ("[\\c_]", "", None),
        ("a{,5}", "", None),
        (
            "a{,5}",
            "u",
            Some("Invalid regular expression: /a{,5}/u: Incomplete quantifier"),
        ),
        ("\\s+\\S", "", None),
        ("\\p{Script=Greek}", "u", None),
        (
            "\\p{Script=Foo}",
            "u",
            Some("Invalid regular expression: /\\p{Script=Foo}/u: Invalid property name"),
        ),
        ("\\p{General_Category=L}", "u", None),
        ("\\p{RGI_Emoji}", "v", None),
        (
            "\\p{RGI_Emoji}",
            "u",
            Some("Invalid regular expression: /\\p{RGI_Emoji}/u: Invalid property name"),
        ),
        ("(/", "", Some("Invalid regular expression: /(//: Unterminated group")),
        ("(\n", "", Some("Invalid regular expression: /(\n/: Unterminated group")),
        ("(", "ig", Some("Invalid regular expression: /(/gi: Unterminated group")),
        (
            "(",
            "gimsuyd",
            Some("Invalid regular expression: /(/dgimsuy: Unterminated group"),
        ),
        (
            "(",
            "dygi",
            Some("Invalid regular expression: /(/dgiy: Unterminated group"),
        ),
        ("", "", None),
        (
            "[\\q]",
            "u",
            Some("Invalid regular expression: /[\\q]/u: Invalid escape"),
        ),
        (
            "[\\c]",
            "u",
            Some("Invalid regular expression: /[\\c]/u: Invalid Unicode escape"),
        ),
        ("[\\-]", "", None),
        (
            "[\\k]",
            "u",
            Some("Invalid regular expression: /[\\k]/u: Invalid escape"),
        ),
        (
            "[\\p{Foo}]",
            "u",
            Some("Invalid regular expression: /[\\p{Foo}]/u: Invalid property name in character class"),
        ),
        (
            "[\\p]",
            "u",
            Some("Invalid regular expression: /[\\p]/u: Invalid property name in character class"),
        ),
        (
            "[\\1]",
            "u",
            Some("Invalid regular expression: /[\\1]/u: Invalid decimal escape"),
        ),
        ("[\\0]", "", None),
        (
            "[\\00]",
            "u",
            Some("Invalid regular expression: /[\\00]/u: Invalid decimal escape"),
        ),
        (
            "[\\B]",
            "u",
            Some("Invalid regular expression: /[\\B]/u: Invalid escape"),
        ),
        ("[\\B]", "", None),
        (
            "[\\x1]",
            "u",
            Some("Invalid regular expression: /[\\x1]/u: Invalid escape"),
        ),
        (
            "[\\u12]",
            "u",
            Some("Invalid regular expression: /[\\u12]/u: Invalid Unicode escape"),
        ),
        ("[\\cA]", "u", None),
        (
            "[\\c1]",
            "u",
            Some("Invalid regular expression: /[\\c1]/u: Invalid Unicode escape"),
        ),
        ("[\\c1]", "", None),
        (
            "(?<a>.)(?<b>.)\\k<c>",
            "",
            Some("Invalid regular expression: /(?<a>.)(?<b>.)\\k<c>/: Invalid named capture referenced"),
        ),
        (
            "(?<a>.)\\k<a",
            "",
            Some("Invalid regular expression: /(?<a>.)\\k<a/: Invalid capture group name"),
        ),
        ("\\k<a", "", None),
        (
            "(?<a>.)\\k",
            "",
            Some("Invalid regular expression: /(?<a>.)\\k/: Invalid named reference"),
        ),
        (
            "(?<a>(?<a>.))",
            "",
            Some("Invalid regular expression: /(?<a>(?<a>.))/: Duplicate capture group name"),
        ),
        (
            "((?<a>.)|(?<b>.))(?<a>.)",
            "",
            Some("Invalid regular expression: /((?<a>.)|(?<b>.))(?<a>.)/: Duplicate capture group name"),
        ),
        ("(?:(?<a>.)|b)|(?<a>.)", "", None),
        (
            "(?<a>.)|\\k<b>",
            "",
            Some("Invalid regular expression: /(?<a>.)|\\k<b>/: Invalid named capture referenced"),
        ),
        ("(?<$>.)(?<_>.)(?<a1>.)", "", None),
        (
            "(?<a-b>.)",
            "",
            Some("Invalid regular expression: /(?<a-b>.)/: Invalid capture group name"),
        ),
        (
            "(?<>.)",
            "",
            Some("Invalid regular expression: /(?<>.)/: Invalid capture group name"),
        ),
        (
            "(?<a>",
            "",
            Some("Invalid regular expression: /(?<a>/: Unterminated group"),
        ),
        (
            "(?<=",
            "",
            Some("Invalid regular expression: /(?<=/: Unterminated group"),
        ),
        (
            "(?<",
            "",
            Some("Invalid regular expression: /(?</: Invalid capture group name"),
        ),
        (
            "(?<!",
            "",
            Some("Invalid regular expression: /(?<!/: Unterminated group"),
        ),
        ("(?=", "", Some("Invalid regular expression: /(?=/: Unterminated group")),
        ("(?!", "", Some("Invalid regular expression: /(?!/: Unterminated group")),
        ("(?i", "", Some("Invalid regular expression: /(?i/: Invalid group")),
        ("(?i)", "", Some("Invalid regular expression: /(?i)/: Invalid group")),
        ("(?i-)", "", Some("Invalid regular expression: /(?i-)/: Invalid group")),
        (
            "(?-:a)",
            "",
            Some("Invalid regular expression: /(?-:a)/: Invalid flag group"),
        ),
        ("(?-)", "", Some("Invalid regular expression: /(?-)/: Invalid group")),
        (
            "(?ims-ims:a)",
            "",
            Some("Invalid regular expression: /(?ims-ims:a)/: Repeated flag in flag group"),
        ),
        ("(?m:a)", "", None),
        (
            "(?u:a)",
            "",
            Some("Invalid regular expression: /(?u:a)/: Invalid group"),
        ),
        (
            "(?i:",
            "",
            Some("Invalid regular expression: /(?i:/: Unterminated group"),
        ),
        ("a{1}?", "u", None),
        ("a{1,2}", "u", None),
        ("a{1,}", "u", None),
        ("a{}", "", None),
        (
            "a{}",
            "u",
            Some("Invalid regular expression: /a{}/u: Incomplete quantifier"),
        ),
        ("a{a}", "", None),
        (
            "a{a}",
            "u",
            Some("Invalid regular expression: /a{a}/u: Incomplete quantifier"),
        ),
        (
            "a{1,a}",
            "u",
            Some("Invalid regular expression: /a{1,a}/u: Incomplete quantifier"),
        ),
        (
            "{1,2}",
            "",
            Some("Invalid regular expression: /{1,2}/: Nothing to repeat"),
        ),
        (
            "{1,}",
            "",
            Some("Invalid regular expression: /{1,}/: Nothing to repeat"),
        ),
        ("{,}", "", None),
        ("{1", "", None),
        ("a|*", "", Some("Invalid regular expression: /a|*/: Nothing to repeat")),
        ("(*)", "", Some("Invalid regular expression: /(*)/: Nothing to repeat")),
        (
            "(?:*)",
            "",
            Some("Invalid regular expression: /(?:*)/: Nothing to repeat"),
        ),
        (
            "a|{1}",
            "",
            Some("Invalid regular expression: /a|{1}/: Nothing to repeat"),
        ),
        (
            "\\B{2}",
            "",
            Some("Invalid regular expression: /\\B{2}/: Nothing to repeat"),
        ),
        ("\\d-a", "u", None),
        ("\\cJ", "", None),
        ("\\c0", "", None),
        (
            "\\c0",
            "u",
            Some("Invalid regular expression: /\\c0/u: Invalid Unicode escape"),
        ),
        ("\\ca", "u", None),
        (
            "\\u{}",
            "u",
            Some("Invalid regular expression: /\\u{}/u: Invalid Unicode escape"),
        ),
        (
            "\\u{0061",
            "u",
            Some("Invalid regular expression: /\\u{0061/u: Invalid Unicode escape"),
        ),
        ("\\uD83D\\uDE00", "u", None),
        ("\\x", "", None),
        ("\\x", "u", Some("Invalid regular expression: /\\x/u: Invalid escape")),
        (
            "\\xGG",
            "u",
            Some("Invalid regular expression: /\\xGG/u: Invalid escape"),
        ),
        (
            "\\u",
            "u",
            Some("Invalid regular expression: /\\u/u: Invalid Unicode escape"),
        ),
        ("\\u", "", None),
        ("\\/", "u", None),
        ("\\$", "u", None),
        ("\\^", "u", None),
        ("\\|", "u", None),
        ("\\]", "u", None),
        ("\\}", "u", None),
        ("\\a", "u", Some("Invalid regular expression: /\\a/u: Invalid escape")),
        ("\\e", "u", Some("Invalid regular expression: /\\e/u: Invalid escape")),
        ("\\f\\n\\r\\t\\v", "u", None),
        ("\\0", "", None),
        ("\\01", "", None),
        ("\\10", "", None),
        ("(a)\\1", "u", None),
        (
            "(a)\\10",
            "u",
            Some("Invalid regular expression: /(a)\\10/u: Invalid escape"),
        ),
        ("\\k<a>(?<a>.)", "u", None),
        ("\\1(a)", "u", None),
        ("[\\d-\\w]", "", None),
        ("[a-]", "u", None),
        ("[-a]", "u", None),
        ("[a-b-c]", "u", None),
        ("[\\w-]", "u", None),
        ("[--a]", "", None),
        ("[\\]]", "", None),
        ("[^]]", "", None),
        ("[]]", "", None),
        ("\\p{Lu}", "u", None),
        ("\\P{Lu}", "u", None),
        (
            "\\p{lu}",
            "u",
            Some("Invalid regular expression: /\\p{lu}/u: Invalid property name"),
        ),
        ("\\p{ASCII}", "u", None),
        ("\\p{Any}", "u", None),
        ("\\p{scx=Grek}", "u", None),
        ("\\p{sc=Grek}", "u", None),
        ("\\p{gc=Lu}", "u", None),
        (
            "\\p{L=Lu}",
            "u",
            Some("Invalid regular expression: /\\p{L=Lu}/u: Invalid property name"),
        ),
        ("\\p{ASCII_Hex_Digit}", "u", None),
        ("\\p{Emoji}", "u", None),
        (
            "\\p{Basic_Emoji}",
            "u",
            Some("Invalid regular expression: /\\p{Basic_Emoji}/u: Invalid property name"),
        ),
        (
            "[a&&&b]",
            "v",
            Some("Invalid regular expression: /[a&&&b]/v: Invalid character in character class"),
        ),
        (
            "[a&&]",
            "v",
            Some("Invalid regular expression: /[a&&]/v: Invalid character in character class"),
        ),
        (
            "[&&a]",
            "v",
            Some("Invalid regular expression: /[&&a]/v: Invalid set operation in character class"),
        ),
        (
            "[a--]",
            "v",
            Some("Invalid regular expression: /[a--]/v: Invalid character in character class"),
        ),
        (
            "[a&&b--c]",
            "v",
            Some("Invalid regular expression: /[a&&b--c]/v: Invalid set operation in character class"),
        ),
        ("[[a-z]--[aeiou]]", "v", None),
        ("[\\q{abc|d}]", "v", None),
        (
            "[a!!]",
            "v",
            Some("Invalid regular expression: /[a!!]/v: Invalid set operation in character class"),
        ),
        ("[a-z]", "v", None),
        (
            "[a-]",
            "v",
            Some("Invalid regular expression: /[a-]/v: Invalid character in character class"),
        ),
        (
            "[|]",
            "v",
            Some("Invalid regular expression: /[|]/v: Invalid character in character class"),
        ),
        ("[\\|]", "v", None),
        ("[a[b]]", "v", None),
        (
            "[^\\p{RGI_Emoji}]",
            "v",
            Some("Invalid regular expression: /[^\\p{RGI_Emoji}]/v: Negated character class may contain strings"),
        ),
        (
            "\\P{RGI_Emoji}",
            "v",
            Some("Invalid regular expression: /\\P{RGI_Emoji}/v: Invalid property name"),
        ),
        (
            "[{]",
            "v",
            Some("Invalid regular expression: /[{]/v: Invalid character in character class"),
        ),
        ("[\\-]", "v", None),
        ("[\\&]", "v", None),
        ("[&]", "v", None),
        ("[a&b]", "v", None),
        (
            "x{2}{3}",
            "u",
            Some("Invalid regular expression: /x{2}{3}/u: Nothing to repeat"),
        ),
        (
            "x**",
            "u",
            Some("Invalid regular expression: /x**/u: Nothing to repeat"),
        ),
        ("(?=a){2}", "", None),
        ("(?!a)+", "", None),
        (
            "(?<!a)?",
            "",
            Some("Invalid regular expression: /(?<!a)?/: Invalid quantifier"),
        ),
        ("a{0}", "", None),
        ("a{2147483648}", "", None),
        ("a{2147483648,2147483647}", "", None),
        (
            "a{3,2}",
            "u",
            Some("Invalid regular expression: /a{3,2}/u: numbers out of order in {} quantifier"),
        ),
        ("\\w+?", "", None),
        ("[\\s\\S]", "", None),
        ("(?<a>a)\\k<a>", "u", None),
        ("\\k<a>", "", None),
        ("\\k<", "", None),
        ("\\k<a>(?<a>.)", "", None),
        ("(?i-:a)", "", None),
        ("(?i-m:a)", "", None),
        ("(?s:.)", "", None),
        ("(?i:a)(?<n>b)\\k<n>", "u", None),
        ("[\\u{1F600}-\\u{1F64F}]", "u", None),
        ("[\\uD83D\\uDE00-\\uD83D\\uDE4F]", "u", None),
        ("\\p{Lu}", "i", None),
        ("[\\p{L}--\\p{Lu}]", "v", None),
        ("[\\p{L}&&\\p{Lu}]", "v", None),
        ("[^a]", "v", None),
        ("[a-c[d-f]]", "v", None),
        ("[\\q{}]", "v", None),
        ("[^\\q{a|b}]", "v", None),
        ("(?<a>.)(?<b>.)", "g", None),
        ("^(?:\\s|[\\p{P}])+$", "u", None),
        ("[\\u3000-\\u303f]", "u", None),
        ("(?:(?!\\s).)*", "u", None),
        ("\\[paste #\\d+( (\\+\\d+ lines|\\d+ chars))?\\]", "g", None),
        ("(?:^|[,\\s])foo=(?:\"([^\"]*)\"|([^\\s,]+))", "i", None),
        ("^[a-z]+$", "y", None),
        ("a", "d", None),
        ("a", "dd", Some("Invalid flags supplied to RegExp constructor 'dd'")),
        ("a", "Z", Some("Invalid flags supplied to RegExp constructor 'Z'")),
        ("a", "gimsuy", None),
        ("a", "gimsvy", None),
        ("a", "uu", Some("Invalid flags supplied to RegExp constructor 'uu'")),
        ("\\u{1F600}", "u", None),
        ("\\ud83d", "u", None),
        ("[\\ud83d]", "u", None),
        ("(?<π>a)", "u", None),
        ("(?<a\\u0062>.)\\k<ab>", "", None),
        ("(?<\\u{61}>.)", "", None),
        (
            "(?<\\u{61>.)",
            "",
            Some("Invalid regular expression: /(?<\\u{61>.)/: Invalid Unicode escape"),
        ),
        (
            "(?<a\\>.)",
            "",
            Some("Invalid regular expression: /(?<a\\>.)/: Invalid capture group name"),
        ),
        (
            "a{1,2}{3}",
            "",
            Some("Invalid regular expression: /a{1,2}{3}/: Nothing to repeat"),
        ),
        ("(?:a|b)+?", "", None),
        ("a{2}?b", "u", None),
        ("\\cJ", "u", None),
        ("[\\cJ]", "", None),
        ("[\\c]", "", None),
        ("\\c", "i", None),
        ("[\\-a]", "", None),
        ("[a\\-z]", "u", None),
        ("[\\d-]", "u", None),
        ("(", "gu", Some("Invalid regular expression: /(/gu: Unterminated group")),
        (
            "(?=",
            "u",
            Some("Invalid regular expression: /(?=/u: Unterminated group"),
        ),
        ("a)", "v", Some("Invalid regular expression: /a)/v: Unmatched ')'")),
        (
            "[",
            "v",
            Some("Invalid regular expression: /[/v: Unterminated character class"),
        ),
        (
            "[a",
            "v",
            Some("Invalid regular expression: /[a/v: Unterminated character class"),
        ),
        (
            "[a&&",
            "v",
            Some("Invalid regular expression: /[a&&/v: Unterminated character class"),
        ),
        (
            "[a--b",
            "v",
            Some("Invalid regular expression: /[a--b/v: Unterminated character class"),
        ),
        (
            "[\\q{a",
            "v",
            Some("Invalid regular expression: /[\\q{a/v: Unterminated character class"),
        ),
        ("[\\q", "v", Some("Invalid regular expression: /[\\q/v: Invalid escape")),
        (
            "\\",
            "v",
            Some("Invalid regular expression: /\\/v: \\ at end of pattern"),
        ),
    ];

    pub struct ExecCase {
        pub pattern: &'static str,
        pub flags: &'static str,
        pub input: &'static str,
        pub expected: Option<(
            usize,
            &'static str,
            &'static [Option<&'static str>],
            Option<&'static [(&'static str, Option<&'static str>)]>,
        )>,
    }
    pub const EXEC: &[ExecCase] = &[
        ExecCase {
            pattern: "(\\d+)-(\\d+)",
            flags: "",
            input: "a 12-34 b 56-78",
            expected: Some((2, "12-34", &[Some("12"), Some("34")], None)),
        },
        ExecCase {
            pattern: "(?<y>\\d{4})-(?<m>\\d{2})",
            flags: "",
            input: "on 2026-10 ok",
            expected: Some((
                3,
                "2026-10",
                &[Some("2026"), Some("10")],
                Some(&[("y", Some("2026")), ("m", Some("10"))]),
            )),
        },
        ExecCase {
            pattern: "\\s+",
            flags: "",
            input: "a \u{a0}\u{2028}\u{feff} b",
            expected: Some((1, " \u{a0}\u{2028}\u{feff} ", &[], None)),
        },
        ExecCase {
            pattern: "é(.)",
            flags: "",
            input: "cafébx",
            expected: Some((3, "éb", &[Some("b")], None)),
        },
        ExecCase {
            pattern: "😀(.)",
            flags: "u",
            input: "a😀😁b",
            expected: Some((1, "😀😁", &[Some("😁")], None)),
        },
        ExecCase {
            pattern: "a|(b)",
            flags: "",
            input: "xa",
            expected: Some((1, "a", &[None], None)),
        },
        ExecCase {
            pattern: "^foo$",
            flags: "m",
            input: "x\nfoo\ny",
            expected: Some((2, "foo", &[], None)),
        },
        ExecCase {
            pattern: "FOO",
            flags: "i",
            input: "a foo",
            expected: Some((2, "foo", &[], None)),
        },
        ExecCase {
            pattern: "a.b",
            flags: "s",
            input: "a\nb",
            expected: Some((0, "a\nb", &[], None)),
        },
        ExecCase {
            pattern: "a.b",
            flags: "",
            input: "a\nb a-b",
            expected: Some((4, "a-b", &[], None)),
        },
        ExecCase {
            pattern: "(?<=\\$)\\d+",
            flags: "",
            input: "cost $42",
            expected: Some((6, "42", &[], None)),
        },
        ExecCase {
            pattern: "\\bword\\b",
            flags: "",
            input: "a word here",
            expected: Some((2, "word", &[], None)),
        },
        ExecCase {
            pattern: "x*",
            flags: "g",
            input: "axxb",
            expected: Some((0, "", &[], None)),
        },
    ];

    pub const MATCH_ALL: &[(&str, &str, &str, &[(usize, &str)])] = &[
        ("(\\d+)-(\\d+)", "", "a 12-34 b 56-78", &[(2, "12-34"), (10, "56-78")]),
        ("(?<y>\\d{4})-(?<m>\\d{2})", "", "on 2026-10 ok", &[(3, "2026-10")]),
        (
            "\\s+",
            "",
            "a \u{a0}\u{2028}\u{feff} b",
            &[(1, " \u{a0}\u{2028}\u{feff} ")],
        ),
        ("é(.)", "", "cafébx", &[(3, "éb")]),
        ("😀(.)", "u", "a😀😁b", &[(1, "😀😁")]),
        ("a|(b)", "", "xa", &[(1, "a")]),
        ("^foo$", "m", "x\nfoo\ny", &[(2, "foo")]),
        ("FOO", "i", "a foo", &[(2, "foo")]),
        ("a.b", "s", "a\nb", &[(0, "a\nb")]),
        ("a.b", "", "a\nb a-b", &[(4, "a-b")]),
        ("(?<=\\$)\\d+", "", "cost $42", &[(6, "42")]),
        ("\\bword\\b", "", "a word here", &[(2, "word")]),
        ("x*", "g", "axxb", &[(0, ""), (1, "xx"), (3, ""), (4, "")]),
    ];

    pub const REPLACE: &[(&str, &str, &str, &str, bool, &str)] = &[
        (
            "(\\d+)-(\\d+)",
            "",
            "a 12-34 b 56-78",
            "$2-$1",
            false,
            "a 34-12 b 56-78",
        ),
        (
            "(\\d+)-(\\d+)",
            "g",
            "a 12-34 b 56-78",
            "$2-$1",
            true,
            "a 34-12 b 78-56",
        ),
        (
            "(\\d+)",
            "g",
            "a1b22",
            "[$&|$`|$'|$$|$0|$3|$11|$01]",
            true,
            "a[1|a|b22|$|$0|$3|11|1]b[22|a1b||$|$0|$3|221|22]",
        ),
        (
            "(?<y>\\d{4})-(?<m>\\d{2})",
            "g",
            "on 2026-10 ok",
            "$<m>/$<y> $<zz>|$<y",
            true,
            "on 10/2026 |$<y ok",
        ),
        (
            "(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)",
            "",
            "abcdefghijk",
            "$11-$10-$1-$12-$100",
            false,
            "k-j-a-a2-j0",
        ),
        ("x*", "g", "axxb", "-", true, "-a--b-"),
        ("b", "g", "abc", "$<y>", true, "a$<y>c"),
        ("é", "g", "café é", "[$`]", true, "caf[caf] [café ]"),
        (
            "[.*+?^${}()|[\\]\\\\]",
            "g",
            "a.b*c(d)",
            "\\$&",
            true,
            "a\\.b\\*c\\(d\\)",
        ),
    ];
}
use vectors::*;

use pi_js::regex::{self as re, JsFlags};
use pretty_assertions::assert_eq;

#[test]
fn syntax_errors_match_v8() {
    let mut failures = Vec::new();
    for (pattern, flags, expected) in SYNTAX {
        let got = re::ecma(pattern, flags);
        let got_msg = got.as_ref().err().map(|e| e.to_string());
        if let Err(e) = &got {
            assert_eq!(e.name(), "SyntaxError", "/{pattern}/{flags}");
        }
        if got_msg.as_deref() != *expected {
            failures.push(format!("/{pattern}/{flags}: expected {expected:?}, got {got_msg:?}"));
        }
    }
    // PORT: V8 clamps both quantifier bounds to 2^31-1 (so `{2147483648,2147483647}` is
    // `{max,max}`); regress compares the unclamped numbers and rejects the pattern.
    failures.retain(|f| !f.starts_with("/a{2147483648,2147483647}/:"));
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn flags_parse_and_canonicalize() {
    let f = JsFlags::parse("yigd").unwrap();
    assert!(f.sticky && f.ignore_case && f.global && f.has_indices);
    assert_eq!(f.canonical(), "dgiy");
    assert!(!f.unicode_mode());
    assert!(JsFlags::parse("v").unwrap().unicode_mode());
    assert_eq!(
        JsFlags::parse("gg").unwrap_err().to_string(),
        "Invalid flags supplied to RegExp constructor 'gg'"
    );
}

#[test]
fn exec_matches_v8() {
    for case in EXEC {
        let compiled = re::ecma(case.pattern, case.flags).unwrap();
        let got = re::exec(&compiled, case.input);
        match (got, &case.expected) {
            (None, None) => {}
            (Some(m), Some((index, matched, captures, groups))) => {
                assert_eq!(m.index, *index, "index /{}/{}", case.pattern, case.flags);
                assert_eq!(m.matched, *matched, "match /{}/{}", case.pattern, case.flags);
                let caps: Vec<Option<&str>> = m.captures.iter().map(|c| c.as_deref()).collect();
                assert_eq!(caps, captures.to_vec(), "captures /{}/{}", case.pattern, case.flags);
                let got_groups: Option<Vec<(&str, Option<&str>)>> = m
                    .groups
                    .as_ref()
                    .map(|g| g.iter().map(|(k, v)| (k.as_str(), v.as_deref())).collect());
                assert_eq!(
                    got_groups,
                    groups.map(|g| g.to_vec()),
                    "groups /{}/{}",
                    case.pattern,
                    case.flags
                );
                assert_eq!(&case.input[m.byte_start..m.byte_end], m.matched);
            }
            (got, expected) => panic!(
                "/{}/{}: got {got:?}, expected {:?}",
                case.pattern,
                case.flags,
                expected.is_some()
            ),
        }
    }
}

#[test]
fn match_all_matches_v8() {
    for (pattern, flags, input, expected) in MATCH_ALL {
        let compiled = re::ecma(pattern, flags).unwrap();
        let got: Vec<(usize, String)> = re::match_all(&compiled, input)
            .into_iter()
            .map(|m| (m.index, m.matched))
            .collect();
        let expected: Vec<(usize, String)> = expected.iter().map(|(i, s)| (*i, s.to_string())).collect();
        assert_eq!(got, expected, "/{pattern}/{flags} on {input:?}");
    }
}

#[test]
fn replace_matches_v8() {
    for (pattern, flags, input, replacement, global, expected) in REPLACE {
        let compiled = re::ecma(pattern, flags).unwrap();
        assert_eq!(
            re::replace(&compiled, input, replacement, *global),
            *expected,
            "/{pattern}/{flags} {replacement:?}"
        );
    }
}

#[test]
fn non_unicode_dot_matches_whole_astral_char() {
    // PORT: V8 matches UTF-16 code units without `u`, so `/é(.)/.exec("café😀")[1]` is a lone
    // surrogate. Rust strings cannot hold one; regress matches the whole code point instead.
    let compiled = re::ecma("é(.)", "").unwrap();
    let m = re::exec(&compiled, "café😀x").unwrap();
    assert_eq!(m.captures[0].as_deref(), Some("😀"));
    assert_eq!(m.index, 3);
}

#[test]
fn replace_with_callback() {
    let compiled = re::ecma("(\\d+)", "g").unwrap();
    let out = re::replace_with(&compiled, "a1b22", true, |m| {
        format!("<{}@{}>", m.captures[0].as_deref().unwrap(), m.index)
    });
    assert_eq!(out, "a<1@1>b<22@3>");
    let first = re::replace_with(&compiled, "a1b22", false, |m| m.matched.repeat(2));
    assert_eq!(first, "a11b22");
}

#[test]
fn test_and_named_group_lookup() {
    let compiled = re::ecma("(?<word>[a-z]+)", "i").unwrap();
    assert!(re::test(&compiled, "123 ABC"));
    assert!(!re::test(&compiled, "123"));
    let m = re::exec(&compiled, "123 ABC").unwrap();
    assert_eq!(m.group("word"), Some("ABC"));
    assert_eq!(m.group("missing"), None);
}

#[test]
fn escape_matches_common_js_helper() {
    assert_eq!(
        re::escape("a.b*c(d)[e]{f}|g^$\\"),
        "a\\.b\\*c\\(d\\)\\[e\\]\\{f\\}\\|g\\^\\$\\\\"
    );
    let compiled = re::ecma(&re::escape("1+1=2?"), "").unwrap();
    assert!(re::test(&compiled, "is 1+1=2?"));
}

#[test]
fn js_ws_class_works_in_every_engine() {
    let ws = "\t\n\u{b}\u{c}\r \u{a0}\u{1680}\u{2000}\u{2005}\u{200a}\u{2028}\u{2029}\u{202f}\u{205f}\u{3000}\u{feff}";
    let not_ws = "a\u{85}\u{180e}\u{200b}_";
    let plain = regex::Regex::new(&format!("^{}+$", re::JS_WS_CLASS)).unwrap();
    assert!(plain.is_match(ws));
    for c in not_ws.chars() {
        assert!(!plain.is_match(&c.to_string()), "{c:?}");
    }
    let fancy = fancy_regex::Regex::new(&format!("^{}+(?={})", re::JS_WS_CLASS, re::JS_NON_WS_CLASS)).unwrap();
    assert!(fancy.is_match(" \u{3000}x").unwrap());
    let ecma = re::ecma(&format!("^{}+$", re::JS_WS_CLASS), "u").unwrap();
    assert!(re::test(&ecma, ws));
    let inner = regex::Regex::new(&format!("^[^{},]+$", re::JS_WS_CHARS)).unwrap();
    assert!(inner.is_match("abc"));
    assert!(!inner.is_match("a,b"));
    assert!(!inner.is_match("a\u{feff}b"));
    // The JS `\s` equals the class (cross-check against regress's own `\s`).
    let js_s = re::ecma("^\\s+$", "").unwrap();
    assert!(re::test(&js_s, ws));
    for c in not_ws.chars() {
        assert!(!re::test(&js_s, &c.to_string()), "{c:?}");
    }
    let dot = regex::Regex::new(&format!("^{}$", re::JS_DOT_CLASS)).unwrap();
    assert!(dot.is_match("a") && dot.is_match("\u{85}"));
    assert!(!dot.is_match("\n") && !dot.is_match("\u{2028}"));
}
