//! pi_js::fetch tests. Expected values come from Node 24 / undici probes (see `vectors`).

#[rustfmt::skip]
#[allow(clippy::type_complexity)]
mod vectors {
    // @generated by gen-fetch.mjs with Node v24.21.0 and undici 8.10.2. Do not edit.
    pub struct SseCase { pub body: &'static [u8], pub events: &'static [(&'static str, &'static str, &'static str)] }
    /// (event type, data, lastEventId) as undici's EventSource dispatched them.
    pub const SSE: &[SseCase] = &[
        SseCase { body: b"data: hello\x0a\x0a", events: &[("message", "hello", "")] },
        SseCase { body: b"data: a\x0adata: b\x0a\x0a", events: &[("message", "a\u{a}b", "")] },
        SseCase { body: b"event: foo\x0adata: x\x0a\x0a", events: &[("foo", "x", "")] },
        SseCase { body: b"id: 1\x0adata: x\x0a\x0adata: y\x0a\x0a", events: &[("message", "x", "1"), ("message", "y", "1")] },
        SseCase { body: b"id: 1\x0adata: x\x0a\x0aid\x0adata: y\x0a\x0a", events: &[("message", "x", "1"), ("message", "y", "")] },
        SseCase { body: b": comment\x0adata: x\x0a\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"data:x\x0a\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"data:  two spaces\x0a\x0a", events: &[("message", " two spaces", "")] },
        SseCase { body: b"data\x0a\x0a", events: &[("message", "", "")] },
        SseCase { body: b"data:\x0a\x0a", events: &[("message", "", "")] },
        SseCase { body: b"\xef\xbb\xbfdata: bom\x0a\x0a", events: &[("message", "bom", "")] },
        SseCase { body: b"\xef\xbb\xbf\xef\xbb\xbfdata: x\x0a\x0a", events: &[] },
        SseCase { body: b"data: a\x0d\x0adata: b\x0d\x0a\x0d\x0a", events: &[("message", "a\u{a}b", "")] },
        SseCase { body: b"data: a\x0ddata: b\x0d\x0d", events: &[("message", "a\u{a}b", "")] },
        SseCase { body: b"data: a\x0d\x0a\x0ddata: b\x0a\x0a", events: &[("message", "a", ""), ("message", "b", "")] },
        SseCase { body: b"event: foo\x0a\x0adata: x\x0a\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"retry: 1000\x0adata: x\x0a\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"retry: abc\x0adata: x\x0a\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"data: incomplete", events: &[] },
        SseCase { body: b"data: x\x0a\x0adata: trailing\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"id: a\x00b\x0adata: x\x0a\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"data: \xc3\xa9\xf0\x9f\x98\x80\x0a\x0a", events: &[("message", "é😀", "")] },
        SseCase { body: b"foo: bar\x0adata: x\x0a\x0a", events: &[("message", "x", "")] },
        SseCase { body: b" data: x\x0a\x0a", events: &[] },
        SseCase { body: b"data: x\x0a\x0a\x0a\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"event: \x0adata: x\x0a\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"event: bar\x0adata: 1\x0a\x0aevent: foo\x0adata: 2\x0a\x0adata: 3\x0a\x0a", events: &[("bar", "1", ""), ("foo", "2", ""), ("message", "3", "")] },
        SseCase { body: b"data: {\x22a\x22:1}\x0a\x0adata: [DONE]\x0a\x0a", events: &[("message", "{\"a\":1}", ""), ("message", "[DONE]", "")] },
        SseCase { body: b"data: line1\x0adata:\x0adata: line3\x0a\x0a", events: &[("message", "line1\u{a}\u{a}line3", "")] },
        SseCase { body: b"id: 7\x0a\x0adata: x\x0a\x0a", events: &[("message", "x", "7")] },
        SseCase { body: b"DATA: x\x0adata: y\x0a\x0a", events: &[("message", "y", "")] },
        SseCase { body: b"data: x\x0aevent: late\x0a\x0a", events: &[("late", "x", "")] },
        SseCase { body: b"event: message\x0adata: m\x0a\x0a", events: &[("message", "m", "")] },
        SseCase { body: b"data: a:b:c\x0a\x0a", events: &[("message", "a:b:c", "")] },
        SseCase { body: b"data: x\x0a\x0aid: 9\x0a", events: &[("message", "x", "")] },
        SseCase { body: b"data: \xff\xfe ok\x0a\x0a", events: &[("message", "\u{fffd}\u{fffd} ok", "")] },
        SseCase { body: b"data: \xe2\x82\x0a\x0a", events: &[("message", "\u{fffd}", "")] },
    ];
    /// (url, Ok((status_text, content-type, body bytes, response url)) | Err(cause message)).
    pub const DATA_URLS: &[(&str, Result<(&str, &str, &[u8], &str), &str>)] = &[
        ("data:,hello", Ok(("OK", "text/plain;charset=US-ASCII", b"hello", "data:,hello"))),
        ("data:,Hello%2C%20World%21", Ok(("OK", "text/plain;charset=US-ASCII", b"Hello, World!", "data:,Hello%2C%20World%21"))),
        ("data:text/plain;base64,aGk=", Ok(("OK", "text/plain", b"hi", "data:text/plain;base64,aGk="))),
        ("data:text/plain;base64,aGk", Ok(("OK", "text/plain", b"hi", "data:text/plain;base64,aGk"))),
        ("data:;base64,aGk=", Ok(("OK", "text/plain;charset=US-ASCII", b"hi", "data:;base64,aGk="))),
        ("data:TEXT/HTML;Charset=UTF-8,<b>x</b>", Ok(("OK", "text/html;charset=UTF-8", b"<b>x</b>", "data:TEXT/HTML;Charset=UTF-8,<b>x</b>"))),
        ("data:application/json;charset=utf-8,%7B%22a%22%3A1%7D", Ok(("OK", "application/json;charset=utf-8", b"{\x22a\x22:1}", "data:application/json;charset=utf-8,%7B%22a%22%3A1%7D"))),
        ("data:text/plain ; base64 ,aGk=", Ok(("OK", "text/plain", b"hi", "data:text/plain ; base64 ,aGk="))),
        ("data:text/plain;BASE64,aGVs bG8=", Ok(("OK", "text/plain", b"hello", "data:text/plain;BASE64,aGVs bG8="))),
        ("data:image/png;base64,iVBORw0KGgo=", Ok(("OK", "image/png", b"\x89PNG\x0d\x0a\x1a\x0a", "data:image/png;base64,iVBORw0KGgo="))),
        ("data:text/plain;a=1;b=\"x;y\";a=2,z", Ok(("OK", "text/plain;a=1;b=\"x;y\"", b"z", "data:text/plain;a=1;b=\"x;y\";a=2,z"))),
        ("data:foo,bar", Ok(("OK", "text/plain;charset=US-ASCII", b"bar", "data:foo,bar"))),
        ("data:text/plain;charset=\"utf-8\",q", Ok(("OK", "text/plain;charset=utf-8", b"q", "data:text/plain;charset=\"utf-8\",q"))),
        ("data:text/plain;base64,a", Err("failed to fetch the data URL")),
        ("data:text/plain;base64,a===", Err("failed to fetch the data URL")),
        ("data:text/plain,a#frag", Ok(("OK", "text/plain", b"a", "data:text/plain,a"))),
        ("data:text/plain;x=,y", Ok(("OK", "text/plain", b"y", "data:text/plain;x=,y"))),
    ];
    pub const GZIP_HELLO: &[u8] = b"\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x13\xcbH\xcd\xc9\xc9WH\xaf\xca,\x00\x00\x19j\xd2\xdf\x0a\x00\x00\x00";
    pub const BROTLI_HELLO: &[u8] = b"\x8b\x03\x80hello br\x03";
}
use vectors::*;

use std::net::SocketAddr;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use bytes::Bytes;
use futures::StreamExt;
use pi_js::abort::{AbortController, AbortReason, AbortSignal};
use pi_js::fetch::{self, Body, Headers, Request, Response, SseEvent, SseParser, testing};
use pi_js::{Error, JsError, NodeError};
use pretty_assertions::assert_eq;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{TcpListener, TcpStream};

// ---- helpers ------------------------------------------------------------------------------

fn js(e: &Error) -> &JsError {
    match e {
        Error::Js(j) => j,
        other => panic!("expected Error::Js, got {other:?}"),
    }
}

/// (name, message, code) of an error.
fn shape(e: &Error) -> (String, String, Option<String>) {
    (e.name().to_string(), e.message(), e.code().map(str::to_string))
}

/// The `cause` of `TypeError: fetch failed` / `TypeError: terminated`.
fn cause(e: &Error) -> &Error {
    js(e).cause.as_deref().unwrap_or_else(|| panic!("no cause on {e:?}"))
}

fn fetch_failed(e: &Error) -> (String, String, Option<String>) {
    assert_eq!(
        shape(e),
        ("TypeError".to_string(), "fetch failed".to_string(), None),
        "{e:?}"
    );
    shape(cause(e))
}

fn s(x: &str) -> String {
    x.to_string()
}

#[derive(Clone, Debug)]
struct Captured {
    method: String,
    path: String,
    headers: Vec<(String, String)>,
    body: Vec<u8>,
}

impl Captured {
    fn header(&self, name: &str) -> Option<&str> {
        self.headers
            .iter()
            .find(|(k, _)| k.eq_ignore_ascii_case(name))
            .map(|(_, v)| v.as_str())
    }
}

enum Reply {
    /// Raw bytes, then close.
    Raw(Vec<u8>),
    /// Raw pieces written with a pause before each, then close.
    Paced(Vec<(u64, Vec<u8>)>),
}

fn reply(status: &str, headers: &[(&str, &str)], body: &[u8]) -> Reply {
    let mut out = format!("HTTP/1.1 {status}\r\n");
    for (k, v) in headers {
        out.push_str(&format!("{k}: {v}\r\n"));
    }
    out.push_str(&format!("content-length: {}\r\nconnection: close\r\n\r\n", body.len()));
    let mut bytes = out.into_bytes();
    bytes.extend_from_slice(body);
    Reply::Raw(bytes)
}

struct Server {
    addr: SocketAddr,
    seen: Arc<Mutex<Vec<Captured>>>,
}

impl Server {
    fn url(&self, path: &str) -> String {
        format!("http://{}{path}", self.addr)
    }

    fn requests(&self) -> Vec<Captured> {
        self.seen.lock().unwrap().clone()
    }
}

async fn read_request(sock: &mut TcpStream) -> Option<Captured> {
    let mut buf = Vec::new();
    let mut tmp = [0u8; 4096];
    let head_end = loop {
        if let Some(i) = buf.windows(4).position(|w| w == b"\r\n\r\n") {
            break i;
        }
        let n = sock.read(&mut tmp).await.ok()?;
        if n == 0 {
            return None;
        }
        buf.extend_from_slice(&tmp[..n]);
    };
    let head = String::from_utf8_lossy(&buf[..head_end]).into_owned();
    let mut lines = head.split("\r\n");
    let mut first = lines.next()?.split(' ');
    let method = first.next()?.to_string();
    let path = first.next()?.to_string();
    let headers: Vec<(String, String)> = lines
        .filter_map(|l| l.split_once(':'))
        .map(|(k, v)| (k.to_string(), v.trim().to_string()))
        .collect();
    let len: usize = headers
        .iter()
        .find(|(k, _)| k.eq_ignore_ascii_case("content-length"))
        .and_then(|(_, v)| v.parse().ok())
        .unwrap_or(0);
    let mut body = buf[head_end + 4..].to_vec();
    while body.len() < len {
        let n = sock.read(&mut tmp).await.ok()?;
        if n == 0 {
            break;
        }
        body.extend_from_slice(&tmp[..n]);
    }
    Some(Captured {
        method,
        path,
        headers,
        body,
    })
}

async fn serve(handler: impl Fn(&Captured, SocketAddr) -> Reply + Send + Sync + 'static) -> Server {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();
    let seen = Arc::new(Mutex::new(Vec::new()));
    let handler = Arc::new(handler);
    let log = seen.clone();
    tokio::spawn(async move {
        loop {
            let Ok((mut sock, _)) = listener.accept().await else {
                return;
            };
            let handler = handler.clone();
            let log = log.clone();
            tokio::spawn(async move {
                let Some(req) = read_request(&mut sock).await else {
                    return;
                };
                log.lock().unwrap().push(req.clone());
                match handler(&req, addr) {
                    Reply::Raw(bytes) => {
                        let _ = sock.write_all(&bytes).await;
                    }
                    Reply::Paced(parts) => {
                        for (pause, bytes) in parts {
                            tokio::time::sleep(Duration::from_millis(pause)).await;
                            if sock.write_all(&bytes).await.is_err() {
                                return;
                            }
                        }
                    }
                }
                let _ = sock.shutdown().await;
            });
        }
    });
    Server { addr, seen }
}

/// Echoes the request as JSON and serves the redirect fixtures of the Node probe.
async fn echo_server() -> Server {
    serve(|req, addr| match req.path.as_str() {
        "/r301" => reply("301 Moved Permanently", &[("location", "/echo")], b"moved"),
        "/r302" => reply("302 Found", &[("location", "/echo")], b""),
        "/r303" => reply("303 See Other", &[("location", "/echo")], b""),
        "/r307" => reply("307 Temporary Redirect", &[("location", "/echo")], b""),
        "/loop" => reply("302 Found", &[("location", "/loop")], b""),
        "/noloc" => reply("302 Found", &[], b"x"),
        "/badloc" => reply("302 Found", &[("location", "ftp://x/")], b"x"),
        "/frag" => reply("302 Found", &[("location", "/echo")], b""),
        "/abs" => reply("302 Found", &[("location", &format!("http://{addr}/echo?abs=1"))], b""),
        "/204" => reply("204 No Content", &[], b""),
        "/close" => Reply::Paced(vec![
            (
                0,
                b"HTTP/1.1 200 OK\r\ncontent-length: 100\r\nconnection: close\r\n\r\npartial".to_vec(),
            ),
            (20, Vec::new()),
        ]),
        "/gzip" => reply(
            "200 OK",
            &[("content-encoding", "gzip"), ("content-type", "text/plain")],
            GZIP_HELLO,
        ),
        "/br" => reply("200 OK", &[("content-encoding", "br")], BROTLI_HELLO),
        "/bom" => reply("200 OK", &[], b"\xEF\xBB\xBFhi \xFF!"),
        "/json" => reply(
            "200 OK",
            &[("content-type", "application/json")],
            br#"{"b":1,"a":[true,null]}"#,
        ),
        "/badjson" => reply("200 OK", &[], br#"{"a":"#),
        "/headers" => reply(
            "200 OK",
            &[
                ("content-type", "application/json"),
                ("x-dup", "1"),
                ("x-dup", "2"),
                ("set-cookie", "a=1"),
                ("set-cookie", "b=2"),
                ("x-latin", "caf\u{e9}"),
            ],
            b"{}",
        ),
        "/slow-headers" => Reply::Paced(vec![(
            2000,
            b"HTTP/1.1 200 OK\r\ncontent-length: 2\r\nconnection: close\r\n\r\nok".to_vec(),
        )]),
        "/slow-body" => Reply::Paced(vec![
            (
                0,
                b"HTTP/1.1 200 OK\r\ncontent-length: 10\r\nconnection: close\r\n\r\nfirst".to_vec(),
            ),
            (2000, b"second".to_vec()),
        ]),
        "/sse" => Reply::Paced(vec![
            (
                0,
                b"HTTP/1.1 200 OK\r\ncontent-type: text/event-stream\r\nconnection: close\r\n\r\n".to_vec(),
            ),
            (5, b"\xEF\xBB\xBFevent: start\ndata: {\"n\":1}\n".to_vec()),
            (5, b"\n: keep-alive\n\ndata: caf\xC3".to_vec()),
            (
                5,
                b"\xA9\r\ndata: two\r\n\r\nid: 3\nretry: 50\ndata: end\n\ndata: dangling".to_vec(),
            ),
        ]),
        _ => {
            let body = serde_json::json!({
                "method": req.method,
                "path": req.path,
                "content_type": req.header("content-type"),
                "authorization": req.header("authorization"),
                "body": String::from_utf8_lossy(&req.body),
            });
            reply(
                "200 OK",
                &[("content-type", "application/json")],
                body.to_string().as_bytes(),
            )
        }
    })
    .await
}

fn sorted_headers(req: &Captured) -> Vec<(String, String)> {
    let mut h: Vec<(String, String)> = req
        .headers
        .iter()
        .filter(|(k, _)| !k.eq_ignore_ascii_case("host"))
        .map(|(k, v)| (k.to_ascii_lowercase(), v.clone()))
        .collect();
    h.sort();
    h
}

fn pairs(list: &[(&str, &str)]) -> Vec<(String, String)> {
    let mut v: Vec<(String, String)> = list.iter().map(|(k, v)| (s(k), s(v))).collect();
    v.sort();
    v
}

// ---- Headers ------------------------------------------------------------------------------

#[test]
fn headers_validation_matches_undici() {
    let err = |pairs: &[(&str, &str)]| shape(&Headers::try_from_pairs(pairs.iter().copied()).unwrap_err());
    assert_eq!(
        err(&[("bad name", "x")]),
        (
            s("TypeError"),
            s("Headers.append: \"bad name\" is an invalid header name."),
            None
        )
    );
    assert_eq!(
        err(&[("", "x")]),
        (
            s("TypeError"),
            s("Headers.append: \"\" is an invalid header name."),
            None
        )
    );
    assert_eq!(
        err(&[("a", "x\ny")]),
        (
            s("TypeError"),
            s("Headers.append: \"x\ny\" is an invalid header value."),
            None
        )
    );
    assert_eq!(
        err(&[("a", "x\0y")]),
        (
            s("TypeError"),
            s("Headers.append: \"x\0y\" is an invalid header value."),
            None
        )
    );
    assert_eq!(
        err(&[("a", "x€y")]),
        (
            s("TypeError"),
            s(
                "Cannot convert argument to a ByteString because the character at index 1 has a value of 8364 which is greater than 255."
            ),
            None
        )
    );
    let mut h = Headers::new();
    assert_eq!(
        shape(&h.try_set("a", "😀").unwrap_err()).1,
        "Cannot convert argument to a ByteString because the character at index 0 has a value of 55357 which is greater than 255."
    );
    assert_eq!(
        shape(&h.try_set("a b", "x").unwrap_err()).1,
        "Headers.set: \"a b\" is an invalid header name."
    );
    let ok = Headers::try_from_pairs([("a", "xéy"), ("b", " \t x y \r\n")]).unwrap();
    assert_eq!(ok.get("a").as_deref(), Some("xéy"));
    assert_eq!(ok.get("b").as_deref(), Some("x y"));
    assert_eq!(ok.get("bad name"), None);
}

#[test]
fn headers_order_and_combining_match_whatwg() {
    let mut h = Headers::new();
    h.append("B", "1");
    h.append("a", "2");
    h.append("b", "3");
    h.set("A", "4");
    h.append("Set-Cookie", "x");
    h.append("set-cookie", "y");
    // Node: [["a","4"],["b","1, 3"],["set-cookie","x"],["set-cookie","y"]], "1, 3", ["x","y"], true
    assert_eq!(
        h.entries(),
        vec![
            (s("a"), s("4")),
            (s("b"), s("1, 3")),
            (s("set-cookie"), s("x")),
            (s("set-cookie"), s("y"))
        ]
    );
    assert_eq!(h.get("B").as_deref(), Some("1, 3"));
    assert_eq!(h.get_set_cookie(), vec![s("x"), s("y")]);
    assert!(h.has("SET-COOKIE"));
    assert_eq!(h.get("set-cookie").as_deref(), Some("x, y"));
    assert_eq!(h.keys(), vec![s("a"), s("b"), s("set-cookie"), s("set-cookie")]);
    // Names keep the casing of their first occurrence in the raw list.
    assert_eq!(h.raw()[0], (s("B"), s("1")));
    assert_eq!(h.raw()[1], (s("a"), s("4")));
    assert_eq!(h.raw()[2], (s("B"), s("3")));
    h.set("b", "5");
    assert_eq!(h.raw().iter().filter(|(k, _)| k.eq_ignore_ascii_case("b")).count(), 1);
    assert_eq!(h.raw()[0], (s("B"), s("5")));
    h.delete("SET-cookie");
    assert_eq!(h.entries(), vec![(s("a"), s("4")), (s("b"), s("5"))]);
    assert_eq!(
        Headers::from_pairs([("x", "1")]),
        [("X", "1")].into_iter().collect::<Headers>().with_lower_names()
    );
}

trait LowerNames {
    fn with_lower_names(self) -> Headers;
}

impl LowerNames for Headers {
    fn with_lower_names(self) -> Headers {
        Headers::from_pairs(self.raw().iter().map(|(k, v)| (k.to_ascii_lowercase(), v.clone())))
    }
}

// ---- SSE ----------------------------------------------------------------------------------

fn parse_all(parser: &mut SseParser, body: &[u8], chunk: usize) -> Vec<SseEvent> {
    body.chunks(chunk.max(1)).flat_map(|c| parser.feed(c)).collect()
}

#[test]
fn sse_parser_matches_undici_event_source() {
    for case in SSE {
        let expected: Vec<(String, String, String)> = case.events.iter().map(|(t, d, i)| (s(t), s(d), s(i))).collect();
        for chunk in [usize::MAX, 1, 2, 3, 7] {
            let got: Vec<(String, String, String)> = parse_all(&mut SseParser::new(), case.body, chunk)
                .into_iter()
                .map(|e| (e.event, e.data, e.id.unwrap_or_default()))
                .collect();
            assert_eq!(
                got,
                expected,
                "body {:?} in chunks of {chunk}",
                String::from_utf8_lossy(case.body)
            );
        }
    }
}

#[test]
fn sse_parser_reports_retry_and_persistent_id() {
    let events =
        SseParser::new().feed_str("retry: 1500\n\nid: 4\ndata: a\n\ndata: b\nretry: x\n\nretry: 20\ndata: c\n\n");
    assert_eq!(
        events,
        vec![
            SseEvent {
                event: s("message"),
                data: s("a"),
                id: Some(s("4")),
                retry: Some(1500)
            },
            SseEvent {
                event: s("message"),
                data: s("b"),
                id: Some(s("4")),
                retry: None
            },
            SseEvent {
                event: s("message"),
                data: s("c"),
                id: Some(s("4")),
                retry: Some(20)
            },
        ]
    );
    let mut p = SseParser::new();
    p.feed_str("id: 9\n");
    assert_eq!(p.last_event_id(), "9");
}

// ---- mock_fetch / deny_network -------------------------------------------------------------

#[tokio::test]
async fn mock_fetch_sees_the_request_as_built_and_restores_on_drop() {
    let seen = Arc::new(Mutex::new(Vec::new()));
    let log = seen.clone();
    let guard = testing::mock_fetch(move |req: Request| {
        log.lock().unwrap().push((
            req.method.clone(),
            req.url.clone(),
            req.headers.entries(),
            req.body_json(),
        ));
        Box::pin(async move {
            Ok(testing::response(
                201,
                &[("content-type", "application/json")],
                r#"{"ok":true}"#,
            ))
        })
    });
    let req = Request::post("https://api.example.com/v1/messages")
        .header("x-api-key", "k")
        .header("content-type", "application/json")
        .body(r#"{"model":"m","stream":true}"#);
    let res = fetch::fetch(req).await.unwrap();
    assert_eq!(res.status(), 201);
    assert!(res.ok());
    assert_eq!(res.status_text(), "");
    assert_eq!(res.url(), "");
    assert_eq!(res.json().await.unwrap(), serde_json::json!({"ok": true}));
    assert_eq!(
        seen.lock().unwrap().clone(),
        vec![(
            s("POST"),
            s("https://api.example.com/v1/messages"),
            vec![(s("content-type"), s("application/json")), (s("x-api-key"), s("k"))],
            Some(serde_json::json!({"model": "m", "stream": true})),
        )]
    );
    {
        let _inner = testing::deny_network();
        let err = fetch::fetch(Request::get("https://example.com/x")).await.unwrap_err();
        let (name, message, _) = fetch_failed(&err);
        assert_eq!(name, "Error");
        assert!(
            message.contains("deny_network") && message.contains("GET https://example.com/x"),
            "{message}"
        );
    }
    // The outer mock is back after the inner guard dropped.
    assert_eq!(fetch::fetch(Request::get("https://x/")).await.unwrap().status(), 201);
    drop(guard);
    assert_eq!(seen.lock().unwrap().len(), 2);
}

#[tokio::test]
async fn mock_fetch_is_thread_local() {
    let _guard = testing::mock_fetch(|_| Box::pin(async { Ok(testing::response(299, &[], "mocked")) }));
    let other = std::thread::spawn(|| {
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();
        rt.block_on(async {
            let _deny = testing::deny_network();
            fetch::fetch(Request::get("http://127.0.0.1:9/"))
                .await
                .map(|r| r.status())
                .map_err(|e| e.to_string())
        })
    })
    .join()
    .unwrap();
    assert_eq!(other, Err(s("fetch failed")));
    assert_eq!(
        fetch::fetch(Request::get("http://x/"))
            .await
            .unwrap()
            .text()
            .await
            .unwrap(),
        "mocked"
    );
}

#[tokio::test]
async fn constructed_responses_follow_body_rules() {
    let res = testing::response(200, &[("a", "1")], "hello");
    assert!(res.has_body());
    assert!(!res.body_used());
    assert_eq!(res.text().await.unwrap(), "hello");
    assert!(res.body_used());
    assert_eq!(
        shape(&res.text().await.unwrap_err()),
        (s("TypeError"), s("Body is unusable: Body has already been read"), None)
    );
    assert_eq!(
        shape(&res.body_stream().unwrap_err()),
        (
            s("TypeError"),
            s("Invalid state: ReadableStream is locked"),
            Some(s("ERR_INVALID_STATE"))
        )
    );

    let locked = testing::response(200, &[], "x");
    let _stream = locked.body_stream().unwrap();
    assert_eq!(
        shape(&locked.bytes().await.unwrap_err()).1,
        "Body is unusable: Body has already been read"
    );

    let null = Response::null_body(204, Headers::new());
    assert!(!null.has_body());
    assert_eq!(null.text().await.unwrap(), "");
    assert_eq!(null.text().await.unwrap(), "");
    assert!(!null.body_used());

    let chunked = testing::chunked_response(200, &[], vec!["a", "b", "c"]);
    let chunks: Vec<Bytes> = chunked.body_stream().unwrap().map(|c| c.unwrap()).collect().await;
    assert_eq!(chunks, vec![Bytes::from("a"), Bytes::from("b"), Bytes::from("c")]);

    let cancelled = testing::response(200, &[], "x");
    cancelled.cancel_body();
    assert!(cancelled.body_used());

    assert_eq!(
        shape(&testing::response(200, &[], "").json().await.unwrap_err()),
        (s("SyntaxError"), s("Unexpected end of JSON input"), None)
    );
    assert_eq!(
        shape(&testing::response(200, &[], r#"{"a":"#).json().await.unwrap_err()).1,
        "Unexpected end of JSON input"
    );
    // Node 24 `await new Response(body).json()` messages.
    for (body, message) in [
        (
            "{bad",
            "Expected property name or '}' in JSON at position 1 (line 1 column 2)",
        ),
        ("hello", "Unexpected token 'h', \"hello\" is not valid JSON"),
        ("[1,]", "Unexpected token ']', \"[1,]\" is not valid JSON"),
    ] {
        let err = testing::response(200, &[], body).json().await.unwrap_err();
        assert_eq!(shape(&err), (s("SyntaxError"), s(message), None), "{body}");
    }
    let bom = testing::response(200, &[], &b"\xEF\xBB\xBF{\"a\":1}"[..]);
    assert_eq!(bom.json().await.unwrap(), serde_json::json!({"a": 1}));

    let sse = testing::chunked_response(
        200,
        &[("content-type", "text/event-stream")],
        vec!["data: 1\n", "\ndata: 2\n\n"],
    );
    let events: Vec<String> = sse.sse().unwrap().map(|e| e.unwrap().data).collect().await;
    assert_eq!(events, vec![s("1"), s("2")]);
}

// ---- Request validation (network path) ----------------------------------------------------

#[tokio::test]
async fn request_validation_matches_undici() {
    let check = |req: Request| async move { shape(&fetch::fetch(req).await.unwrap_err()) };
    let url_err = fetch::fetch(Request::get("not a url")).await.unwrap_err();
    assert_eq!(
        shape(&url_err),
        (s("TypeError"), s("Failed to parse URL from not a url"), None)
    );
    assert_eq!(
        shape(cause(&url_err)),
        (s("TypeError"), s("Invalid URL"), Some(s("ERR_INVALID_URL")))
    );
    assert_eq!(
        check(Request::get("http://user:pw@127.0.0.1:1/")).await,
        (
            s("TypeError"),
            s("Request cannot be constructed from a URL that includes credentials: http://user:pw@127.0.0.1:1/"),
            None
        )
    );
    assert_eq!(
        check(Request::get("http://127.0.0.1:1/").body("x")).await,
        (
            s("TypeError"),
            s("Request with GET/HEAD method cannot have body."),
            None
        )
    );
    assert_eq!(
        check(Request::new("head", "http://127.0.0.1:1/").body("x")).await,
        (
            s("TypeError"),
            s("Request with GET/HEAD method cannot have body."),
            None
        )
    );
    assert_eq!(
        check(Request::new("CONNECT", "http://127.0.0.1:1/")).await,
        (s("TypeError"), s("'CONNECT' HTTP method is unsupported."), None)
    );
    assert_eq!(
        check(Request::new("trace", "http://127.0.0.1:1/")).await,
        (s("TypeError"), s("'trace' HTTP method is unsupported."), None)
    );
    assert_eq!(
        check(Request::new("BAD METHOD", "http://127.0.0.1:1/")).await,
        (s("TypeError"), s("'BAD METHOD' is not a valid HTTP method."), None)
    );
    assert_eq!(
        check(Request::get("http://127.0.0.1:1/").header("bad name", "x")).await,
        (
            s("TypeError"),
            s("Headers.append: \"bad name\" is an invalid header name."),
            None
        )
    );
    let ftp = fetch::fetch(Request::get("ftp://127.0.0.1/x")).await.unwrap_err();
    assert_eq!(fetch_failed(&ftp), (s("Error"), s("unknown scheme"), None));
    let file = fetch::fetch(Request::get("file:///etc/hosts")).await.unwrap_err();
    assert_eq!(fetch_failed(&file).1, "not implemented... yet...");
    let about = fetch::fetch(Request::get("about:blank")).await.unwrap_err();
    assert_eq!(fetch_failed(&about).1, "about scheme is not supported");
    for url in ["blob:http://x/0", "blob:http://x/0?"] {
        let blob = fetch::fetch(Request::get(url)).await.unwrap_err();
        assert_eq!(fetch_failed(&blob).1, "invalid method", "{url}");
    }
    let blob = fetch::fetch(Request::get("blob:http://x/0?q")).await.unwrap_err();
    assert_eq!(fetch_failed(&blob).1, "NetworkError when attempting to fetch resource.");
    let bad_port = fetch::fetch(Request::get("http://127.0.0.1:1/")).await.unwrap_err();
    assert_eq!(fetch_failed(&bad_port), (s("Error"), s("bad port"), None));
    let bad_port = fetch::fetch(Request::get("http://127.0.0.1:6667/")).await.unwrap_err();
    assert_eq!(fetch_failed(&bad_port).1, "bad port");
}

#[tokio::test]
async fn methods_are_normalized_like_undici() {
    let server = echo_server().await;
    for (given, sent) in [
        ("get", "GET"),
        ("Get", "GET"),
        ("post", "POST"),
        ("patch", "patch"),
        ("PATCH", "PATCH"),
        ("Patch", "Patch"),
        ("delete", "DELETE"),
        ("options", "OPTIONS"),
        ("purge", "purge"),
    ] {
        let res = fetch::fetch(Request::new(given, server.url("/echo"))).await.unwrap();
        assert_eq!(res.json().await.unwrap()["method"], sent, "{given}");
    }
}

// ---- Wire behaviour --------------------------------------------------------------------------

#[tokio::test]
async fn sends_undici_default_headers() {
    let server = echo_server().await;
    fetch::fetch(Request::get(server.url("/p?q=1")))
        .await
        .unwrap()
        .text()
        .await
        .unwrap();
    fetch::fetch(
        Request::post(server.url("/p"))
            .header("X-Custom", "A")
            .header("b-h", "1")
            .body("hello"),
    )
    .await
    .unwrap()
    .text()
    .await
    .unwrap();
    fetch::fetch(Request::post(server.url("/p")).body(vec![1u8, 2]))
        .await
        .unwrap()
        .text()
        .await
        .unwrap();
    fetch::fetch(Request::new("PUT", server.url("/p")))
        .await
        .unwrap()
        .text()
        .await
        .unwrap();
    fetch::fetch(
        Request::post(server.url("/p"))
            .header("content-type", "application/json")
            .header("User-Agent", "mine")
            .header("Accept-Encoding", "identity")
            .body(r#"{"a":1}"#),
    )
    .await
    .unwrap()
    .text()
    .await
    .unwrap();
    let reqs = server.requests();
    let base = [
        ("connection", "keep-alive"),
        ("accept", "*/*"),
        ("accept-language", "*"),
        ("sec-fetch-mode", "cors"),
    ];
    let with = |extra: &[(&'static str, &'static str)]| pairs(&[&base[..], extra].concat());
    // Expected sets come from Node 24's built-in fetch (see the module docs for `user-agent`).
    assert_eq!((reqs[0].method.as_str(), reqs[0].path.as_str()), ("GET", "/p?q=1"));
    assert_eq!(
        sorted_headers(&reqs[0]),
        with(&[("user-agent", "node"), ("accept-encoding", "gzip, deflate")])
    );
    assert_eq!(
        sorted_headers(&reqs[1]),
        with(&[
            ("x-custom", "A"),
            ("b-h", "1"),
            ("content-type", "text/plain;charset=UTF-8"),
            ("user-agent", "node"),
            ("accept-encoding", "gzip, deflate"),
            ("content-length", "5"),
        ])
    );
    assert_eq!(reqs[1].body, b"hello");
    assert_eq!(
        sorted_headers(&reqs[2]),
        with(&[
            ("user-agent", "node"),
            ("accept-encoding", "gzip, deflate"),
            ("content-length", "2")
        ])
    );
    assert_eq!(reqs[2].body, [1, 2]);
    assert_eq!(
        sorted_headers(&reqs[3]),
        with(&[
            ("user-agent", "node"),
            ("accept-encoding", "gzip, deflate"),
            ("content-length", "0")
        ])
    );
    assert_eq!(
        sorted_headers(&reqs[4]),
        with(&[
            ("content-type", "application/json"),
            ("user-agent", "mine"),
            ("accept-encoding", "identity"),
            ("content-length", "7")
        ])
    );
}

#[tokio::test]
async fn undici_rejects_or_strips_connection_level_headers() {
    let server = echo_server().await;
    let status = fetch::fetch(Request::get(server.url("/echo")).header("host", "evil"))
        .await
        .unwrap()
        .status();
    assert_eq!(status, 200);
    let res = fetch::fetch(Request::get(server.url("/echo")).header("connection", "close"))
        .await
        .unwrap();
    assert_eq!(res.status(), 200);
    res.text().await.unwrap();
    let reqs = server.requests();
    assert_eq!(reqs[0].header("host"), Some(server.addr.to_string().as_str()));
    assert_eq!(reqs[1].header("connection"), Some("close"));
    for (name, value, expected) in [
        (
            "transfer-encoding",
            "chunked",
            (
                "InvalidArgumentError",
                "invalid transfer-encoding header",
                "UND_ERR_INVALID_ARG",
            ),
        ),
        (
            "keep-alive",
            "timeout=5",
            (
                "InvalidArgumentError",
                "invalid keep-alive header",
                "UND_ERR_INVALID_ARG",
            ),
        ),
        (
            "upgrade",
            "websocket",
            ("InvalidArgumentError", "invalid upgrade header", "UND_ERR_INVALID_ARG"),
        ),
        (
            "expect",
            "100-continue",
            (
                "NotSupportedError",
                "expect header not supported",
                "UND_ERR_NOT_SUPPORTED",
            ),
        ),
    ] {
        let err = fetch::fetch(Request::get(server.url("/echo")).header(name, value))
            .await
            .unwrap_err();
        assert_eq!(
            fetch_failed(&err),
            (s(expected.0), s(expected.1), Some(s(expected.2))),
            "{name}"
        );
    }
}

#[tokio::test]
async fn redirects_follow_whatwg_rules() {
    let server = echo_server().await;
    for (path, method, expected_method, expected_ct, expected_body) in [
        ("/r301", "POST", "GET", None, ""),
        ("/r302", "POST", "GET", None, ""),
        ("/r303", "PUT", "GET", None, ""),
        ("/r307", "POST", "POST", Some("text/x"), "data"),
        ("/r301", "PUT", "PUT", Some("text/x"), "data"),
    ] {
        let res = fetch::fetch(
            Request::new(method, server.url(path))
                .header("content-type", "text/x")
                .header("authorization", "Bearer k")
                .body("data"),
        )
        .await
        .unwrap();
        assert_eq!(
            (res.status(), res.url(), res.redirected()),
            (200, server.url("/echo").as_str(), true),
            "{path} {method}"
        );
        let body = res.json().await.unwrap();
        assert_eq!(body["method"], expected_method, "{path} {method}");
        assert_eq!(body["content_type"].as_str(), expected_ct, "{path} {method}");
        assert_eq!(body["authorization"], "Bearer k", "{path} {method}");
        assert_eq!(body["body"], expected_body, "{path} {method}");
    }
    let head = fetch::fetch(Request::new("HEAD", server.url("/r303"))).await.unwrap();
    assert_eq!((head.status(), head.redirected(), head.has_body()), (200, true, false));

    let looped = fetch::fetch(Request::get(server.url("/loop"))).await.unwrap_err();
    assert_eq!(fetch_failed(&looped), (s("Error"), s("redirect count exceeded"), None));
    assert_eq!(server.requests().iter().filter(|r| r.path == "/loop").count(), 21);

    let noloc = fetch::fetch(Request::get(server.url("/noloc"))).await.unwrap();
    assert_eq!((noloc.status(), noloc.redirected()), (302, false));
    assert_eq!(noloc.text().await.unwrap(), "x");

    let badloc = fetch::fetch(Request::get(server.url("/badloc"))).await.unwrap_err();
    assert_eq!(fetch_failed(&badloc).1, "URL scheme must be a HTTP(S) scheme");

    let frag = fetch::fetch(Request::get(format!("{}#top", server.url("/frag"))))
        .await
        .unwrap();
    assert_eq!(frag.url(), server.url("/echo"));
}

#[tokio::test]
async fn cross_origin_redirects_drop_credentials() {
    let target = echo_server().await;
    let target_url = target.url("/echo");
    let origin = serve(move |_, _| reply("307 Temporary Redirect", &[("location", target_url.as_str())], b"")).await;
    let res = fetch::fetch(
        Request::post(origin.url("/start"))
            .header("authorization", "Bearer k")
            .header("cookie", "c=1")
            .header("x-keep", "1")
            .body("data"),
    )
    .await
    .unwrap();
    assert_eq!(res.url(), target.url("/echo"));
    res.text().await.unwrap();
    let seen = &target.requests()[0];
    assert_eq!(seen.header("authorization"), None);
    assert_eq!(seen.header("cookie"), None);
    assert_eq!(seen.header("x-keep"), Some("1"));
    assert_eq!(seen.body, b"data");
}

#[tokio::test]
async fn responses_expose_status_headers_and_decoded_bodies() {
    let server = echo_server().await;
    let res = fetch::fetch(Request::get(server.url("/headers"))).await.unwrap();
    assert_eq!((res.status(), res.status_text(), res.ok()), (200, "OK", true));
    let entries: Vec<(String, String)> = res
        .headers()
        .entries()
        .into_iter()
        .filter(|(k, _)| k != "connection" && k != "content-length")
        .collect();
    assert_eq!(
        entries,
        vec![
            (s("content-type"), s("application/json")),
            (s("set-cookie"), s("a=1")),
            (s("set-cookie"), s("b=2")),
            (s("x-dup"), s("1, 2")),
            (s("x-latin"), s("caf\u{c3}\u{a9}")),
        ]
    );

    let gzip = fetch::fetch(Request::get(server.url("/gzip"))).await.unwrap();
    assert_eq!(gzip.text().await.unwrap(), "hello gzip");
    let br = fetch::fetch(Request::get(server.url("/br"))).await.unwrap();
    assert_eq!(br.text().await.unwrap(), "hello br");

    let bom = fetch::fetch(Request::get(server.url("/bom"))).await.unwrap();
    assert_eq!(bom.text().await.unwrap(), "hi \u{fffd}!");

    let json = fetch::fetch(Request::get(server.url("/json"))).await.unwrap();
    let value = json.json().await.unwrap();
    assert_eq!(value, serde_json::json!({"b": 1, "a": [true, null]}));
    assert_eq!(value.as_object().unwrap().keys().collect::<Vec<_>>(), ["b", "a"]);

    let bad = fetch::fetch(Request::get(server.url("/badjson"))).await.unwrap();
    assert_eq!(
        shape(&bad.json().await.unwrap_err()),
        (s("SyntaxError"), s("Unexpected end of JSON input"), None)
    );

    let no_content = fetch::fetch(Request::get(server.url("/204"))).await.unwrap();
    assert_eq!((no_content.status(), no_content.has_body()), (204, false));
    assert_eq!(no_content.text().await.unwrap(), "");

    let head = fetch::fetch(Request::new("HEAD", server.url("/json"))).await.unwrap();
    assert!(!head.has_body());
}

#[tokio::test]
async fn premature_close_is_terminated_other_side_closed() {
    let server = echo_server().await;
    let res = fetch::fetch(Request::get(server.url("/close"))).await.unwrap();
    let err = res.text().await.unwrap_err();
    assert_eq!(shape(&err), (s("TypeError"), s("terminated"), None));
    assert_eq!(
        shape(cause(&err)),
        (s("SocketError"), s("other side closed"), Some(s("UND_ERR_SOCKET")))
    );
}

#[tokio::test]
async fn connection_refused_matches_node() {
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    drop(listener);
    let err = fetch::fetch(Request::get(format!("http://127.0.0.1:{port}/")))
        .await
        .unwrap_err();
    fetch_failed(&err);
    match cause(&err) {
        Error::Node(NodeError {
            code,
            errno,
            syscall,
            message,
            ..
        }) => {
            assert_eq!(code, "ECONNREFUSED");
            assert_eq!(syscall, "connect");
            assert_eq!(message, &format!("connect ECONNREFUSED 127.0.0.1:{port}"));
            #[cfg(unix)]
            assert_eq!(*errno, -libc_econnrefused());
            #[cfg(not(unix))]
            let _ = errno;
        }
        other => panic!("expected a Node error, got {other:?}"),
    }
}

#[cfg(unix)]
fn libc_econnrefused() -> i32 {
    std::io::Error::from(std::io::ErrorKind::ConnectionRefused)
        .raw_os_error()
        .unwrap_or(if cfg!(target_os = "linux") { 111 } else { 61 })
}

#[tokio::test]
async fn abort_rejects_with_the_signal_reason() {
    let server = echo_server().await;
    let pre = AbortController::new();
    pre.abort(None);
    let err = fetch::fetch(Request::get(server.url("/echo")).signal(pre.signal()))
        .await
        .unwrap_err();
    assert_eq!(shape(&err).0, "AbortError");
    assert_eq!(shape(&err).1, "This operation was aborted");
    assert!(err.is_abort());

    let custom = AbortController::new();
    custom.abort(Some(AbortReason::error("Error", "stop now")));
    let err = fetch::fetch(Request::get(server.url("/echo")).signal(custom.signal()))
        .await
        .unwrap_err();
    assert_eq!((shape(&err).0, shape(&err).1), (s("Error"), s("stop now")));

    let during = AbortController::new();
    let signal = during.signal();
    let pending = tokio::spawn(fetch::fetch(Request::get(server.url("/slow-headers")).signal(signal)));
    tokio::time::sleep(Duration::from_millis(50)).await;
    during.abort(None);
    let err = pending.await.unwrap().unwrap_err();
    assert_eq!(shape(&err).1, "This operation was aborted");

    let timeout = fetch::fetch(Request::get(server.url("/slow-headers")).signal(AbortSignal::timeout(50)))
        .await
        .unwrap_err();
    assert_eq!(
        (shape(&timeout).0, shape(&timeout).1),
        (s("TimeoutError"), s("The operation was aborted due to timeout"))
    );

    let mid = AbortController::new();
    let res = fetch::fetch(Request::get(server.url("/slow-body")).signal(mid.signal()))
        .await
        .unwrap();
    let mut stream = res.body_stream().unwrap();
    assert_eq!(stream.next().await.unwrap().unwrap(), Bytes::from("first"));
    mid.abort(None);
    let err = stream.next().await.unwrap().unwrap_err();
    assert_eq!(
        (shape(&err).0, shape(&err).1),
        (s("AbortError"), s("This operation was aborted"))
    );
    assert!(stream.next().await.is_none());
}

#[tokio::test]
async fn streams_sse_over_the_network() {
    let server = echo_server().await;
    let res = fetch::fetch(Request::get(server.url("/sse"))).await.unwrap();
    assert_eq!(res.headers().get("content-type").as_deref(), Some("text/event-stream"));
    let events: Vec<SseEvent> = res.sse().unwrap().map(|e| e.unwrap()).collect().await;
    assert_eq!(
        events,
        vec![
            SseEvent {
                event: s("start"),
                data: s("{\"n\":1}"),
                id: None,
                retry: None
            },
            SseEvent {
                event: s("message"),
                data: s("café\ntwo"),
                id: None,
                retry: None
            },
            SseEvent {
                event: s("message"),
                data: s("end"),
                id: Some(s("3")),
                retry: Some(50)
            },
        ]
    );
}

#[tokio::test]
async fn data_urls_match_undici() {
    for (url, expected) in DATA_URLS {
        let got = match fetch::fetch(Request::get(*url)).await {
            Ok(res) => {
                let meta = (
                    res.status(),
                    s(res.status_text()),
                    res.headers().get("content-type").unwrap_or_default(),
                    s(res.url()),
                );
                Ok((meta, res.bytes().await.unwrap().to_vec()))
            }
            Err(e) => Err(fetch_failed(&e).1),
        };
        let want = match expected {
            Ok((status_text, content_type, body, res_url)) => {
                Ok(((200, s(status_text), s(content_type), s(res_url)), body.to_vec()))
            }
            Err(message) => Err(s(message)),
        };
        assert_eq!(got, want, "{url}");
    }
}

#[test]
fn request_and_body_helpers() {
    let req = Request::post("http://x/").body(vec![0xFFu8, b'a']);
    assert_eq!(req.body_text().as_deref(), Some("\u{fffd}a"));
    assert_eq!(req.body_json(), None);
    assert_eq!(Request::default().method, "GET");
    let body: Body = "abc".into();
    assert_eq!((body.len(), body.as_bytes()), (3, &b"abc"[..]));
    assert_eq!(
        Body::from(Bytes::from_static(b"x")),
        Body::Bytes(Bytes::from_static(b"x"))
    );
    let dbg = format!("{:?}", Request::get("http://x/").header("a", "1"));
    assert!(dbg.contains("\"a\": \"1\""), "{dbg}");
}

#[test]
fn default_client_is_shared_and_replaceable() {
    let a = fetch::default_client();
    let b = fetch::default_client();
    // reqwest clients are handles; formatting both shows the same configuration.
    assert_eq!(format!("{a:?}"), format!("{b:?}"));
    assert!(format!("{a:?}").contains("node"), "{a:?}");
}

#[tokio::test]
async fn idle_timeouts_map_to_undici_errors() {
    let server = echo_server().await;
    let client = fetch::client_builder()
        .read_timeout(Duration::from_millis(200))
        .build()
        .unwrap();
    let err = fetch::fetch_with_client(&client, Request::get(server.url("/slow-headers")))
        .await
        .unwrap_err();
    assert_eq!(
        fetch_failed(&err),
        (
            s("HeadersTimeoutError"),
            s("Headers Timeout Error"),
            Some(s("UND_ERR_HEADERS_TIMEOUT"))
        )
    );
    let res = fetch::fetch_with_client(&client, Request::get(server.url("/slow-body")))
        .await
        .unwrap();
    let err = res.text().await.unwrap_err();
    assert_eq!(shape(&err), (s("TypeError"), s("terminated"), None));
    assert_eq!(
        shape(cause(&err)),
        (
            s("BodyTimeoutError"),
            s("Body Timeout Error"),
            Some(s("UND_ERR_BODY_TIMEOUT"))
        )
    );
}

#[tokio::test]
async fn custom_clients_set_the_user_agent() {
    // http-dispatcher.ts installs npm undici, whose fetch sends `user-agent: undici`.
    let server = echo_server().await;
    let client = fetch::client_builder().user_agent("undici").build().unwrap();
    fetch::fetch_with_client(&client, Request::get(server.url("/echo")))
        .await
        .unwrap()
        .text()
        .await
        .unwrap();
    fetch::fetch_with_client(&client, Request::get(server.url("/echo")).header("user-agent", "mine"))
        .await
        .unwrap()
        .text()
        .await
        .unwrap();
    let reqs = server.requests();
    assert_eq!(reqs[0].header("user-agent"), Some("undici"));
    assert_eq!(reqs[1].header("user-agent"), Some("mine"));
}

#[tokio::test]
async fn dns_failures_are_getaddrinfo_errors() {
    let err = fetch::fetch(Request::get("http://nonexistent.invalid/"))
        .await
        .unwrap_err();
    match cause(&err) {
        Error::Node(NodeError {
            code, syscall, message, ..
        }) => {
            assert_eq!(syscall, "getaddrinfo");
            assert!(code == "ENOTFOUND" || code == "EAI_AGAIN", "{code}");
            assert_eq!(message, &format!("getaddrinfo {code} nonexistent.invalid"));
        }
        other => panic!("expected a getaddrinfo error, got {other:?}"),
    }
}
